### ISSUE TITLE
Rotate/Scale vertices around center of mass of selected vertices or custom pivot/origin

### ISSUE THREAD

**Issue by ghost** [ousnius/BodySlide-and-Outfit-Studio#101]
To be able to create slider data more easily in OutfitStudio, it would be nice to have a possibility to rotate/scale vertices around the center of mass of the selected vertices or around a custom pivot/origin.

This would help to create slider data for breast, butt, waist (everything which is circular or spherically shaped) as well as bend knees, ankles, feet correctly for high heeled outfits.

**Comment by ousnius** [comment]
This might take a while until we get to it, since it would mean we finally have to implement proper 3D controls for the transform actions in the renderer that can be interacted with.

Otherwise it would probably just become a clunky addition. But yes, it would be very useful of course.

**Comment by ghost** [comment]
Sure, good things take time.

But I think it would not be neccessary to implement full 3D controls like in 3DSMAX or Maya. 

Maybe a bone skeleton based manipulation tool might suffice, since we are not doing anything else than bodies and outfits.

So it could be enough to have a way to scale around the bone axis and rotate around bone joints.

Kind of "Poser/Puppeteer" approach, if I would think in concepts rather than features.

This however seems to be more sophisticated than the initial suggestion I made.

**Comment by ousnius** [comment]
Moving and rotating unmasked vertices around the center of mass or the origin (0,0,0) was implemented in the form of 2ec5000.

Switching between Object/Selected/Origin is done in the Config.xml currently.

**Comment by ghost** [comment]
Great work on this. Thanks!
