### ISSUE TITLE
Existing Cloth Bones Don't Export or Import

### ISSUE THREAD

**Issue by Nightasy** [ousnius/BodySlide-and-Outfit-Studio#105]
One thing I would like to request, which I'm guessing would fall in Cali's realm, would be to allow for the export of the cloth bones with the fbx exporter. Currently if you export anything with a cloth bone in the rigging, such as a dress, it does not export the cloth bones or the weights assigned to those cloth bones. I also can't add the cloth bones to the rigging in Maya, name and position them properly and then export them back into OS. It won't accept any bones that aren't in the default skeleton. This creates a lot of limitations towards getting properly rigged physics with precision weighting on models.

I'm not requesting being able to create new bones and import them. Just being able to export and import existing cloth bones would be a game changer for working with physics. I could do a lot with that functionality were it available.

**Comment by ousnius** [comment]
Hierarchy is dropped for most skeleton bones.
Fix TBD.

**Comment by sabudum** [comment]
Still can't import cloth bones from FBX files, which makes creating custom dress or skirt or coat shapes with different cloth bones impossible.
