### ISSUE TITLE
Exit after building complete if using command-line arguments (or add /q argument)

### ISSUE THREAD

**Issue by philippeop** [ousnius/BodySlide-and-Outfit-Studio#115]
The new commands for bodyslide are awesome, they let me build each outfit groups into their own folders for use with Mod Organizer.

But I'dd love to be able to run my Build.bat file without having to exit out of Bodyslide for each outfit group.

Would it be possible to add a /q argument to tell BS to quit after the build task?

**Comment by ousnius** [comment]
Since running with the group build argument to begin with means you merely want to build stuff, I think it's even better if I simply always close BodySlide after it's done, without an additional argument.

**Comment by ousnius** [comment]
Implemented in 7215bfa.
