### ISSUE TITLE
Command-line argument /p for batch build is ignored

### ISSUE THREAD

**Issue by philippeop** [ousnius/BodySlide-and-Outfit-Studio#116]
/p is ignored, Config.xml's SelectedPreset is used instead.

Example, running this command:

> "BodySlide x64.exe" /gbuild "CBBE Bodies" /p "CBBE Curvy" /t "C:\Fallout4Mods\mods\CBBE\"

Produces

> [#Log Wed May 18 18:04:22 2016]
> [18:04:22][3]   BodySlideApp.cpp(78): Initializing BodySlide...
> [18:04:22][3]   BodySlideApp.cpp(93): Working directory: C:\SteamGames\SteamApps\common\Fallout 4\data\Tools\BodySlide
> [18:04:22][3]   BodySlideApp.cpp(986): Game data path in config: C:\SteamGames\SteamApps\common\Fallout 4\data\
> [18:04:22][3]   BodySlideApp.cpp(106): Target game: Fallout 4
> [18:04:22][3]   BodySlideApp.cpp(1061): Loading all slider categories...
> [18:04:22][3]   BodySlideApp.cpp(1091): Loading all slider groups...
> [18:04:22][3]   BodySlideApp.cpp(120): Loading BodySlide frame at X:733 Y:212 with W:800 H:809...
> [18:04:23][3]   BodySlideApp.cpp(138): BodySlide initialized.
> [18:04:23][3]   BodySlideApp.cpp(258): Loading initial data...
> [18:04:23][3]   BodySlideApp.cpp(279): Setting up set 'CBBE Body'...
> [18:04:23][3]   BodySlideApp.cpp(1086): Using group(s): 'CBBE' 
> [18:04:23][3]   BodySlideApp.cpp(1247): Loading assigned presets...
> [18:04:23][3]   BodySlideApp.cpp(345): Loading all slider sets...
> [18:04:23][3]   BodySlideApp.cpp(300): Creating sliders...
> [18:04:24][3]   BodySlideApp.cpp(296): Finished setting up 'CBBE Body'.
> [18:04:24][3]   BodySlideApp.cpp(421): Applying preset 'Imitation - UNP #2' to sliders.
> [18:04:24][3]   BodySlideApp.cpp(1485): Started batch build with options: Custom Path = C:\Fallout4Mods\mods\CBBE\, Cleaning = False, TRI = False
> [18:04:24][3]   BodySlideApp.cpp(1557): Processing 'CBBE Body Physics' (1 of 1)...
> [18:04:24][3]   BodySlideApp.cpp(1800): All group build sets processed successfully!
> [18:04:26][3]   BodySlideApp.cpp(2172): BodySlide closed.

I'm running Windows 10 64 bit, Bodyslide 64 bit, version 3.5. I use it mostly from inside Mod Organizer 2.0.5 but I've validated that it does the same behavior

**Comment by ousnius** [comment]
I'll take a look at it and see what's going on.

**Comment by ousnius** [comment]
This is merely the log saying that it loaded the last selected preset after the UI was initialized. The preset that is used for the actual batch build should be the one in your command-line argument.

Are you sure the built NIF files don't have the shape of the preset in your command-line arguments?

**Comment by philippeop** [comment]
You are right, I tested it and using /p "CBBE Chubby" while the conf has CBBE Slim produced the chubby body. I might have previously made a typo in the preset to use when testing this issue out.

Everything works as intended.
