### ISSUE TITLE
How do I know the current presets for a given Outfit/Body?

### ISSUE THREAD

**Issue by flipperbw** [ousnius/BodySlide-and-Outfit-Studio#117]
Apologies if I'm missing something obvious, but when I select an Outfit/Body, is there any way to know in advance the preset it _currently_ has applied to it? This would be pretty helpful so I don't accidentally overwrite good configurations with a batch build.

**Comment by ousnius** [comment]
You mean the preset used for the NIF files that have already been built into your game folder? There's no way to retroactively figure that out from the NIF, no.

**Comment by flipperbw** [comment]
Okay. That would be a very nice feature to have when you have time (maybe just a file that contains the last saved preset for that NIF). Thanks.

**Comment by ousnius** [comment]
It might sound like a good feature, but really one should just save the presets so they're not lost instead of having the program save files for every built thing. Closing for now. :)

**Comment by flipperbw** [comment]
Well, I do save all the presets - I meant more along the lines of wanting different presets for different groups or outfits.
