### ISSUE TITLE
[Feature Request] NiOverride High Heels Slider

### ISSUE THREAD

**Issue by Nucleoprotein** [ousnius/BodySlide-and-Outfit-Studio#127]
Hello,

Adding NiOverride High Heels (http://www.nexusmods.com/skyrim/mods/70581/?) Slider will make even easier to create proper high heels. This heels system does not require any scripting - only to attach `NiStringExtraData` to any `NiTriShape` in boots with name `SDTA` and data `[{"name":"NPC","pos":[0, 0, <height>]}]` where `height` is float value of heel height (same as value used in HDT High Heels system spell).

Thanks.

**Comment by ousnius** [comment]
I know of the NiO High Heels system - it was me who made it together with Expired. :)

However, I can't make Outfit Studio or BodySlide add it to boots automatically. The boots mesh has to be made for high heels for it to work well, and there will only be issues if I make it automatic.

Thanks for the suggestion though, but people will have to add the NiStringExtraData manually. You can use either NifSkope to add it or Outfit Studio in the "Shape Properties" window.
