### ISSUE TITLE
BodySlide application is completely blank

### ISSUE THREAD

**Issue by Nightslaeyer** [ousnius/BodySlide-and-Outfit-Studio#128]
When i run the program through either NMM or using the exe it self, it opens up but there are no options. No sliders or presets nothing. I cant figure out where i went wrong and i could really use some help.

**Comment by ousnius** [comment]
Are you trying to use it for SK, FO4 or SSE?

For SK, you should use the installer that comes with it.
For FO4, you need to install a body mod separately, such as CBBE.
For SSE - there's nothing coming with that right now. You'd have to figure out how to add projects to it yourself until there's new bodies for it.

If you use NMM or MO, you have to run BodySlide through their interface.

**Comment by elee0763** [comment]
How do you run Bodyslide through NMM? clicking on it just uninstalls it

**Comment by ousnius** [comment]
@elee0763 Using the "Supported Tools" button in the toolbar at the top.

Left-clicking starts the program, right-clicking you can select a different folder in your game's data directory where it looks for the executable.

This only works for the Skyrim and FO4 game modes of NMM right now, not yet for SSE.

**Comment by Nightslaeyer** [comment]
Im using SSE and i just want to modify the body of my character with more detail than the creation. So i cant do that with the mod yet? Is there a mod that will do that? i know in the original there was Enhanced Character Creation or something along those lines and thats what im looking for really.

**Comment by elee0763** [comment]
@ousnius thank you, worked like a charm!

**Comment by ousnius** [comment]
@Nightslaeyer You need to install addons for BodySlide or it will be empty. There is no official body for SSE as of now, so you either have to wait until one is released or try to get one of the old ones working in the SSE BodySlide.

**Comment by Nightslaeyer** [comment]
Ahhh alright, thanks

**Comment by vararth** [comment]
So I am trying out Enderal SSE and though I've never faced this issue before, the exe is opening but is completely empty. Having played the game for years without an issue with Bodyslide, this is the first time such an error has shown up..
