### ISSUE TITLE
Customize Mesh/Textures Path

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#129]
This is a feature request or at least a feature to consider, although its usage may be very limited and/or relatively rarely used:

**Use Case:** Let's assume you use a custom race (ningheim, f.e. or any other race) and you want player exclusive textures and/or meshes. **Why?** 4-8k textures and high poly models for the player, and "low res/performance" texture versions for normal NPCs.

**What you got to do now:** So what I did to tackle this was copying the "Unified UNP" (in my case) files, renaming them to `CustomRaceUUNP*Special`and changing the texture paths of the `NiTriShapes` to the custom race folder (e.g. `textures\CustomRaces\CustomNord\femalebody_1.dds`). I then copied the `SliderSet` for `Unified UNP`, renamed it and adjusted it's `SourceFile` and `OutputPath` for all the individual SliderSets.

**How it should/could be:** Add an option f.e. in the option pane to enter a `overwrite path` for `OutputPath` and the texture path for the `NiTriShapes`. When you then build a body, it uses the normal `.nif` files (f.e. `UUNPSpecial.nif`), adjusts the `BSShaderTextureSet` accordingly, and creates the body files in the `OutputPath`. 
So in the above example you would enter `textures\CustomRaces\CustomNord\` as the texture path and `meshes\CustomRaces\CustomNord\` as the `OutputPath`.

This would basically save you the time of adjusting texture paths of `.nifs` that were created with BodySlide and used for other races.

**Comment by ousnius** [comment]
Editing the texture set paths in the NIF files isn't needed for body and head meshes, they are being fully overwritten by the game with the plugin (.esm or .esp file).

It doesn't matter what's in the BSShaderTextureSet at all (other than for looking at it in NifSkope).
So, the only thing would be changing the actual output path to build into the custom race's folder.

A feature for that isn't necessary though, as you can simply hold down the CTRL key and batch build the body directly into the folder yourself (or just re-save the project in Outfit Studio for yourself for convenience).

Good suggestion, but having multiple outfits paths is too much hassle to implement for not enough use, sorry! :)

**Comment by CNKTHoward** [comment]
Oh, ok. I was under the impression, that I (and that is for my installation) **had** to change the `BSShaderTextureSet`. Clearly I know too little about how the game handles nifs, .esp/.esm, textures and all that stuff. 
Anyway, even if you had to change the texture path, this wasn't really something that had to be done, since updating the paths only takes like 5 minutes tops. 

Thanks for the clarification on the matter ;)

**Comment by Lukong15** [comment]
HAHAHA...changing the paths takes 5mins, trying doing that with something that has 23 pieces and all have the same texture paths...I just lazily copy the material only (Which works cause I think I see no difference between No-Texture-Path Mesh and Texture-Path Mesh in game)

The only way to do it faster than
**Default Workflow**
Open mesh's Properties > Copy 1 Thing or Memorize the rest of each section > Close mesh's Properties > Open another Properties > Paste that 1 Thing or Change in the other Properties's sections > Repeat Everything Per Mesh

**Textbox Workflow**
Open mesh's Properties > Copy everything or Memorize the rest into a Textbox (Windows 7 Notepad, Wordpad, StickyNotes) > Close mesh's Properties > Open another Properties > Paste everything into each section or Change in the other Properties's section > Repeat Pasting per Mesh 

**Concept & Paste Workflow** https://github.com/ousnius/BodySlide-and-Outfit-Studio/issues/139

## This might not be necessary if Materials is actually taking care of all the Texture Path (What I learned from the Thread below) cause without the Material Path, Mesh is invisible.

**Comment by Lukong15** [comment]
Actually some Shapes don't use Material like if someone were to edit the pipboy
