### ISSUE TITLE
Preview Window

### ISSUE THREAD

**Issue by nomadwarmachine01** [ousnius/BodySlide-and-Outfit-Studio#130]
I have updated to 4.1.2 and the preview window is no longer populating the outfit/body and presets that are selected.

All of my outfit/body and presets are present in the drop downs. I am wondering if NMM put something in the wrong place? If so, what am I looking for to put it back in the right spot? Any help would be greatly appreciated.

**Comment by ousnius** [comment]
Preview and sliders are working fine for me. I'm guessing it has something to do with NMM.

Try disabling any anti-virus software, re-downloading and installing BodySlide, running everything as an admin and re-selecting the BodySlide folder in the NMM toolbar (right-click on "Launch BodySlide").

You can also try running it both from within and without NMM.

**Comment by nomadwarmachine01** [comment]
I had done these steps prior to reaching out, with the exception of the antivirus protection getting turned off. I turned it off and did the steps again. The preview window is still not displaying anything. There is a 0 to 100 slider at the top, which I do not recall from previous editions.

**Comment by nomadwarmachine01** [comment]
While batch building my meshes, they all failed. To figure out why I looked at the file path that Bodyslide was expecting and found that an extra folder had been created during install somewhere along the way.

Once I moved my folders out of the extra folder and into the correct one, the preview window is now working correctly. Thank you for your help!
