### ISSUE TITLE
Question: Multithreaded Outfit Creation

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#133]
I was skimming through the code and I'm curious why there isn't any multithreading for the outfit creation. I think each outfit is processed in this function `BodySlideApp::BuildListBodies`, which could be easily wrapped and multithreaded. If nothing speaks against that I'd want to do a PR that addresses that.

**Comment by ousnius** [comment]
There is multithreading already and it's enabled by default for the 64-bit build.
32-bit builds can't have enough memory for some big outfits in big outfit packs, so I had to disable it there as people kept getting crashes.

It was added in July and it's done using Microsoft's PPL:
`concurrency::parallel_for_each(outfitList.begin(), outfitList.end(), [&](const string& outfit)`

When run on an HDD, the limiting factor is probably the drive, not the CPU (threading). SSDs are fast enough for the CPU to go all the way to 100% with a batch build.
