### ISSUE TITLE
Drag and Drop Not Functioning

### ISSUE THREAD

**Issue by nomadwarmachine01** [ousnius/BodySlide-and-Outfit-Studio#136]
I am unable to drag and drop nifs into OS. I run OS as an admin and have unistalled and reinstalled OS and it has not fixed itself. The funny thing is that I can drag and drop nifs from Skyrim into the Skyrim OS, but not FO4 nifs into OS. My thoughts are one of the settings is messed up or I am missing a file but have not idea which one it could be or how to fix it.

I saw that this was an issue that was fixed with the last update but I am still unable to drag and drop. Any help would be appreciated.

**Comment by ousnius** [comment]
This is a Windows-specific issue that I can do nothing about. You can only drag and drop files from folders that have, I think, the same level of privileges that the program was run with. That means the program folder and maybe the user folders of your Windows user, but not from anywhere else.

You'll have to play around with where you can drag files from.

**Comment by Lukong15** [comment]
Funny I was able to do this, but these NIFs came from 3DSMax and where on my desktop, but bodyslide was in my Documents.

**Comment by ousnius** [comment]
The desktop and documents folders have the same level of privileges as they're both in your user folder, as I said above.

**Comment by Lukong15** [comment]
Not saying it didn't work, I'm saying they weren't in User Folder (Unless by User you mean C:/User and not the same Folder)...then I misunderstood you...and am having no problems.
