### ISSUE TITLE
Load Outfit, Can't load texture from file browse

### ISSUE THREAD

**Issue by anhexpoke** [ousnius/BodySlide-and-Outfit-Studio#145]
Hi.
I have noticed one thing. I'm not familiar with GitHub. I'm sorry if I write poorly.

It's loading textures, but Fatal exception will come out.
I am a windows 10 (64 bit), windows 7 (64 bit) user.
I am not a C ++ technician, but I can read the program a bit.

I will write the steps to reproduce the error.
BodySlide.exe → Bottom right, Outfit Studio → File → Load Outfit → Mesh (as appropriate) → Textures, From File Browse → specify a texture file (dds, png, jpg ...) → Fatal exception pop
The error content is "Fatal exception has occurred, the program will terminate."

I tried various things and noticed
Check from the file and it seems I do not want to have letters in the file path.

I saw Log.txt.
[00: 46: 36] [3] OutfitStudio.cpp (1162): Loading outfit ...
[00: 46: 36] [1] Fatal exception has occurred, the program will terminate.

I then chased the source.

OutfitStudio.cpp
1167 wxLogMessage ("Loading outfit ...")

Maybe this is Log.txt's "OutfitStudio.cpp (1162): Loading outfit ..."

And

1208 wxLogMessage ("Creating outfit ...")

Not reached here.

Probably the problem is

1206 project-> SetTextures (XRCCTRL (dlg, "npTexFilename", wxFilePickerCtrl) -> GetPath (). ToStdString ());

I think that.

This "SetTextures" probably is in OutfitProject.cpp

1013 void OutfitProject :: SetTextures (const string & shapeName, const vector <string> & textureFiles) {

I think that OutfitStudio.cpp calling this.
From this point on, I don't really understand.

Please check it :)

**Comment by ousnius** [comment]
Thanks for the find, it's fixed in f25d109.

Keep in mind that the texture selection you were trying to use applies only that one specific texture file to all meshes in the NIF you're loading. It's supposed to be used for testing purposes.

The real texture selection is in the shape properties when you double-click a shape.

**Comment by anhexpoke** [comment]
Thank you for responding quickly.
It's a very good software, so I'm glad it got better.

My friends use outfit studio via NEXUS.
If you get a break, make sure that they are available.
They are waiting.
