### ISSUE TITLE
Problem with coping skirt skin weight

### ISSUE THREAD

**Issue by Vitriks** [ousnius/BodySlide-and-Outfit-Studio#146]
I use Irma Outfit as reference. Copy all the waits to my mesh. In game physics works but the whole mesh look glitched. 

![c45598e69a7779c717f2c02d6230af4b](https://cloud.githubusercontent.com/assets/26214248/23597972/d614ef6e-023f-11e7-8daa-a8743ffb1cb1.jpg)

**Comment by ousnius** [comment]
Not sure what this could be... try using the body as a reference for the bones that aren't for physics. In any case, this is something for the mod page, not GitHub.
