### ISSUE TITLE
Slow Load

### ISSUE THREAD

**Issue by Lu5ck** [ousnius/BodySlide-and-Outfit-Studio#147]
Hi,

BodySlide and Outfit Studio seems to load very slow for CBBE body that is packaged into ba2. It also seems to be repeating the same loading process for every outfit.

It would be great if there is some forms of caching for those body.

**Comment by ousnius** [comment]
There's already a cache for textures/materials, it can't really be made all that much faster. It could also be the slider data that takes long to load for you, and it also depends on your hardware.

**Comment by Lu5ck** [comment]
That is strange. If I didn't package CBBE into ba2, it will load much faster.

**Comment by ousnius** [comment]
That's normal, because contents in a BA2 archive have to be decompressed first, which adds additional CPU overhead.

**Comment by Lu5ck** [comment]
But you mention there is a cache. o.O

**Comment by ousnius** [comment]
If there's anything that can be improved in terms of BSA/BA2 performance, it will be with a new library, maybe at some point. For now I'm closing this.
