### ISSUE TITLE
Blank screen on Installation

### ISSUE THREAD

**Issue by raydleemsc** [ousnius/BodySlide-and-Outfit-Studio#148]
Onstalled ok by NMM in the data folder, pointed to the SSE game that it's installed into, but BS window is blank except for basic fields - no default loaded. outfit/body dropdown is empty as is preset. Settings dialogue data files shows the bsas that it should be able to see, but nothing available.

**Comment by raydleemsc** [comment]
Seen sticky - application is essentially redundant until CBBE is available, right?

**Comment by ousnius** [comment]
Unless you manually install bodies/outfits that come from the old Skyrim, for which there is no support from our side, yes.
