### ISSUE TITLE
BSMeshLODTriShape "LOD Size" Not Set When Separating Vertices

### ISSUE THREAD

**Issue by deadite81** [ousnius/BodySlide-and-Outfit-Studio#149]
Hi!  I've been finding your program very useful for editing Fallout 4 static meshes.  I've run into an issue you might want to know about.

When separating a mesh with "LOD" (BSMeshLODTriShape instead of BSTriShape) data into multiple shapes the "LOD# Size" fields don't get updated.

![lodsize](https://cloud.githubusercontent.com/assets/231300/25023086/827c5898-2066-11e7-90d7-730945d1a238.PNG)

For the meshes I'm working with "LOD2 Size" should be equal to the number of triangles as in the above screenshot from NifSkope.  I have not found any meshes that utilize the other LOD fields yet, if they exists, and am only using your program with Fallout 4 meshes.  When the LOD size is not set the mesh distorts in game.  Unfortunately that's all I can say about it, I'm basically just hitting my keyboard until things work :)

Anyway, it's an easy fix in NifSkope, just thought you might want to know about it.

**Comment by ousnius** [comment]
Indeed, I didn't expect anyone to use it on a BSMeshLODTriShape.

I don't fully know what the engine does with the LOD sizes, though. It seems like the three sizes together have to add up to the number of triangles. There are a lot of NIFs in the game that make use of two or all three of the sizes.

The logic behind it is probably something along the lines of "first you see 1000 triangles, then you get closer and see 500 more triangles, then you're right beneath and can see the remaining 750 triangles".
 LOD0 Size = 1000
LOD1 Size = 500
LOD2 Size = 750
Num Triangles = 2250

So for now all I can do is simply always set the LOD2 Size to contain all triangles after deleting some vertices. This way, the LOD information might be lost, but at least it will work in-game.

**Comment by deadite81** [comment]
Thanks!
