### ISSUE TITLE
Making a new conversion reference fails

### ISSUE THREAD

**Issue by Renha** [ousnius/BodySlide-and-Outfit-Studio#156]
Hello. I'm trying to follow instructions at 
https://github.com/ousnius/BodySlide-and-Outfit-Studio/wiki/Making-a-new-conversion-reference

and it fails, even when I import same exported obj (without any modification), say, CBBE - on the step 8 of "The accurate way" I got this (see attached image)
![outfit-studio-01](https://user-images.githubusercontent.com/3139759/31406693-f83a13b8-ae0a-11e7-88d6-795eaf523d5e.png)

**Comment by ousnius** [comment]
With "no modifications", you mean importing into 3D software and exporting it again?

In that case, whatever software you are using is modifying the mesh in some way. This isn't allowed when working with slider morphs, the OBJ has to come out exactly the same way that it came in.

I don't know about other software, but Blender has OBJ import options for "Keep vertex count/order" etc.

**Comment by Renha** [comment]
Thank you for answer! No, I'm importing same file I've extracted from Outfit Studio :(
Maybe I've done something wrong? What could be wrong? Wrong button while extracting, or something...

**Comment by ousnius** [comment]
Tried it out and it happens for me as well.

The weird thing is that it doesn't happen with the SK or FO4 CBBE, it only happens with the SSE CBBE.
The exported vertex count in the OBJ is the same as that of the CBBE body in the NIF file.

**Comment by Renha** [comment]
it doesn't seem to happen with fbx export/import... (altrough fbx isn't that useful in blender)

**Comment by ichiritter** [comment]
I have the exact same issue, exporting the CBBE Body as .obj and without making changes trying to import the slider from obj, but I get a crumbled mesh, although I see this should've been fixed with d05ab36 ?

**Comment by ousnius** [comment]
It was fixed with that commit, yes. Do you have the latest version of Outfit Studio?

**Comment by ichiritter** [comment]
Only happens if I export them from Blender... could I bother you with the exact export / import settings for Blender?

Edit2: Nevermind it got nothing to do with Blender, only happens when I export with some sliders not set to zero, this is probably expected behaviour though am I right?

**Comment by ousnius** [comment]
You have to import and export with "Keep Vertex Order/Count" with Blender.

**Comment by ichiritter** [comment]
Thanks!
