### ISSUE TITLE
xml bug

### ISSUE THREAD

**Issue by Akujin** [ousnius/BodySlide-and-Outfit-Studio#167]
whenever i try to load a reference into outfit studio from an xml bodyslide preset i get this error. am using latest 4.4.1, have tried running thru Mod Organizer 2.1.1 and without
![outfiterror](https://user-images.githubusercontent.com/35421224/34915326-8d354f38-f978-11e7-8810-69bcd69ba968.png)

**Comment by ousnius** [comment]
This is not a bug, you can't load a **preset** as a **reference** or project.

You need to load a body reference first, then you can load a preset using the "Slider -> Load Preset" menu item.

However, there's usually not a need to even load a preset into Outfit Studio in general. If you're trying to do a conversion, check out the guides on the wiki.
