### ISSUE TITLE
Coupled Toggle Sliders should to be toggled when loading preset

### ISSUE THREAD

**Issue by ToxicKin** [ousnius/BodySlide-and-Outfit-Studio#168]
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/09ef9b4a174a749a0715b3ede17fbd9c6e73a020/src/components/SliderManager.cpp#L243
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/09ef9b4a174a749a0715b3ede17fbd9c6e73a020/src/components/SliderManager.cpp#L251

The above lines (both in function SliderManager::InitializeSliders()) should insert a swap of the current value of all sliders in slidersBig[i].zapToggles if slidersBig[i].changed == true. Same code should apply to slidersSmall aswell. 

Unoptimal example: 
```
if(slidersBig[i].changed) {
	for (auto &toggleSlider : slidersBig[i].zapToggles) {
		// Somehow toggle the value here, though as it stands currently, it'll likely be overwritten later.
		for (auto& slider : slidersBig) {
			if (slider.name == toggleSlider) {
				slider.value = 1.0f - slider.value;
				// Really unsure about this:
				slider.changed = true;
				break;
			}
		}
	}
}
```
The above solution have major issues with precedence however, i.e it more or less requires the toggled slider to show up after the toggler, else if it's part of the preset it'll change to the value the user quite obviously doesn't want - as they saved it as part of the preset. I'd say this probably would do itself best in some sort of post process of the slider init - perhaps simply in the end of SliderManager::InitializeSliders()?

**Comment by ousnius** [comment]
I played around with presets, zaps and zap toggles but can't actually figure out what it is that's not working for you or that you want implemented.

When a preset has been saved with changed zaps, it will save those zap values (on/off) into the preset XML file. When you load that preset, it will set the zaps to the value in the preset file.

The toggling of the coupled zaps happens in the UI before you save your preset. Keep in mind that it's, in theory, possible to have a zap toggle another zap, but then also be able to manually click that zap off again, if it wasn't hidden by the creator of the project. So what's in the actual preset file is what has to appear when you select it.

**Comment by ToxicKin** [comment]
Try using this preset:
```
    <Preset name="Toggle Slider Demo" set="CBBE Body">
        <Group name="CBBE"/>
        <SetSlider name="Remove Sleeves" size="big" value="100"/>
        <SetSlider name="Remove Sleeves" size="small" value="100"/>
    </Preset>
```
And load `CBBE Vanilla - Body - Ancient Nord`:
![image](https://user-images.githubusercontent.com/35739214/35296234-ba1eaac6-007b-11e8-839e-05904f4fe152.png)

**Comment by ousnius** [comment]
Ah, the problem here is that the preset with "Remove Sleeves" wasn't created on the Ancient Nord itself, but maybe on a different outfit or manually.

If you load up a fresh BodySlide that doesn't have the Toggle Slider Demo preset selected yet, then check the "Remove Sleeves" and save a NEW preset, it will also have the hidden toggled zap in it as well and load that just fine.

So a possible fix would be to only invert the value of the coupled sliders, when the coupled slider doesn't also appear in the preset itself with a fixed value.

**Comment by ToxicKin** [comment]
Agreed, was thinking something along those lines, but couldn't express it properly. It probably isn't much of an issue for your standard user, it's mostly folks like me who prefer to edit the XML directly when changing setups for batches, rather than go through each outfit and select your zaps independently. 

...I just realized, when using Save, and not Save As for presets, it keep your previous settings intact. This is really a non-issue for 99% of users.

**Comment by ousnius** [comment]
I've decided to not do toggling from presets for the moment, as it was intended to be a UI-side event only and doesn't cause any issues unless manually editing data.
