### ISSUE TITLE
HotKeys

### ISSUE THREAD

**Issue by firefightert77** [ousnius/BodySlide-and-Outfit-Studio#169]
Would it be possible to add the ability to set your own hotkeys in outfit studio? It would help my work flow tremendously to be able to assign/re-assign hotkeys to the functions I am using at the time.

**Comment by ousnius** [comment]
Totally reasonable suggestion, but it would be quite a big undertaking, so I'm not sure if I want to do something like that yet.

What hotkeys would you rebind specifically? Right now you can edit the .xrc files in a text editor and change those of all menu items in the menu bar.

**Comment by firefightert77** [comment]
I completely understand. Wasn't sure how involved a process it would be. I don't have any specific keys to rebind, as it changes depending on what I'm working on. I honestly didn't know about the .xrc. I will give that a shot. I'm sure I can make that work.
Thanks for your time. 
And Well Done with the quick response. I didn't expect that. It is much appreciated.
