### ISSUE TITLE
Texture Refreshing

### ISSUE THREAD

**Issue by kkthebeast** [ousnius/BodySlide-and-Outfit-Studio#170]
Could we have a refresh textures button or auto polling of time stamp of textures with auto refresh for OS sir? some of our texture guys are using OS with obj files and linking the bgsm,  to test exports.
but changes when using bgsm/bgems to those textures are not updating in real time like they do in NS

**Comment by ousnius** [comment]
Clicking the OK button in the properties dialog of a shape now reloads all shader values, materials and texture files. No file watching yet, maybe in the future.
