### ISSUE TITLE
Suggestion: 'Toggle Zaps' in Slider Properties should be 'Toggle Sliders', and the set should include both zaps and hidden sliders

### ISSUE THREAD

**Issue by ToxicKin** [ousnius/BodySlide-and-Outfit-Studio#175]
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/0fe186b50ea9f533b452768cf8fabffb3c141406/src/program/OutfitStudio.cpp#L5374

Currently, if you want to morph the shape when zapping something, you need to manually add the morph-slider to the zap-slider's zapToggles-property in the osp-file. As the code currently fully supports standard sliders to be modified by the zap-toggle (see `BodySlideFrame::OnZapCheckChanged` in `BodySlideApp.cpp`), I recommend you allow standard sliders into the set. However, it would be a UI issue if all sliders were present, and therefore I suggest it only contains hidden sliders, like this: `if (i != curSlider && (project->SliderZap(i) || project->SliderHidden(i)))`

Myself, I like to use some morphing of the outfit shape when setting zaps, to, for example, make the outfit shape better fit the base shape:

```
<Slider name="Skirt Zap" invert="false" small="0" big="0" zap="true" zaptoggles="Skirt Zap - Body;Skirt Zap - DressFit;">
    <Data name="Farm02_0Skirt Zap" target="Farm02_0" local="true">Farmer Dress 2.osd\Farm02_0Skirt Zap</Data>
</Slider>
<Slider name="Skirt Zap - Body" invert="false" small="100" big="100" hidden="true" zap="true">
    <Data name="BaseShapeHRSkirt Zap - Body" target="BaseShapeHR" local="true">Farmer Dress 2.osd\BaseShapeHRSkirt Zap - Body</Data>
</Slider>
<Slider name="Skirt Zap - DressFit" invert="false" small="0" big="0" hidden="true">
    <Data name="Farm02_0Skirt Zap - DressFit" target="Farm02_0" local="true">Farmer Dress 2.osd\Farm02_0Skirt Zap - DressFit</Data>
</Slider>
```

Either way, it's a small QOL change - and some people might not be aware it's possible to use the zaptoggles this way - which allows for better quality outfits.

**Comment by ousnius** [comment]
Thanks for the suggestion.
