### ISSUE TITLE
Building preset breaks ingame blood hit effect

### ISSUE THREAD

**Issue by Fallout4Why** [ousnius/BodySlide-and-Outfit-Studio#177]
when you build with a new cbbe preset, it breaks the blood textures when you're hit and you're naked.

**Comment by Fallout4Why** [comment]
I figured it out, the new CBBE update v2.6 isn't compatible and causes the issues. Version 2.5.2 of CBBE works properly. v2.6 Changed the body to be saved as a full precision mesh. This could be causing the issues.

**Comment by ousnius** [comment]
Please don't post CBBE or mod issues on the BodySlide GitHub.

**Comment by Fallout4Why** [comment]
Where should I make a bug report?
