### ISSUE TITLE
Support for filepaths with diacritical signs

### ISSUE THREAD

**Issue by MrJamesFreeze** [ousnius/BodySlide-and-Outfit-Studio#178]
This bug is definetely in v4.5.3 Outfit Studio

It is not happening when opening file which filepath has diacritics but for example when I am exporting mesh which has cloth physics (and have filepath with diacritics) and I choose to use cloth physics from original file program terminates.

Picture with problem:
![pic](https://user-images.githubusercontent.com/17742925/38784969-ee1acbf0-4119-11e8-8b57-95da7bea3146.jpg)

**Comment by ousnius** [comment]
Thanks, UTF-8 conversion was missing in that spot.
