### ISSUE TITLE
Mirror along axis

### ISSUE THREAD

**Issue by Darklocq** [ousnius/BodySlide-and-Outfit-Studio#196]
From the Nexus forum page, Ousnius wrote (in 2017): "There's no mirror function in Outfit Studio right now because it could mess up a few things on working meshes, such as having to copy the bone weights again. You can either try an OBJ export/import and do it in Blender or create a new issue entry on the GitHub page so I don't forget about it in the future. "

Well, the ability to do that is, to an image editor like me, pretty much a must-have.  It's astounding to me that this ability isn't in Outfit Studio, or NIFskope, given the frequency (about 95%) with which armors and clothing have identical but mirrored parts on the left and right.  For various jewelry designs and such, it might make sense to also be able to mirror on the other two axes.

Almost all of my "trying to 3D mod" wannbe projects have run aground because I can't just copy an object like a sleeve or a pauldron and flip it around.  I gather I could do this with Blender, somehow, but that's a tool I've not figured out yet (it seems about 10x more complicated than Outfit Studio and NIFSkope combined).

**Comment by ousnius** [comment]
This was implemented a week ago in 55740fa.
You can duplicate a shape, mirror the duplicated shape, then re-copy bone weights from the reference.

**Comment by Darklocq** [comment]
Oh, wow!  I didn't expect any action on this so soon.  Thanks.  I'm going to have to try this out.

**Comment by Darklocq** [comment]
Some belated feedback: It's spectacular!
