### ISSUE TITLE
Exporting Clothes meshes removes physics information

### ISSUE THREAD

**Issue by Poofey** [ousnius/BodySlide-and-Outfit-Studio#198]
I am probably doing something wrong but...

I am using JaneBod Extended to add physics to breasts and butt and I am in the process of converting the 200+ outfits i have. I used [this video ](https://www.youtube.com/watch?v=oVKcZgaL-To&t=2s) to copy the  body physics bone weights to the clothes and worked for the most part. I noticed that robes/dresses would lose their physics when doing this and turn into a static piece of clothing. I also noticed that those pieces of clothing had their own bones and weights and when copying the body's it would delete them. 

I also noticed that even if i don't touch anything except loading the outfit and exporting it, the size of the file will go down by 50kb or so and lose its physics ingame, even if the bones remain. When exporting i get a dialog telling me that it has physics data loaded and to choose an origin, if i tick the checkbox, it will instead add 50 or so kb to the file but also lose its physics. 

I will attach as an example the bathrobe that has been built by bodyslide to fit my body, the body im using as well as the non-modified export outputs with and without the physics data checked. 

[Bathrobe.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/2512585/Bathrobe.zip)

**Comment by ousnius** [comment]
Fallout 4 can only use one physics "block" (BSClothExtraData in the NIF file) at the same time. You have to choose between dress physics or body physics.

In any case this is no issue with Outfit Studio.
