### ISSUE TITLE
mishandled bones

### ISSUE THREAD

**Issue by rdm** [ousnius/BodySlide-and-Outfit-Studio#20]
Building from source gives me different behavior in outfit studio from what I see in the copy downloaded from nexus.

When I open Skyrim\Data\meshes\clothes\prisoner\prisonerclothes_f_1.nif from outfit studio built from source, I get 20 message boxes from this code:

``` c++
bool AnimInfo::LoadFromNif(NifFile* nif, const string& shape) {
	vector<string> bonenames;
	vector<int> boneIndices;
	//vector<int> boneids;
	//vector<AnimBone> tmpbonelist;
	if (!nif->GetShapeBoneList(shape, bonenames))
		return false;

	int slot = 0;
	for (auto bn: bonenames) {		
		if (!AnimSkeleton::getInstance().RefBone(bn)) {
			AnimBone& cstm = AnimSkeleton::getInstance().AddBone(bn, true);
			if (!cstm.isValidBone) {
				wxMessageBox("Referenced bone not found in skeleton, skipping: " + bn, "Invalid Bone");
				continue;
			}
...
```

There might be two problems here. One in the behavior of the code, the other in the phrasing of the messsage box message.

The .AddBone() method is the source of the invalid cstm values. But .AddBone() is just searching an empty tree for them. Perhaps supposed to be adding an empty AnimBone of that name which will then have content plugged in. If this were the case, though, that message box message would be misleading.

The bones are present in the nif argument to this method, and this looks like the code which is trying to fill in the animskeleton values.

(Alternatively, maybe an earlier bit of processing was supposed to fill that tree with bone nodes. But if that were the case, I don't know what this code is for.)

**Comment by ousnius** [comment]
Did you install a reference skeleton and link it in the Config.xml? See the Nexus archive for what other fikes are in there.

**Comment by rdm** [comment]
Hmm...  this might very well be my not knowing how to use things properly.

That said, I have since copied config.xml and all subdirectories from D:\games\Steam\steamapps\common\Skyrim\ModOrganizer\mods\BodySlide\CalienteTools\BodySlide\ into my visual studio debug directory, and I started a new project in outfit studio and selected SliderSets\CalienteBody.xml before proceeding on to load D:\Games\Steam\steamapps\common\Skyrim\Data\meshes\clothes\prisoner\prisonerclothes_f_1.nif as the outfit.

This produces the same behavior.

So presumably what I need are earlier diagnostic messages, to help me isolate my failure?

**Comment by ousnius** [comment]
The message simply means that the NIF you're trying to load has bones that are not in the reference skeleton (which is linked to in Config.xml and stored in the res folder). Is the prisonerclothes_f_1.nif a vanilla file you're trying to load?

**Comment by rdm** [comment]
Yes.

So my failure was understanding the concept of "linked to in config.xml" - I had four .nif files in the res folder, and none matched config.xml (res\skeleton_female.nif).

As an aside... Looking back at the version I downloaded from nexus - it's in the same state (the config file refers to a non-existent res folder .nif file). Meanwhile, of course, the default provided in the config.xml in the source contains a matching skeleton, and the default provided by BodySlideApp.cpp does does not match. Also, the outfit studio I downloaded from nexus doesn't give the message box popups, which strikes me as odd, but might be because of elevated privileges and "security" or something.

If the nexus version has the popups but I'm not seeing them (I do see something that might be a message box for a fraction of a second) then that is troubling. 

So... for remedies...  I propose that all of these bone messages to be grouped together and accompanied by a diagnostic message mentioning by name the full path to config.xml as well as the full path to defSkelFile from OutfitProject.cpp. Perhaps also a "please read Guide 4: Tweak BodySlide/Outfit Studio" or something like that?

But I do not know what to do about the hostile UI environment.

**Comment by ousnius** [comment]
The file from the Nexus does include a correct Config.xml and the matching skeleton, I just checked the archive again. That's also the reason why it works or you (skeleton_female_xpmse.nif in config and res).

The default skeleton path in the BodySlideApp.cpp does ALSO point to one that's existing in the Nexus archive.

`Config.SetValue("Anim/DefaultSkeletonReference", "res\\skeleton_female.nif");`
You probably didn't see or copy the res folder from the Nexus archive or something else went wrong.

I agree about merging the separate dialog windows into one.

**Comment by rdm** [comment]
Huh... you are right about that config file.

I could have sworn that I copied my Config.xml from the nexus BodySlide directory. But now it looks like I did not.

Thanks.
