### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Shaderconst** [ousnius/BodySlide-and-Outfit-Studio#202]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(FSBSA.obj 中)	BodySlide	E:\project\OutfitStudio\BodySlide-and-Outfit-Studio\wxbase31ud.lib(appbase.obj)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "public: __thiscall std::exception::exception(char const * const &)" (??0exception@std@@QAE@ABQBD@Z)	BodySlide	E:\project\OutfitStudio\BodySlide-and-Outfit-Studio\wxmsw31ud_core.lib(choicbkg.obj)	1	

Is there a contact?

**Comment by ousnius** [comment]
It works fine for me using VS2017 and the latest builds of wxWidgets.
Your error seems to be related to linking wxWidgets, make sure to read https://github.com/ousnius/BodySlide-and-Outfit-Studio/wiki/Compilation

**Comment by Shaderconst** [comment]
I Have been compiled success, thank you very much。
another problem, I want to export an earlier version of the “Nif” file used in GameBryo 2.3.Is there such a historical version?thanks。。
