### ISSUE TITLE
Scale and Move Tools Mark all Vertices as Modified

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#204]
If you go to edit a slider and mask out the set of vertices you want to apply, using the Move or Scale tools from the Shape menu marks all vertices as modified, even though it doesn't perform any actions on the masked vertices.

This results in a lot of unnecessary bloat in the sliders file. It also makes it difficult to fine-tune sliders since there is slider data present on vertices that there shouldn't.

To demonstrate:

1. Open any project in Outfit Studio.
2. Click the Edit button next to a slider that affects only a portion of a shape.
3. Select Slider > Mask Affected Vertices to show what vertices are currently modified by the slider and verify it is not currently affecting the entire shape.
4. Clear mask. Invert mask. Remove mask on any number of vertices in the shape. 1 is sufficient to demonstrate.
5. Apply a Move or Scale transform to the unmasked vertex(ices) from the Shape menu. You can visually see the transform is only altering the unmasked vertex(ices).
6. Clear mask and again select Slider> Mask Affected Vertices
7. You'll see the entire shape is now masked regardless of how many, or where, the vertex(ices) were that you applied the transform to.

The Brushes do not exhibit this. Only the transforms from the Shape menu.

**Comment by ousnius** [comment]
Fixed, thanks.
