### ISSUE TITLE
In BodySlide, sometimes clicking "Opens the current project in Outfit Studio" button does not open the project 

### ISSUE THREAD

**Issue by ogrotten** [ousnius/BodySlide-and-Outfit-Studio#207]
Using Mod Organizer 2.

OS opens just fine, but the project doesn't preload. ~~It seems to only be UNP meshes.~~

On further review, it doesn't appear to only be UNP based meshes.

**Comment by ousnius** [comment]
The feature is working for me, it might be related to MO2 (sometimes?) being unable to hook the launched Outfit Studio process in time. The button launches a new Outfit Studio process, since they're separate executables now.

**Comment by ogrotten** [comment]
Is that button sending a command-line parameter to Outfit Studio? If so, what's the format? I'd be ok with using that directly as a work around.

**Comment by ousnius** [comment]
If you just want to load the project, you can also simply use "File -> Load Project" directly in Outfit Studio and choose the .osp file.

The command-line would be `OutfitStudio -proj "project_file.osp" "project_name"`

**Comment by ogrotten** [comment]
Jeez . . . I misunderstood the purpose of the button.

So I was under the impression that the button was 

> Make a new project from this Preset and open the project in Outfit Studio

But it's not that. . . 

It is _literally and only_ a shortcut for opening Outfit Studio and browse-surfing for `project_file.osp`. In other words, it's been working as intended all along.

I will, however, say that what I thought it was would be a nice shortcut feature. I realize that the theme of BS/OS is to make very few assumptions, but to assume the most basic settings to do such a thing would remove quite a bit of repetition.

Thanks for responding.

**Comment by jobobby04** [comment]
Pretty sure this is caused by trying to open a project thats located in a .xml file, the old bodyslide sliderset format.
