### ISSUE TITLE
Idiot Not Savant

### ISSUE THREAD

**Issue by innoccu35** [ousnius/BodySlide-and-Outfit-Studio#208]
First off I'm not a "code" person - I do enjoy a good mod though.  Body Slide is a great mod if it works ffor me with a min.. of fuss - but in Fallout 4 I have had nothing but issues - namely in getting a male bodyshape to work. NOTHING I have tried from deleting, re-downloading, manuel install, to mod manager download/install , to file exchanges and mapping filters (or something like that). Look - Im confused = is there a simple easy step by step way to get it to work - or should I just delete the mod and deal with ugly toons. 

Mike

**Comment by ousnius** [comment]
Please go to the Nexus page for support.
