### ISSUE TITLE
OutfitStudio and commandline batch builds

### ISSUE THREAD

**Issue by Envious-Data** [ousnius/BodySlide-and-Outfit-Studio#209]
Hello, This is more of a suggestion/feature request

Ive recently come across a mod ported to SSE and would like to convert it to the Skyrim SSE CBBE body rather than the LE CBBE, From what I can tell Outfit studio does not have a batch convert process nor a --help in CLI

**so my suggestion then:**
- CLI command --help to list all options w/ a example
- option to select a list of outfit groups or outfits and what to do
-- E.G convert LE to SE CBBE THEN what body for the end output, cbbe, cbbe physics, unp
- perhaps a gui version of ^^ this stuff for those who want it ?

I presume the benefit of this feature would be a lot more bigger clothing packs might get converted from LE to SSE and or from vanilla to SSE for example It also would take the tediousness out of converting about 150-400 outfits

Anyhoos, I hope you consider this suggestion
~ Adam

**Comment by 3000percentmanlyjaw** [comment]
This has been requested multiple times, but due to the way things work in OS, like requiring a viewport to create an outfit, it's not possible to have this implemented.

**Comment by Envious-Data** [comment]
> like requiring a viewport to create an outfit, it's not possible to have this implemented.

my next question would be, would a solution built into the GUI be possible then?

**Comment by ousnius** [comment]
Would be a lot of work, both refactoring and new, to get this done. Even then, you wouldn't get remotely pretty results without manual touchup, so I didn't see a real need to automate it like that yet.

**Comment by Envious-Data** [comment]
Tyvm for your response, I do hope to see some automation in the future even if still a bit semi-auto It should still be faster than individual convertsions

~ Adam
