### ISSUE TITLE
[Nif library] Crashing in NiString::Get

### ISSUE THREAD

**Issue by Guekka** [ousnius/BodySlide-and-Outfit-Studio#211]
When loading a nif file using `NifFile::Load`, the program calling it may crash. 
Looking at the stack trace, it appears that the crash happens in the [NiString::Get](https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/8105f92a5cc5130949b5fa0f9385da64a6d7a01f/lib/NIF/BasicTypes.cpp#L52) function. 

        void NiString::Get(NiStream& stream, const int szSize) {
        char buf[1025];
        /*Some code */

	else if (szSize == 4) {
		uint bigSize;
		stream >> bigSize;
		if (bigSize < 1025)
			stream.read(buf, bigSize);
		buf[bigSize] = 0; /* Crash here */

	}

	str = buf;
        }

The crash happens when bigSize is bigger than 1025, since the buffer is only 1025 bytes.

**How to reproduce**
I've created a sample project, and attached it as well as some meshes.
[NifLibCrashingSample.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3277351/NifLibCrashingSample.zip)

**Comment by ousnius** [comment]
This should be good enough for now, thanks.

**Comment by Guekka** [comment]
I've just tried your fix. It is nearly working. 
You forgot to add a ``-1`` [on line 78](https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/dev/lib/NIF/BasicTypes.cpp#L78): replacing this line with ``bigSize = bufSize - 1;`` worked.
