### ISSUE TITLE
[FO4] Head morphs all get deleted in CK after export

### ISSUE THREAD

**Issue by jobobby04** [ousnius/BodySlide-and-Outfit-Studio#212]
After adding new morphs to the female head I went to add them into the game with CK, after opening the human female morphs menu in CK a bunch of these menus came up for each section.

![77zQvwW 1](https://user-images.githubusercontent.com/17078382/59958728-14a7b680-9479-11e9-9c60-d2e16fa12986.png)

Pressing yes cleared them all, leaving nothing, I went to the add morphs menu and the only things that were there were 2 sliders that I think came from a different source.

![PHIfzgT 1](https://user-images.githubusercontent.com/17078382/59958746-53d60780-9479-11e9-96dd-17692e71ed85.png)
I have also been able to replicate this behavior by using a vanilla head tri files.

**Comment by ousnius** [comment]
Can you post the before and after .tri files?

**Comment by jobobby04** [comment]
Before:
[BaseFemaleHeadChargen.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3316838/BaseFemaleHeadChargen.zip)

After
[BaseFemaleHeadChargen.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3316839/BaseFemaleHeadChargen.zip)

**Comment by ousnius** [comment]
Might be fixed in the next version.

**Comment by jobobby04** [comment]
Its fixed! I'm not having any issues with CK now.
