### ISSUE TITLE
Pathing issues

### ISSUE THREAD

**Issue by Wei-ss** [ousnius/BodySlide-and-Outfit-Studio#214]
I'm trying to load Bodyslide through MO2, but I'm suffering from many pathing issues. I fixed one by manually setting the path for the skeleton meshes, but I'm unable to set any more. Especially for shader files, which I'm also getting errors loading.

The files/paths I'm currently having pathing issues with include:

- `res\skeletonfo4.nif`

- `res\shaders\fo4_default.vert`

I noticed that the NexusMods description mentions having broken registry keys. I've loaded the game up, but I'm still getting the errors. Would you mind letting me know which registry keys BS reads to find the game's install path, so I can edit them myself?

Thanks.

**Comment by ousnius** [comment]
The registry key of the launcher that points to the game install has nothing to do with BodySlide finding the files you listed or not. BodySlide and Outfit Studio load all files relative to the working directory they're launched in.

1.) Reinstall BodySlide into MO to get a clean setup
2.) Follow the MO installation instructions on the mod page, it's important you launch BodySlide through MO with the right working directory.

That's all that has to be done (installing and running through MO). If something isn't working then it's a bug in MO2, but it's confirmed to be working with BodySlide or there would be way more issues.

**Comment by Wei-ss** [comment]
I followed the guide you mentioned initially, but I had a problem not being able to launch `setup.xrc`, so I installed it manually, then added the executable to MO2 that way, which is where I'm at now.
