### ISSUE TITLE
Import Custom Normals From OBJ and FBX files.

### ISSUE THREAD

**Issue by SQr17** [ousnius/BodySlide-and-Outfit-Studio#218]
**What is it that you want to do that isn't currently possible?**
Reliably importing meshes with modified/customized normals into Outfit Studio isn't possible. Neither is it possible to update existing NIF files with modified normals. 

While it is possible to import OBJs with customized normals (by going through many additional steps, unreliable), it will almost always break the mesh's vertex order, resulting in incompatibility with any dependent TRI morphs (head meshes). Topology-based weight transfers also become impossible after this.

**Request the feature**
Please include a feature that allows modified/customized normals (and possibly bitangents, tangents) to be imported into existing NIF files, same way as you would import updated texture coordinates or vertex positions in Outfit Studio (by using compatible OBJ and FBX files).

**Comment by 3000percentmanlyjaw** [comment]
Attach some files you've had issues with so it can be investigarino-pepperino'd.

**Comment by SQr17** [comment]
[Modified Normals.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3672897/Modified.Normals.zip)

Here's Fallout 4's default female head mesh with customized/copied normals to match CBBE. Importing the OBJ into the Outfit Studio will discard the modded normals and also mess up the vertex order.

**Comment by 3000percentmanlyjaw** [comment]
This isn't an issue of Outfit Studiorino. Vertex Order gets shuffled on flipping normals - this is expected behavior. You need to use a brogram like Maya, 3ds Max et al that allows you to change or adjust the order to keep them identical to the original after you have edited them.

**Comment by SQr17** [comment]
The OBJ vertex order issue is not my primary concern, but it most certainly is something that Outfit Studio does (You can confirm this by exporting an OBJs from the head mesh NIF in OS and then importing the OBJ back into OS, the vertex order will be different from the original NIF file).  
And also, this does not happen at all when using FBX export/import. 

However, my main request is allowing custom normal imports onto existing NIF files using FBX/OBJ files.

Anyway, I have already discussed this at length with ousnius and he was the one who asked me to create a feature request here as a reminder for him to look into it.

**Comment by tokitoki22** [comment]
Ah I could see same problem,, even though I export obj from OS, then just use same obj to up-date mesh in out-fit stuido,, it break my mesh. (not use any other aprication)

**Comment by sts1skj** [comment]
Could someone please test to see if PR #444 fixes this issue?

**Comment by sts1skj** [comment]
<s>I saw something puzzling in the FBX import and export code: the vertex coordinates had x,y,z swapped around, but the normals didn't.  This might mean that FBX import and export of normals messes up the normals in a reversible way.  Could someone please check?  If it is messed up, it should be easy to fix.</s>
