### ISSUE TITLE
Import as obj and Update current shape seems break mesh

### ISSUE THREAD

**Issue by tokitoki22** [ousnius/BodySlide-and-Outfit-Studio#219]
**Description**
When I import obj in out fit studio, with select mesh(eg CBBE body),  it seems break mesh arrange as if it was mirror or scaled. 

**How to reproduce**
1. export mesh from out-fit studio.  import it to blender 2.7  and  edit , export obj  as test.obj from blender

2. In out fit studio, select the mesh , then import obj

3 . out fit studio will, show dialogue "only up-date vertex position yes or no" when vertex count is same.

4. click yes to only up-date vertex position.  about UV "no"

5. it break mesh as if I use wrong x mirroer or break.

6, if I use same obj.file,, and edit slider data,, it work as expected.

=======================
I test with blender 2.7,  and use same obj file to up-date slider data.  Only when I try to up-date shape,, the problem happen.  though I can make slider, and up-date shape,  
basically, I can use same obj file, to up-date slider data and to up-date vertex postion.

So hope if it can work as same as up-date slider data (import as obj)
or I may need to use different export option from blender when I export as obj.  
the attach file is CBBE (skyrim SE)  defaut body mesh which I editted. so test please . you may see it work to edit slider data, without break mesh.. but not work to up-date geometry only.

[export-fb27.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3674133/export-fb27.zip)

these are pic, 
1 when I import as slider data.
![sliderdataimport](https://user-images.githubusercontent.com/38904085/65930183-d0e12780-e43f-11e9-937e-cdb7cd0f688c.JPG)

2 when I import with select CBBE body, then tried to up-date geometry only
![updategeometry](https://user-images.githubusercontent.com/38904085/65930240-1271d280-e440-11e9-82e1-6b337231660e.JPG)

**Comment by tokitoki22** [comment]
It is not related blender exporter . because even though I just select CBBE mesh in OS (v4.8.0), then
r-click option,  export as obj,  and re-import the obj,, it show same broken mesh. then it is not matter, about blender, maya, etc.  

And it did not happen about cloth meshes which I test.  (though I can only check, it seems not change as looking but do not know, if it change vertex order)

**Comment by Bug64** [comment]
This may be related.  Using version 4.8.0 of OutfitStudio, if I:

1. open TBOS-BodyTalk-NeverNudeV2.osp (from https://www.nexusmods.com/fallout4/mods/34208)
2. export the body as OBJ
3. immediately import the OBJ (no edits)
4. reply Yes to the merge prompt and Yes to update vertex positions

The mesh ends up "scrambled" similar to the image above.  Comparing the OBJ files with the vertex data in NifSkope, the vertices don't appear to be in the same order.  If I import the OBJ as a new outfit, export it and re-import it, the problem doesn't occur.  

As a further test, I tried exporting and re-importing the Super Hero Body and there were no issues (so apparently it's verts are already in the "right" order).

As a workaround, I:
1. Imported the OBJ as a new shape into the base body's project
2. Copied bone weights (with radius/target of 0/1)
3. Conformed the shape to the original body (0/1)
4. Copied the shape properties from the old body to the new

**Comment by ousnius** [comment]
Importing an OBJ as a shape follows the order of the vertices as they appear in the triangles in the OBJ file. If this order doesn't match up with what's already loaded in Outfit Studio, then you will get a scrambled up mesh.

When you import an OBJ as slider data instead, only the vertex array is loaded without caring about any triangles, so the original vertex order may get loaded and stays intact here.

To work around this, I may need to add a separate way to update data from OBJ files instead of the regular OBJ import.

**Comment by tokitoki22** [comment]
> Importing an OBJ as a shape follows the order of the vertices as they appear in the triangles in the OBJ file. If this order doesn't match up with what's already loaded in Outfit Studio, then you will get a scrambled up mesh.

**Comment by tokitoki22** [comment]
So I do not know, how OS importer work to generate mesh from obj file. but basically
most of 3d aprication, obj importer, and obj exporter keep vertex order. without change it.

Though I know, recent version nif-scopes have same problem about obj importer.
(If I check exported obj file, it keep vertex order, as same as nif-scope, but when import the same obj file, nif-scope corrupt vertex order. )

**Comment by 3000percentmanlyjaw** [comment]
This is definitely not an OS issue, whatever program you use on exporting the obj is changing the vertex order. Auto clamp, welding or VOJ can cause this.

**Comment by tokitoki22** [comment]
> This is definitely not an OS issue, whatever program you use on exporting the obj is changing the vertex order. Auto clamp, welding or VOJ can cause this.

You seems not read what I discribed.

I test without use other 3d aprication, just export nif as obj as test.obj from OS
then import the obj file. then it corrupt vertex order.

but it work if I export and import obj as slider data.

Then most of case, I use obj to make morph, (when import and epxort between 3d apps,
eg iclone or daz or blender or Maya etc etc,, ) then I know, how it work.

And if the apricaiton export obj, and re-import same file,  change vertex order,
many user offer bug-report, then will be up-dated. 
 but I know skyrim tool may not consider it important.
