### ISSUE TITLE
Failed to launch Outfit Studio executable!

### ISSUE THREAD

**Issue by dkspwndj** [ousnius/BodySlide-and-Outfit-Studio#223]
**Description**
Launch BodySlide 4.8.0 well and click in outfit studio at BS. That error popup and return to BS.

MO log seen than write in this message.
DEBUG (13:33:02.0499): create process (w) null - "D:\SteamLibrary\steamapps\common\Skyrim\data\CalienteTools\BodySlide\OutfitStudio.exe"  (in null) - hooking
DEBUG (13:33:02.0499): process failed to start (2)
This is end. Only fail at MO launch. Launch at explorer window than well working.

4.7.4 version OutfitStudio work well at MO launching.
[ModOrganizer_19_11_30_04_35.log](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3906739/ModOrganizer_19_11_30_04_35.log)
[ModOrganizer_19_11_30_04_40.log](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3906740/ModOrganizer_19_11_30_04_40.log)

**Comment by ousnius** [comment]
Report it to the MO2 developers instead (if this is about MO2 instead of MO1).
