### ISSUE TITLE
Feature request: bone movement in Outfit Studio

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#226]
**What is it that you want to do that isn't currently possible?**
See the effects of bone weight changes without starting up Skyrim.

**Request the feature**
I suggest adding the ability to adjust bone positions in Outfit Studio.  You could do some complicated fancy visual adjustment mechanism, of course, but I suggest doing something simpler: when a bone is selected, a small window with several sliders could open.  The sliders would adjust the bone position, and the rendered model would update.  I'm not sure what the correct number of sliders would be, as I don't know enough about model skeletons to know what movement constraints they have, but the maximum would be six: (x,y,z) position and (x,y,z) rotation; I suspect the bone movement constraints would typically limit movement to just three sliders, though (the rotation ones).  The user interface should also make it easy to return bones to their default positions.

Use case: I change some bone weights, say, by tweaking the weights for "NPC L Butt".  I know from experience that it's highly likely that the resulting body will move wrong, but I can't know for sure until I load Skyrim and see the character move.  I'd like to be able to see the problems immediately by adjusting the positions of "NPC L Butt", "NPC L Thigh [LThg]", and possibly other bones in Outfit Studio.

Thoughts: As far as I can tell, Outfit Studio is currently the only tool that lets you modify model bone weights at all for Skyrim.  It would be nice if the models could be imported into Blender and exported back to Skyrim, but the tools for doing so don't seem to exist.  Apparently the tools used to exist, but I've been unable to find all of the pieces necessary for the transfer, as all of them were created at least eight years ago, and not all of the archives exist any more.  If there's some other tool, I have not discovered it.

On the other hand, one of the main purposes of Outfit Studio is to adjust bone weights.  Doing so is surprisingly tricky, with awful results being the norm.  It would be nice if those awful results could be seen immediately, inside Outfit Studio, instead of having to use another tool.

**Comment by ousnius** [comment]
This can't be done before something like https://github.com/ousnius/BodySlide-and-Outfit-Studio/issues/10 is implemented. Then of course, I could also load .kf animations and play them back or just let you edit the bones with the transform tool. But the way there isn't easy.

**Comment by sts1skj** [comment]
@ousnius 
Before trying to implement bone posing in Outfit Studio, I would like to do some cleanup of the coordinate-system (CS) transformation code.  I propose doing the following kinds of cleanup:
C1.  Bundle rot, trans, scale, localRot, and localTrans in AnimBone into two MatTransform objects.
C2.  Rename transforms in AnimBone, AnimWeight, NiAvObject, NiSkinData, and BSSkinBoneData so that their names imply the coordinate system transform they give.  For example, I think AnimWeight::xform would be better named xformGlobalCSToBoneCS.  Also add comments.
C3.  Rename get and set functions so that their names imply the coordinate systems.
C4.  Add functions to MatTransform to apply, invert, and compose MatTransforms.
C5.  Move MatTransform::ToEulerDegrees to the Matrix3 class, where it belongs.

I have a bunch of questions:

Q1: May I do this cleanup?

Q2: Is it okay to modify code in lib/NIF?

Q3: What is the skin transform (NiSkinData::skinTransform)?  More specifically, what are its source and target coordinate systems?  When a transform such as NiSkinData::BoneData::boneTransform specifies a transformation from a global CS to the bone's CS, is the global CS independent of the shape or is it a shape-specific CS that is defined by the skin transform?  In every nif file I've inspected, the skin transform is the identity transform, so I haven't been able to answer these questions by inspecting nif files.

Q4: Many functions (such as GLSurface::AddMeshFromNif) assume that some instances of MatTransform::rotation are rotation matrices instead of general 3x3 matrices, but nothing in lib/NIF guarantees that they are rotation matrices.  Many other functions (such as AnimSkeleton::GetSkinTransform) do not make this assumption and treat MatTransform::rotation as a general 3x3 matrix (not taking advantage of rotation-matrix properties such as the fact that its transpose is its inverse).  (Definition of rotation matrix: a 3x3 matrix whose transpose is its inverse and whose determinant is positive.)  Should all Outfit Studio code assume that every MatTransform::rotation is a rotation matrix?  Should no code assume this?  Should Outfit Studio force every MatTransformation::rotation read from a nif file to be a rotation matrix?

Q5: Many functions (such as AnimInfo::WriteToNif) set MatTransform::scale to 1, and scale is never set to anything other than 1, so scale can only not be 1 when read from a nif file, and then only until some Outfit Studio function sets it to 1.  Should this be more strictly enforced by eliminating scale altogether (which would mean using a new data structure to replace MatTransform in AnimBone and AnimWeight)?

Q6: What sorts of shapes have IsSkinned false?  It's always set to true in the nif files I've inspected.  There is code in GLSurface::AddMeshFromNif for handling shapes with IsSkinned false.

Q7: I've found approximately 5 bugs in this code.  Do you want me to list them so you can fix them yourself, or should I fix them?  If I fix them, do you want the bug fix patch to be a separate pull request from the cleanup?

Q8: Do you have any idea why every ordinary outfit nif file has two copies of each bone transform, one in the NiNode for the bone and the other in NiSkinData or BSSkinBoneData?  (The two are inverses of each other for every instance I've investigated.  The NiNode transform is from bone CS to global CS, and the NiSkinData transform is from global CS to bone CS.)

Q9: I've produced a fairly long set of notes from my investigation of CS transformations in Outfit Studio.  Do you want me to send you my notes?

**Comment by ousnius** [comment]
Q1 Q2: You may, but don't rename members in the NIF lib code.

Q3: Unskinned meshes (shapes without skin instances, bones, weights) and skinned meshes are rendered differently by the engines.

Unskinned meshes can be offset using their parent nodes and the transform on the shape block itself. Skinned meshes completely ignore the transform on the shape itself, it's not used for rendering (only for offsetting the bounding spheres). They also ignore the what I call "overall skin transform" in the comments (NiSkinData::skinTransform) for rendering. The NiSkinData::BoneData::boneTransform are used ingame.

There are a lot of legacy/old/dirty meshes out there that make use of one or the other transform (or not) so all cases need to be handled properly. Since Outfit Studio doesn't render the individual bone transforms right now, I had to make it render the NiSkinData::skinTransform instead, even though the engine doesn't (since it's the inverse of all the bone transforms so I can use that data).

Q4: Unfortunately I can't really answer this question. Some of the code is from Caliente, some is partially mine or was edited. There hasn't been much thought behind it, it's just meant to do things to get the right result. NIFs store the transforms as 3x translation, 3x rotation and 1x scale.

Q5: There's basically no relevant nodes in the game's skeletons that have a scale different than 1.0. There's one exception and it's the hand/finger bones in for example Skyrim. To combat that, the reference skeletons that ship with Outfit Studio (res folder) are normalized, so their hand/finger scales are 1.0 with an adjusted translation value.

The hardcoded scales of 1.0 in the functions you're seeing were always there to possibly prevent similar issues before I worked on the code. I don't know if they're still needed, I don't think so. Maybe the code can be cleaned up somehow.

Q6: Well, skinned meshes are skinned and static meshes are not skinned. Any body or outfit you are going to load will be skinned. Anything else like props, buildings, weapons, ground objects of outfits won't be skinned. See Q3.

Q7: Either list them or separate PR.

Q8: NiNodes are present in skinned meshes to make it possible to link to them in the file structure. They're the same nodes present in the skeleton meshes of the game. The bone transforms can differ from shape to shape within the NIF, the nodes are used by all shapes in the NIF.

Usually their hierarchy is flat compared to the skeleton NIF, but there are meshes (for the HDT PE or HDT SMP physics plugins) that have a non-flat structure of NiNodes in NIFs. The HDT plugins inject nodes present in the NIF that are used for the physics into the skeleton in the game dynamically (in the hierarchy they're given).

Q9: Sure yes.

The way OS handles transforms (what gets loaded, what gets saved and what happens when you say add bones) is very sensitive. If you remove the wrong line of code or change the wrong thing, something about a certain type of NIF will break right away (maybe even just in one game).

So you need to be careful about any small changes in logic that results in different transforms in the NIF than before.

Different types of cases:
- Skinned vs. unskinned meshes
- Skyrim vs. FO4 formats and where transforms are stored
- "Normal" skinned meshes with flat node hierarchy
- "Custom" skinned meshes for HDT PE/HDT SMP physics mods with nodes not present in the reference skeleton at all, with or without a hierarchy of nodes in the NIF
- Old "dirty" NIFs with transforms all over the place that negate each other (just one example: exports with a scale of 0.001 in skin transform and 1000.0 in all bone transforms)

**Comment by sts1skj** [comment]
Here are my notes on this.  I didn't write this for anyone but myself, so it may be incomprehensible.  If you want me to clean it up into something more easily understood, let me know.  The bug list is near the end.

[bonetrans.txt](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/4209182/bonetrans.txt)

**Comment by ousnius** [comment]
I fixed two of the obvious ones. Is this what you were referring to with the two?
e735eca

**Comment by sts1skj** [comment]
Your fix in AnimInfo::CalcShapeSkinBounds was exactly what I was referring to with the first bug on my list.  Your changes in NifFile::GetShapeBoneTransform don't seem to correspond to anything on my bug list.

I looked at your changes in NifFile::GetShapeBoneTransform and realized that there are several places in that file with a similar bounds-checking bug.  "boneIndex > skinData->numBones" should probably be "boneIndex >= skinData->numBones", and "boneIndex > boneData->nBones" should probably be "boneIndex >= boneData->nBones".  But it's unclear to me why numBones and nBones exist anyway, since the sizes are implied by the corresponding std::vectors.

**Comment by ousnius** [comment]
numBones and nBones exist for design reasons. I wanted to the NIF library to be as close to IO as possible, so the typed size variable makes sure you always know what the numeric limits for the file are and you don't need a local variable when reading the size from disk. Not much reason other than that. All arrays in the NIF code do it.

**Comment by ousnius** [comment]
- AnimInfo::GetBoneXForm: mix of local and global.  Also need inverse.
- AnimSkeleton::GetSkinTransform: only skinning.translation is used?

I'm not fully sure about these either (if it has some sort of logical or practical reason or not), so in general cleaning this code up we'll have to think through the entire thing completely.

- AddShapeBoneAndXForm: for FO4, doesn't check if bone exists in Nif before grabbing its transform.

What are you referring to with this?

**Comment by sts1skj** [comment]
AddShapeBoneAndXForm: this is in OutfitProject.cpp.  For FO4, this calls NifFile::GetShapeBoneTransform on the baseShape.  If I understand correctly, this call can fail if the bone doesn't have a boneTransform for the base shape in the nif file.  In that case, AddShapeBoneAndXForm ought to fall back on getting the transform from the skeleton.  I'm not entirely certain that my reasoning is correct.

**Comment by sts1skj** [comment]
AnimInfo::GetBoneXForm: This function constructs the returned transform using AnimBone::localTrans (part of the bone-CS-to-parent-bone-CS transform) and AnimBone::rot (part of the bone-CS-to-global-CS transform).  This function is called from just one place, OutfitProject::AddShapeBoneAndXForm, which then passes the transform to AnimInfo::SetShapeBoneXForm, which puts it in AnimWeight::xform (which transforms from global CS to bone CS).

Clearly localTrans should be replaced with trans (part of the bone-CS-to-global-CS transform).

If localTrans were replaced with trans, then GetBoneXForm would return a transform from bone CS to global CS.  But AnimWeight::xform is a transform from global CS to bone CS.  So GetBoneXForm also needs to invert the transform before returning it.

In the existing code, this bug is probably harmless because, for non-FO4 nif files, AnimWeight::xform is ignored (and replaced) when writing the nif file (in AnimInfo::WriteToNif, see the code just before "bw.xform = xForm").

**Comment by sts1skj** [comment]
I'm still very confused about what the skin transform is (in NiSkinData in a nif file, or NiSkinData::skinTransform in the source code).  Can you point me to an example nif file where this transform is not the identity transform?  It's always the identity transform in the files I've examined.

My understanding of the coordinate systems (CSs) used in nif files is incomplete.  Here are the CSs I know about:

- Each bone has a CS of its own, with origin at the attachment point to its parent and z-axis pointing along the bone.

- There's a global CS with origin on the ground between the model's feet and z-axis pointing upward.

Clearly I'm missing at least one CS, as the skin transform has nothing to do with any one bone, yet it transforms from one CS to another.  Which CSs am I missing?

(I am aware that there's also a rendering CS used inside BodySlide and Outfit Studio in the OpenGL code, but that CS has nothing to do with nif files, as far as I know, and the transforms between global CS and rendering CS are hard-coded in many different places in the source code.)

**Comment by ousnius** [comment]
The bra shape in the following NIF is a culmination of every weird transform imagineable. Some of them are rendered in-game, some of them aren't (see above).

I have a big collection of debugging NIFs if you need more. [bra.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/4210379/bra.zip)

**Comment by sts1skj** [comment]
After analyzing the bra nif file in your previous post, along with the code in GLSurface::AddMeshFromNif and glm, and doing a bunch of experiments with changing things in NifSkope and seeing the results in Skyrim, here's my new understanding of the CSs in nif files.  These are the CSs:

- Each bone has its own CS.

- Each shape/skin has its own CS.  Vertices in BSTriShape::vertData are represented in this CS.

- There's one global CS.

And these are the transforms:

- skeleton nif NiNode::transform: from bone CS to parent bone CS, or to global CS for root bone.

- outfit nif NiNode::transform: from bone CS to global CS.

- outfit nif NiSkinData::BoneData::boneTransform: from skin CS to bone CS.

- outfit nif NiSkinData::skinTransform: from global CS to skin CS.

I tried changing each of these to see what effect it had on Skyrim, and the only one of the four that had any effect was boneTransform, which makes me wonder how Skyrim is transforming the vertices from bone CS to global CS.  (The skeleton file I changed was meshes/actors/character/character assets female/skeleton_female.nif.  Maybe that's not where Skyrim gets its skeleton data.)

I also figured out that, when applying a transform to a point's coordinates, the scale is applied first, then the rotation, and then the translation.

Does all of this sound correct to you?

**Comment by sts1skj** [comment]
I've looked closely at trying to fix the various transformation bugs without doing any cleanup, and I think it would be very messy.  I'd much prefer to do the cleanup and the bug fixes as one patch.  May I do so?

**Comment by ousnius** [comment]
@sts1skj Sure, just describe the major cleanups and changes so I can follow.

**Comment by brad-helgeland** [comment]
@sts1skj I'm also wanting to do some cleanup. Mainly moving the BodySlideFrame class and header into their own files. Perhaps we can work off of a cleanup branch for this? @ousnius

**Comment by sts1skj** [comment]
I've thrown together a quick and sloppy mock-up of a user interface for posing bones in Outfit Studio:
![image](https://user-images.githubusercontent.com/59774938/75293468-74621880-57e3-11ea-87a5-025f83338b5b.png)
What do you think?

I was thinking of adding this below the edit pane and above the slider pane, visible only when the bone tab is selected.

**Comment by ousnius** [comment]
Seems fine as a start.

With it, rendering bone transforms has to be implemented, but only in pose mode, not always (like when brushing anything).

While in pose mode, a lot of actions have to be disabled (editing shapes with brushes other than the weight brush, moving/rotating/scaling anything, etc...).

**Comment by sts1skj** [comment]
Implementation of this feature is finished, as far as I'm concerned, and I'm very pleased with the result.  Before, every outfit and body model I looked at in Skyrim (even "CBBE Body.nif") had rough spots that appeared as the character moved into various positions (with the extra-curvy slider settings I've been using).  By "rough spot", I mean a place where a peak, dimple, ridge, or groove appears where the model should be smooth.  Since posing was implemented in Outfit Studio a week ago, I've adjusted the vertex bone weights on a body model and five outfit models, and they now have no pose-related rough spots in Skyrim that I can detect.  I also did breast, butt, and thigh bone weights that have no pose-related rough spots I can see, even for large physics motions.

So I consider this feature completed.  Do I close the feature request myself?  Or do you do it?
