### ISSUE TITLE
Preview Window Not Working

### ISSUE THREAD

**Issue by zarzwour** [ousnius/BodySlide-and-Outfit-Studio#230]
I can change the sliders and batch build and everything else just fine but my preview window won't change when i change a slider, the body will just stay the same default body.

**Comment by ousnius** [comment]
@zarzwour Preview doesn't hang, shows the correct textures and sliders are working for me.

What's your PC hardware? Do you have the latest graphics drivers? If you have multiple graphics chips in your PC, are you running BodySlide with the dedicated one?

Does it happen with all bodies/outfits? Can you try disabling your body texture mod temporarily?

**Comment by Pirateghostmachine** [comment]
I don't know if any resolution to this problem was found, but I'm experiencing the same issue broadly. Whenever I try to use preview, I get a blank preview window. I'm running a Ryzen 3700x, so I shouldn't have integrated graphics causing a gpu clash. I'm running an Nvidia GTX 1060. All drivers are recent.

**Comment by ousnius** [comment]
@Pirateghostmachine Which game? Did you fully install the main body mod (e.g. CBBE) as well? Did you try disabling your skin texture mods? Are you using MO2?

**Comment by Pirateghostmachine** [comment]
I have fully installed CBBE. I do not use any skin texture mods. I'm using Vortex for mod management, and can launch from Vortex. When launched sliders appear. 

Something that did occur, is that I use my desktop in a headless configuration and steam it using Steamlink software. This has never been an issue before when I was using the Steamlink hardware, but recently had to switch to a Raspberry Pi running a newer iteration of the software. Prior to the switch I did not experience any concerns. I'm going to attempt running the software with a monitor on the machine. I'll update this post with results.

**Comment by ousnius** [comment]
Closing as it's not a real bug related directly to the program.
