### ISSUE TITLE
Support for distributing "diffs" of outfits

### ISSUE THREAD

**Issue by scorpiosixnine** [ousnius/BodySlide-and-Outfit-Studio#236]
**What is it that you want to do that isn't currently possible?**

It would be great if it were possible to use bodyslide to make changes to an existing outfit without having to distribute the original .nif/.osd/.osp files, in order to avoid having to obtain permission from the original author.

My use case is for a mod which wants to take an existing outfit and alter it to turn it into standalone item(s) - eg where the original outfit is designed to replace whatever the character is wearing (using slot 32), and you want to instead allow items or accessories from an outfit to be equipped (by changing the slots and perhaps removing the reference body, maybe also even altering the weights).

You can imagine other use cases though where people just want to distribute tweaks or fixes to an outfit. 

**Request the feature**

I can see a few ways of accomplishing this, but the simplest is probably a mode where at design time in outfit studio you make the edits you want on a copy of the outfit, using the `.osp` supplied by the original mod. 

You then somehow produce a binary diff which just contains your changes to the original `.osp`, `.osd` and/or `.nif` files. 

The patching mod distributes this, so that it gets installed into a known location (eg `CalienteTools/BodySlide/ShapePatches`), with the same name as the `.osp` it should be applied to.

The user of this patching mod has to install it along with the original mod, so as to get both the original bodyslide files and the new diff file.

When Bodyslide encounters an `.osp` file that has one of these diffs present, it applies it to the `.osp`, `.nif` and `.osd` files, and uses the patched versions to generate the final output.

**Comment by ousnius** [comment]
Binary patching of NIFs is not really possible. OSD files already are just diffs of vertex positions. OSP files can't really be part of mod permissions as they're just plain text files created by OS.

Unfortunately this would be too much work and quickly become rather messy. What you can do now is manually create an OSP file that references the original NIF and/or OSD and adds new sliders or changes them. You can't edit the NIF or change slots though.

**Comment by scorpiosixnine** [comment]
> Binary patching of NIFs is not really possible

A binary diff between any two files is possible - it's just a diff. It's not that hard to implement, and I'd imagine there are a bunch of libraries out there already which take a couple of buffers of bytes and spit out a diff between them, or a source buffer and a diff and spit out the destination buffer.

I'm totally fine with the "it's too much work" argument though :)

Maybe at some point I will provide you with a PR...

**Comment by scorpiosixnine** [comment]
> OSP files can't really be part of mod permissions as they're just plain text files created by OS.

Not entirely sure what you meant by this. I'm not suggesting that you actually need to change anything with the OSP file. I was just suggesting using a naming/folder convention so that if Bodyslide was processing an OSP and it spotted a matching diff file, it would apply that too.

Since the OSPs are XML, you could of course add some stuff to it relating to the diffs into them too, which would just be ignored by older versions.

**Comment by scorpiosixnine** [comment]
> if Bodyslide was processing an OSP and it spotted a matching diff file, it would apply that too.

To be clearer, I'm saying that if it encountered one of these special diff files, it would apply it, which would generate a modified set of osp/osd/nif files. It would then process the modified osp instead of the original one.

Anyhoo, I've said enough :)

**Comment by ousnius** [comment]
Distributing diffs to "patch" files is not something that will be implemented.
