### ISSUE TITLE
Add USD support

### ISSUE THREAD

**Issue by erri120** [ousnius/BodySlide-and-Outfit-Studio#249]
**What is it that you want to do that isn't currently possible?**
Export/Import of USD files.

**Request the feature**
Universal Screen Description or [USD](https://graphics.pixar.com/usd/docs/index.html) seems to be the latest and hottest file format for 3d scenes. Request can be made ultra low priority or even ignored if you want to.

**Comment by ousnius** [comment]
No plans by me to add this, but anyone is free to open PRs.

**Comment by ousnius** [comment]
Closing for now as I personally have no plans to add USD support as of right now.
