### ISSUE TITLE
Feature request: custom bone parenting and rotating

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#252]
**What is it that you want to do that isn't currently possible?**
Add a custom bone with a specified parent bone.  Specify the rotation part of the transform for a custom bone.  Edit the parent and transform of a custom bone.

**Request the feature**
1.  Add a parent-bone choice box to the add-custom-bone window and implement it.

2.  Add three rotation vector coordinate boxes to the add-custom-bone window and implement it.

3.  Add a menu item for bringing up the add-custom-bone window again to edit the parameters.

**Comment by sts1skj** [comment]
@ousnius I could implement this immediately.  It would be easier for me if you gave me an updated Skeleton.xrc to work from, as I haven't yet bothered to install an xrc editor on my computer.  I've been editing the xrc files in a text editor, which is not fun.  Plus, I've found that you almost always tweak my xrc changes anyway.

**Comment by sts1skj** [comment]
@ousnius 
![image](https://user-images.githubusercontent.com/59774938/76657556-c3c07c80-6537-11ea-8e7a-0b7789d927b2.png)
Here's my mock-up of the modified add-custom-bone dialog window.  May I implement it?

Would you prefer that the edit-custom-bone changes be a separate pull request from the add-custom-bone changes?

**Comment by ousnius** [comment]
@sts1skj Feel free to do it in the same PR.

**Comment by sts1skj** [comment]
Feature added in pull request 257.
