### ISSUE TITLE
Feature request: improve smoothing brushes

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#253]
**What is it that you want to do that isn't currently possible?**
Smoothing brushes don't do what I want in several different circumstances:

1.  When the mesh connections are asymmetrical, the result is unbalanced in favor of the side with more mesh connections.  (By mesh connection, I mean a triangle edge connecting it to another vertex.)

2.  The position-smoothing brush often moves the vertex position more along the surface than perpendicular to it.  Usually, but not always, such along-the-surface motion is undesirable.

3.  The position-moving brush often moves vertices in or out of the surface in addition to moving them along it.  Sometimes this is desirable; sometimes it isn't.

**Request the feature**
1.  Make all vertices in a connected neighborhood of the vertex matter to smoothing.  Unfortunately, this raises a parameter issue: how big should the neighborhood be?  Should the size of the neighborhood be specified by vertex count or by geometric distance?  Should the user be able to specify the neighborhood size?

If it were undesirable to add another brush parameter slider, a crude solution could be to just use the eight closest connected vertices (or ten, or twelve, or whatever).  Another crude solution would be to use the existing brush-size parameter to also control neighborhood size (which might work well or might work horribly).

It might also be nice (if the user had the option to specify a large neighborhood with lots of vertices) if the smoothing function used weighted averaging, with farther vertices affecting the result less than closer vertices.

2.  It would be nice if the position-smoothing brush had an option to restrict the movement to be perpendicular to the surface.  This could be a user-controlled switch.  A switch to restrict motion the other way, to be tangent to the surface, might (or might not) also be useful.

One question is how to determine the direction perpendicular to the surface.  A simple way would be to just average the normal directions of the adjacent triangles.  But I think you'd get better results if you did a simple plane fit (possibly weighted) of all the vertices in the neighborhood.

3.  One possibility is to add a three-way switch controlled by the user that affects how the move-position brush works: option 1 is free movement; option 2 is along-the-surface movement; and option 3 is perpendicular-to-the-surface movement.

But another possibility would be to determine which option to use automatically: if the angle between the surface normal and the camera direction is less than some angle (say 30 degrees), the motion would automatically be restricted to be along the surface; if the angle were greater than some angle (say 60 degrees), the motion would automatically be restricted to be perpendicular to the surface.

**Comment by sts1skj** [comment]
Pull request #423 implements 2 and 3.

**Comment by themilkdrinker0** [comment]
Zbrush smooth struggles with triangles too, it only works well with squares, not sure if you can make OS to guess what is supposed to be a square cut in half.
