### ISSUE TITLE
Feature request: simple mesh editing

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#254]
**What is it that you want to do that isn't currently possible?**
Fix minor mistakes in the mesh of a model.  It would be nice to be able to add and remove vertices and tweak the triangulation, all without creating holes or other undesirable topological changes to the surface.

**Request the feature**
1.  I suggest adding a tool that lets you click on a mesh edge (the side of a triangle) to split the edge in two, adding a vertex at the midpoint of the edge.  This would increase the number of vertices in the model by one and the number of edges by one.  If the edge were just of one triangle (such as on the mesh boundary), the number of triangles would increase by one (one replaced by two); if the edge were of two triangles (such as in the interior), the number of triangles would increase by two (two replaced by four).  If the edge were a weld edge, a welded pair of vertices would be created instead of one ordinary vertex.

Of course, the new vertex would need a lot of new data (position, uv, etc.).  Probably it would be best to just average the values of the two vertices at either end of the edge; the user could then tweak the result.

2.  I suggest adding a tool that lets you click on a vertex to delete.  The tool would only delete the vertex if it had no more than three connected vertices, because updating the triangulation if there are four or more connected vertices is not trivial.  The triangles attached to the vertex would be replaced with one triangle (or none if the vertex only had two connections), so the surface would be preserved, if in a simpler form.

3.  I suggest adding a tool that lets you click on an edge to flip.  It would only work on non-welded non-boundary edges, that is, edges that are adjacent to two triangles and two vertices.  The triangles would be "flipped" so that the other pair of vertices are connected.  So, for example, if the existing triangles were (0,1,2) and (0,2,3), the new triangles would be (0,1,3) and (1,2,3).  No vertices would be changed.

Of course, these three tools become more powerful together.  For example, if you have a vertex you want to delete with five connections, you first flip two of its edges; then it only has three connections, and you can delete it.  Using all three tools together would even let you close holes.

Of course, undo and redo capability would be desirable for all three tools.

A tool for welding or unwelding vertices might also be desirable, but I don't know enough about welding to request this feature at this time.  I have seen a bunch of welding problems in outfits.

**Comment by sts1skj** [comment]
I've been studying the code, trying to figure out how to make a "delete vertices (and triangles)" operation undo-able.  As far as I can tell, Outfit Studio doesn't currently have any code that supports un-deleting a vertex or adding a vertex.

The big question in my mind is what data to stash in UndoStateProject for a delete-vertices operation.  Here are four of my ideas:

1. Stash the entire project.  Perhaps stash a deep copy of OutfitProject, or maybe just the important data from OutfitProject.

2. Stash all of the shape's data: the NiShape, the descendants of the NiShape in the NifFile, the DiffDataSets, maybe the AnimSkin, maybe other stuff.

3. For each vertex or triangle deleted, stash everything about that vertex or triangle so that it can be restored (including the vertex's index).  Some of the stashed data would only be relevant if the corresponding Nif structure were present.  For example, the stashed-vertex-data structure would contain a "Vector4 dynamicData" that would only be used if the shape were a BSDynamicTriShape.

4. Stash data for each vertex or triangle deleted, but make each vertex/triangle's data a polymorphic-data container, with the exact contents depending on what Nif structures were present.  Some data, such as vertex coordinates, would always be present.  Other data, such as BSDynamicTriShape's dynamicData, would only be present if the Nif had that data, using a polymorphic "extra vertex undo data" structure.

Options 1 or 2 would be versatile, but the memory cost could be high.  Options 3 or 4 would cost little memory, but "insert vertex" and "stash vertex data" functions would have to be added to every Nif class that has a notifyVerticesDelete function, and more.

What do you think?  Do you have any comments on any of these four options?  Can you think of any options I missed?  Is there any existing code in Outfit Studio for supporting this that I missed?  Am I totally on the wrong track, thinking about this problem this way?

**Comment by ousnius** [comment]
I doubt undo/redo of vertex deletion and addition is easily possible as Outfit Studio uses the NIF format as its working format (which is why it's so convenient to use to begin with), but this is one of the downsides.

Deleting vertices (and via notifyVerticesDelete) is always easier as you don't have to add any data that doesn't exist. I don't think Outfit Studio should be a mesh editor to this extent (it will never end until it's Blender or Max), so I wouldn't implement any of the features listed in this issue.

**Comment by sts1skj** [comment]
Is there a way to transfer the data to and from Blender?  I spent quite a bit of time looking for a way, and I found nothing, but I'm not great at finding things.

**Comment by 3000percentmanlyjaw** [comment]
From understanding of what you want (manipulation of topology, different poly count, etc.) there's not much that's out there that can streamline this. Of course there is the GoZ-Pipeline feature, however that only respects a mesh/obj that has the same VO order as before - even changing normals can cause it to go completely mongo.

You _might_ be lucky to search for something GoZ-Related though -- maybe someone made a different GoZ-Pipeline for blender that allows complete manipulation (add/del of verts, UV, ... etc.), doubt it though.

**Comment by sts1skj** [comment]
I've been studying the code for skin partitions (NiSkinPartition).  It looks like the triangles and vertices of a shape's partitions follow three rules:

Rule 1. Every partition triangle is also a shape triangle.

Rule 2. Every one of the shape's triangles is a member of exactly one partition.

Rule 3. The vertices of a partition are precisely the vertices of the triangles of the partition.

I've found three functions that modify the triangles and vertices of a partition: OutfitStudioFrame::ShowPartition, NiSkinPartition::notifyVerticesDelete, and NifFile::UpdateSkinPartitions.  The code of these functions is very complex, so I'm not sure I've interpreted them correctly, but all three appear to maintain the above three rules.  UpdateSkinPartitions also appears to _enforce_ the three rules.

Please let me know if anything I've written above is incorrect.

I have not looked at skin segments at all; for all I know, they may work similarly.

The above rules seem to imply that the triangles and vertices of a shape's partitions can be calculated from the _shape_'s triangles and vertices with one additional piece of information: the partition index of each shape triangle.  With this "source" data, it appears to be possible to calculate the vertexMap, triangles, and trueTriangles of each NiSkinPartition::PartitionBlock.  In addition, vertexWeights and boneIndices can also be derived using the above information plus the shape's bone weights.  (This weight data derivation is already done in UpdateSkinPartitions.)

So the _source_ data for a shape's partitions appears to be simply the partition index for each shape triangle plus other non-array partition data such as vertexDesc, flags, and partID.  Everything else can be derived, if my reasoning is correct.

So I propose simplifying Outfit Studio's code for editing partitions:

Simplification 1. Use shape vertex indices instead of partition vertex indices for the triangles of a partition outside of lib/NIF.  This would mean adding code to NifFile::GetShapePartitions and NifFile::SetShapePartitions to convert the triangles when the shape is not a BSTriShape.  This would allow OutfitStudioFrame::ShowPartition to be simplified by deleting each "if (!isBSTri)" block.

Simplification 2. Eliminate "verts" from PartitionItemData (in OutfitStudio.h).  It can be recalculated from "tris" when needed, which is in just two places: in ShowPartition, in the block at the end titled "Display partition colors"; and in OnPartitionApply, just before passing it to SetShapePartitions.  This would further simplify the partition-update code in ShowPartition.

Simplification 3.  Add a member variable "triParts" (triangle partition indices, a vector of ints) to OutfitStudioFrame; eliminate PartitionItemData::tris; and use triParts instead of tris.  This would further simplify ShowPartition.  Of course, code for calculating triParts would need to be added to OutfitStudioFrame::CreatePartitionTree, and code for calculating tris would need to be added to OutfitStudioFrame::OnPartitionApply.  (NifFile::UpdateSkinPartitions already does both of these conversions as it does its work; an array listing each triangle's partition index is very useful for enforcing the above three rules.)  (Perhaps a better name than "triParts" would be "trianglePartitionIndices".)

Simplification 4. Move the code for recalculating the partition vertex list and triangle list from OutfitStudioFrame::OnPartitionApply to NifFile::SetShapePartitions; move the code for calculating the triangle partition indices from OutfitStudioFrame::CreatePartitionTree to NifFile::GetShapePartitions; and eliminate the "verts" and "tris" parameters of GetShapePartitions and SetShapePartitions in favor of a triParts parameter.

After these four simplifications, the three rules above would be implicitly enforced by the way the data is stored (in triParts instead of verts and tris).  Of course, lib/NIF would still have to deal with the nastiness of NiSkinPartition, but the rest of Outfit Studio wouldn't.

May I implement the above simplifications?

**Comment by ousnius** [comment]
@sts1skj 
If it doesn't affect performance in a negative way and the resulting partitions are identical to before, you may try to implement simplifications.

Be careful with vertex and triangle indices, some of them point to the full/real list in the shape or skin partition block, and some point to the partition specific lists of vertices and triangles.

**Comment by sts1skj** [comment]
I've been struggling to figure that out.  It's clear that sometimes NiSkinPartition::PartitionBlock::triangles uses "partition vertex indices", and sometimes it uses "shape vertex indices".  The mapping of partition vertex indices to shape vertex indices is given by NiSkinPartition::PartitionBlock::vertexMap, no matter which type of indices "triangles" uses.  It's also clear that NiSkinPartition::PartitionBlock::trueTriangles always uses shape vertex indices and not partition vertex indices.

Question 1. At the end of NiSkinPartition::Get, the function that reads all of this data from a file, does "triangles", if it's not empty, _always_ use partition vertex indices?  (My guess is yes.)

Question 2.  If the answer to question 1 is no, is there a way to determine, in NiSkinPartition::Get, whether shape vertex indices or partition vertex indices are used by "triangles"?

Question 3.  At the end of NiSkinPartition::Get, does NiSkinPartition::PartitionBlock::strips, if it's not empty, _always_ use partition vertex indices?  (My guess is yes.)

Question 4.  If the answer to question 3 is no, is there a way to determine, in NiSkinPartition::Get, whether shape vertex indices or partition vertex indices are used by "strips"?

I haven't been able to answer these questions by just reading the code.  Because "triangles" and "trueTriangles" are separate member variables, it is implied that the answers to questions 1 and 3 are yes.  But I haven't seen any code that assumes that; the test used elsewhere is "if (!isBSTriShape)", which obviously uses information not present in NiSkinPartition.

**Comment by sts1skj** [comment]
I've looked at a bunch of sample Nif files using NifSkope, trying to find any for which question 1 is "no" (that is, "triangles" uses shape vertex indices and not partition vertex indices).  I've found something very confusing: in every case where NiSkinPartition had "trueTriangles", it also had "triangles", and "triangles" was exactly the same as "trueTriangles".  That is, the data was duplicated in the file!  I wonder if I'm misinterpreting what NifSkope is showing; I can't think of a reason to include two copies of the very large triangle list in a Nif file.

This seems to suggest a partial answer to my question 1: when trueTriangles is present, "triangles" can use shape vertex indices instead of partition vertex indices.  Question 1 then breaks down into:

Question 1a: If "triangles" is present in a file and "trueTriangles" is not, does "triangles" always use partition vertex indices?

Question 1b: If "trueTriangles" and "triangles" are both present in an NiSkinPartition in a Nif file, are they always the same?  If they're not the same, what is the significance of the differences between them?

Questions 2, 3, and 4 from my previous post remain a mystery to me.

**Comment by ousnius** [comment]
Skin partitions (NiSkinPartition) are different in LE and SE. For both games, skinned meshes use the skin partitions for rendering (not the NiTriShapeData or BSTriShape data).

While NiTriShapeData in LE still had the vertex data and triangles present, BSTriShape in SE does not (no vertex data or triangles on the shape itself). To simplify the code in OS somewhat, it copies the data from the NiSkinPartition to the shape object, so it's in the same place for all games (in code not file).

Each partition holds the vertex descriptor saying which data is present in the vertex data array, so their mesh/shader loader can upload each partition as if it were its own mesh.

For SE meshes, the triangles and trueTriangles in a partition never differ (at least I haven't seen such NIF and OS always sets them to the same, no issues). Don't ask me why it was duplicated or added. Both triangle lists always point to the real (full) vertex index.

For LE meshes, trueTriangles doesn't exist and the indices in triangles point to the vertex map of the partition. It maps each partition-specific vertex index to the full meshes' vertex index.

Strips are an old structure used in games before LE, you can ignore them as they're not really relevant. OS converts them to triangles anyway.

So at least on the file, vertexmap and triangles have no reason to exist for SE: They probably appended new data at the end of the class and kept the existing one. So OS adds/keeps them.

**Comment by sts1skj** [comment]
If I create a helper function that might be called from lib/Nif/Skin.cpp, lib/Nif/Geometry.cpp, and lib/Nif/NifFile.cpp, which header and source files should I put the helper function in?

An example of such a helper function would be "ApplyMapToTriangles", which would apply an index map to a vector of triangles.

**Comment by ousnius** [comment]
@sts1skj There's no separate files for such utility functions yet, so it's all part of the NifFile class.

**Comment by sts1skj** [comment]
@ousnius As part of my efforts to simplify and clean up the partition code, I've been studying the function NifFile::UpdateSkinPartitions to try to figure out what it does.  I've found a bug that has a big effect on what it does.

There's an inner loop in this function starting with "while (!vertQueue.empty())" that is never executed because vertQueue is always empty (because of a bug in the previous block of code that is meant to prime it).  The purpose of this loop, apparently, is to find connected triangles to move from other partitions into the current partition so long as the resulting partition bone list won't be longer than maxBonesPerPartition.  However, there are enough bugs involving this loop that, if it were ever executed, I suspect the partitions would be trashed.

As part of my cleanup, may I remove this loop and its intended purpose?  Or should I fix the bugs so that it works as intended?  It would tend to merge the shape's partitions together whenever the file is saved; that's probably undesirable.

**Comment by ousnius** [comment]
@sts1skj As far as I understand, that loop is getting all verts of the assigned triangle and then adds their adjacent triangles to the partition (if enough space is left).

I can't think of why this is necessary anymore right now, but I don't see how that part of the function is not being executed right now. Can you elaborate on what causes vertQueue to always be empty? I'm not seeing it.

After that I'll decide if it can be removed or not.

**Comment by sts1skj** [comment]
@ousnius vertQueue is supposed to be primed in the preceeding call of fSelectVerts.  fSelectVerts only adds the vertices to the queue if usedVerts is false for those vertices.  But usedVerts is set to true for those vertices a few lines before the definition of fSelectVerts.

It took me a lot of work to find that bug.  I should have explained more thoroughly in my previous message.

**Comment by ousnius** [comment]
@sts1skj Are you sure "triIndex" points to the same triangle in "tris" that is also described by "tri"? I think it only does for bsTriShape but not for others.

**Comment by sts1skj** [comment]
@ousnius triIndex is set to "realTri - tris.begin()".  tris is set using "shape->GetTriangles(tris)", and the tris are "rot"ed but otherwise unmodified.

realTri is an iterator pointing into tris.  It is set by searching tris for a triangle t for which "t.CompareIndices(tri)" is true.  So realTri points to a triangle identical to tri.  So tris[triIndex] is a triangle identical to tri.

**Comment by ousnius** [comment]
Yeah, I was being confused by the two different sources of tris. If it's not being called right now, then it can be removed. Maybe just hook a breakpoint to it once to confirm we're both not missing something.

**Comment by sts1skj** [comment]
I stuck a print statement in there and used Outfit Studio to export "CBBE Body.nif" (Skyrim SE).  The print statement was never called.

**Comment by sts1skj** [comment]
@ousnius Here's my plan for extracting common code from the various notifyVerticesDelete functions and a few others in lib/NIF:

-Make a new header file, lib/NIF/utils/Alg.h, with some algorithm functions.  Use a new namespace, NifUtilsAlg.  The functions would be:
    ApplyMapToTriangles (move from Object3d.h)
    CalcMaxTriangleIndex (move from Object3d.h)
    EraseVectorIndices
    GenerateIndexCollapseMap
    GenerateTrianglesFromStrips

Use these algorithm functions wherever appropriate.  A list is below, for each function. 

-ApplyMapToTriangles needs to have an optional parameter added that returns the deleted triangle indices.  Use in:
    NiSkinPartition::PartitionBlock::GenerateTrueTrianglesFromMappedTriangles
    NiSkinPartition::PartitionBlock::GenerateMappedTrianglesFromTrueTrianglesAndVertexMap
    BSTriShape::notifyVerticesDelete
    NiTriShapeData::notifyVerticesDelete

-EraseVectorIndices would take a vector of data and a sorted vector of indices.  The listed indices of the data vector would be erased.  Use in:
    NiSkinPartition::RemoveEmptyPartitions 
    NiGeometryData::notifyVerticesDelete
    BSTriShape::notifyVerticesDelete
    BSDynamicTriShape::notifyVerticesDelete
    NiLinesData::notifyVerticesDelete

-GenerateIndexCollapseMap.  Given a sorted list of indices to delete, this would create an index renumbering map (vector of int) that would map old indices to new indices, with -1 for indices to delete.  Use in:
    NiSkinData::notifyVerticesDelete
    NiSkinPartition::notifyVerticesDelete
    BSTriShape::notifyVerticesDelete
    NiTriShapeData::notifyVerticesDelete
    NiTriStripsData::notifyVerticesDelete
    NiSkinPartition::RemoveEmptyPartitions

-GenerateTrianglesFromStrips.  Given a vector of vectors of indices, such as NiTriStripsData::points, produces a list of triangles corresponding to those strips.  Use in:
    NiSkinPartition::PartitionBlock::ConvertStripsToTriangles
    NiTriStripsData::StripsToTris

I might come up with one or two more functions as I do the work, but probably not.

May I start implementing this?  Are you okay with the new header file name "lib/NIF/utils/Alg.h"?  Are you okay with the new namespace name NifUtilsAlg?  Would you prefer that the functions not be in a namespace?

**Comment by ousnius** [comment]
@sts1skj Namespaces are great, but none of the code has them right now so I rather not start with that now. That can be its own refactoring at a point in the future.

I'd prefer the header file to be named "lib/NIF/NifUtil.h" (not in the utils folder, that's for non-directly-NIF related things).

Feel free to do it provided functionality stays the same.

**Comment by sts1skj** [comment]
@ousnius I've been studying the segment code, both in branch dev and branch Segmentation-Rework.  There seem to be three different places segment data can be stored in a NIF file: in BSSubIndexTriShape::segmentation, in BSSubIndexTriShape::segments, and in BSSegmentedTriShape::segments.  It looks like at most one of these three places is used at one time; they're mutually exclusive.  They also appear to be mutually exclusive with partitions (NiSkinPartition).

Code for manipulating segments seems to be limited to BSSubIndexTriShape::notifyVerticesDelete, BSSubIndexTriShape::SetDefaultSegments, and the OutfitStudioFrame functions for editing BSSubIndexTriShape::segmentation.  In particular, I see nothing for manipulating BSSegmentedTriShape::segments (not even a notifyVerticesDelete function), and I see nothing for editing BSSubIndexTriShape::segments.  Only editing of BSSubIndexTriShape::segmentation appears to currently be implemented.

Segments seem to follow rules very similar to partitions:

Rule 1. Every triangle is a member of exactly one segment.

Rule 2. Segments do not always have subsegments, even when subsegments are supported by the data structures.

Rule 3. If a segment has subsegments, every segment triangle is a member of exactly one subsegment.

Rule 4. Triangles are ordered by segment and subsegment so that very little data is needed to represent segment and subsegment membership in the file.  So changing anything to do with segments usually means reordering the triangles.

In the dev branch, segment triangle-membership data is translated from nif form to a more convenient form in OutfitStudioFrame::CreateSegmentTree and translated back in OutfitStudioFrame::OnSegmentApply.  This more convenient form is a set of uint for each segment/subsegment giving the indices of triangles belonging to that segment/subsegment.

In the Segmentation-Rework branch, segment triangle-membership data is instead translated into an array of segment/subsegment ids, with the size of the array matching the triangle list, so each triangle has an associated id giving its membership.  As this branch was never integrated into dev, it's unclear whether the code is complete (probably not).

Please let me know if anything I've written above is incorrect.

So it looks like segments give a mathematical partitioning of the triangles.  The partitions are the childless segments and the subsegments.  Though the file data of segments is complex, it seems to boil down to nothing more than a partition membership for each triangle (plus non-triangle data such as material).

I propose making the following simplifications to the segmentation code:

Simplification 1. Replace SegmentItemData::tris and SubSegmentItemData::tris (in OutfitStudio.h) with triParts.  Add a partition id to each of those two data structures.  The partition id for each segment/subsegment would be determined in CreateSegmentTree, and triParts would be filled in with each triangle's membership partition id.  This would allow ShowSegment to be simplified (just as in the Segmentation-Rework branch or my own rework of partitions).  Unlike in Segmentation-Rework, the partition ids would have no encoded meaning; their purpose is merely to be unique for each segment/subsegment.

Simplification 2. Instead of OutfitStudioFrame working with BSSITSSegmentation directly, create an intermediate form that separates out the triangle membership data into the simpler triParts representation.  This would move code for translating between forms from OutfitStudioFrame into NifFile.

Change 3. Add code to NifFile for handling the other two segment representations, using the same intermediate form as in simplification 2.  So OutfitStudioFrame could handle all three forms of segment data using mostly the same code.

May I start implementing this?

Minor question: should BSGeometrySegmentData::flags be editable by the user?  What should it be set to if a new segment is created?  (I'd rather just set it to 0 and let someone else deal with making it user-editable.)

**Comment by ousnius** [comment]
BSSegmentedTriShape and BSSubIndexTriShape::segments aren't relevant for OS at this point, you're free to do the refactor for BSSubIndexTriShape::segmentation.

The other things you said are correct.

**Comment by sts1skj** [comment]
@ousnius Next, I would like to make the "Delete Vertices" command undoable when it doesn't delete the entire shape.  (Also, I'd make the vertex-deletion part of the "Separate Vertices" command be undoable.)  Here's the plan:

-Add data structures, possibly to lib/NIF/VertexData.h, for storing all NIF data for a vertex or triangle:

TriangleAllData:
int index in triangle list
Triangle
int partition ID

VertexAllData:
Vector3 pos
Vector2 uv
Vector3 normal
Color4 color
Vector3 tangents ?
Vector3 bitangents ?
float eyeData ?
vector of SkinWeight: bone weights

-Add an undo type, perhaps called UT_MESH.  In UndoStateShape, add lists of vertex and triangle data deleted.  For a triangle, it would just be TriangleAllData.  The undo record for a vertex would have:
VertexAllData
vector of slider-name and Vector3: slider diffs
int index in vertex list

-Add functions to lib/NIF:
GetOneTriangle
InsertTriangles
GetOneVertex
InsertVertexIndices
SetOneVertex

-Add functions to AnimInfo and DiffDataSets for inserting vertex indices, setting their data, and (for DiffDataSets) getting their data.

-Make OutfitStudio::OnDeleteVerts and OutfitStudio::OnSeparateVerts (and the functions they call) store all the data in an undo record before deleting it.  Add code to ApplyUndoState to undo and redo the new undo type.

The above plan ("plan A") would be the most efficient in terms of execution time and algorithmic complexity, I think.  But I've also seriously considered a slightly different plan, which I'll call plan B: instead of adding functions to lib/NIF for getting, setting, and inserting triangles and vertices, use existing functions like SetVertsForShape.  So there would be a single large function in OutfitProject that would read the various data arrays from the NIF, change them, and set them.  This would be a little less efficient, I think, but it might be more appealing, since it would reduce the number of new functions added to lib/NIF.

May I implement undo for delete-vertices?

Questions:
-Do tangents and bitangents need to be preserved?
-Does eyeData need to be preserved?
-Are there any vertex or triangle data records missing from the structures above, or any that don't need to be there?
-Is it okay to add the two data structures to lib/NIF/VertexData.h?  If not, where should they go?
-Are the data structure and function names okay?
-Do you prefer plan B (single big function instead of lots of little functions)?

**Comment by ousnius** [comment]
@sts1skj I would prefer to see plan B first, if that's fine. Eye data and norm/tan/bitan shouldn't *really* be needed, but just storing it all shouldn't be much more effort than leaving out single ones. If it's a hassle you can leave out eye data.

I would prefer the two data structure to be located in TweakBrush (or similar) if possible, as it's not really needed in the NIF lib if we do plan B, right?

What's most important is vertex position, triangle, weights, bones, partitions and segments. The undo also needs to insert these in the same place that they were in before. You also need to keep the diff data for sliders to be able to undo vertex deletion.

This one might be a bit trickier.

**Comment by sts1skj** [comment]
Once the undo-delete-vertices pull request 277 (undoDelVert branch) has been accepted, I'll be ready to start implementing the first of the new mesh editing tools: eliminate vertex.

- Add a menu item to the tools menu.  I suggest calling it "Eliminate vertex", with a tooltip of "Delete a vertex from the mesh with no more than three connections, updating the triangulation so no hole is created".

- Add a tool button to the toolbar.  I was thinking of drawing a 3-connection vertex with a little red X over it.

- When in eliminate-vertex mode, the cursor circle would not be drawn ("cursormesh" in GLSurface::UpdateCursor), but the intersection point ("cursorcenter") and nearest vertex ("pointhilite") would still be drawn.

- When the user clicks on (or near) a vertex, the number of neighboring vertices would be counted.  If it were more than three, an error message would be displayed.  For welded vertices, a separate check would be done for each welded vertex.

- If the no-more-than-three check is passed, the vertex would be deleted along with the triangles depending on that vertex.  If the number of neighboring vertices were exactly three, a new triangle would be added connecting them.  This would be done for all welded vertices.

- The result would be that the vertex clicked on would be gone, without a hole being created in the surface.

Should the operation happen on mouse-down or mouse-up?  It's much easier to do it on mouse-down, of course, but many standard user-interface elements (like buttons) don't activate until the user releases the mouse over the same element they pressed it on.

May I start implementing this?

**Comment by ousnius** [comment]
@sts1skj Mouse up please. Can you explain the use of the functionality?

**Comment by sts1skj** [comment]
It lets you turn this:  
![image](https://user-images.githubusercontent.com/59774938/79031372-89a8c180-7b5b-11ea-9f06-c1ec14af4b3d.png)
into this: 
![image](https://user-images.githubusercontent.com/59774938/79031395-ac3ada80-7b5b-11ea-97d4-cddaf7c7c587.png)
Is that what you wanted to know?  Note that it'll become more powerful in conjunction with the edge-flip and edge-split tools (the other two tools of this feature request).

**Comment by sts1skj** [comment]
Documentation

Collapse vertex ![CollapseVertex](https://user-images.githubusercontent.com/59774938/79513283-af711300-8000-11ea-9951-8f0205893ec8.png)

This tool allows you to click on a mesh vertex to delete.  The vertex must have no more than three connections to other vertices.  If it has exactly three connections, a triangle is added connecting them, so no hole is created.

Before:
![image](https://user-images.githubusercontent.com/59774938/79513471-273f3d80-8001-11ea-9c09-bcbb573eb36e.png)

After:
![image](https://user-images.githubusercontent.com/59774938/79513605-79805e80-8001-11ea-803a-d4f09e42849d.png)

Before:
![image](https://user-images.githubusercontent.com/59774938/79513735-c401db00-8001-11ea-97e7-4e2f8d8d3171.png)

After:
![image](https://user-images.githubusercontent.com/59774938/79513792-edbb0200-8001-11ea-962f-843a9f0b17c1.png)


Flip edge ![FlipEdge](https://user-images.githubusercontent.com/59774938/79513817-ff040e80-8001-11ea-83da-afc69350b501.png)

This tool allows you to click on a mesh edge to flip.  The edge must not be on the boundary of the surface or on a weld.  The two triangles to either side of the edge are replaced with two new triangles such that the opposite pair of vertices is connected.

Before:
![image](https://user-images.githubusercontent.com/59774938/79513988-615d0f00-8002-11ea-95b1-c8e75f0e8f15.png)

After:
![image](https://user-images.githubusercontent.com/59774938/79514061-881b4580-8002-11ea-886a-921ab84550e7.png)


Split edge ![SplitEdge](https://user-images.githubusercontent.com/59774938/79514113-a8e39b00-8002-11ea-8dfe-6c1e242485e5.png)

This tool allows you to click on a mesh edge to split in two with a new vertex.  Neighboring triangles are also split in two.  The new vertex will be at the midpoint of the edge, adjusted for surface curvature.

Before:
![image](https://user-images.githubusercontent.com/59774938/79514266-037cf700-8003-11ea-9712-f68638ee4d72.png)

After:
![image](https://user-images.githubusercontent.com/59774938/79514321-227b8900-8003-11ea-8f1b-76adb4b2a2a5.png)

Before:
![image](https://user-images.githubusercontent.com/59774938/79514476-79815e00-8003-11ea-80b9-4334c2618998.png)

After:
![image](https://user-images.githubusercontent.com/59774938/79514507-8e5df180-8003-11ea-993d-55498b4d7e5c.png)

**Comment by ousnius** [comment]
These are implemented and the wiki was updated.
