### ISSUE TITLE
Feature request: undiff brush

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#255]
**What is it that you want to do that isn't currently possible?**
Outfit Studio's "Conform Slider" function sometimes produces poor results for specific diff sets (sliders) in small areas.  Fixing these poor localized results is difficult.

For example, this problem can be seen for the Skyrim outfit "CBBE Vanilla - Body - Merchant" (or "CBBE Vanilla/Body/Merchant.nif").  If you load this outfit, conform the dress to the reference, and examine the effect of the "Thighs" slider, you will see the fabric scrunch together in front of the thighs.  There's no easy way to fix this in Outfit Studio that I know of.  I've seen cases where the scrunching together is so bad that there's overlap, with vertices on both sides moving past each other past the centerline.

**Request the feature**
I suggest adding an "undiff" brush to Outfit Studio.  When slider-edit is on, and the brush is applied to some vertices, those vertices would move towards their undiffed position (that is, the position they'd have if the slider were set to zero).

Note: Looking at the merchant outfit mentioned above, without making any changes to it at all, I see the "Thighs" slider does not scrunch the front of the dress, and the vertices move in a very smooth and reasonable way.  I don't know how this effect was achieved with this outfit.  Perhaps Outfit Studio already has functionality like an undiff brush, and I just don't know about it?

**Comment by ousnius** [comment]
I have an idea in mind that would require an undiff brush as well, so this is a good request.

**Comment by ousnius** [comment]
@sts1skj I implemented the undiff brush. Please let me know if there's something about it that wasn't like what you imagined it should be like.

**Comment by sts1skj** [comment]
@ousnius It seems to work fine.
