### ISSUE TITLE
Feature request: sliders affect bones

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#256]
**What is it that you want to do that isn't currently possible?**
I would like bone coordinate systems (primarily the bone CS's origin, but rotation might be useful too) to depend on the slider settings.

An obvious example whose usefulness is not clear would be a bone like "NPC L Breast" or "NPC L Butt".  It _seems_ obvious that the position of these should vary as breast or butt size varies.  What's not so clear is why it would be useful.

A similar example is the "HipForward" slider for the CBBE body for Skyrim.  This moves the positions of a large chunk of the model quite a bit.  It _seems_ obvious that moving the positions of all the bones in the affected area would be good.  The precise usefulness is not so clear.  (Perhaps it would make a z-axis rotation of a thigh look better?  Experimenting in OS suggests so.)

Another example where the usefulness is clearer is for custom bones used for physics simulation of clothing that dangles from some protruding body part.  The easiest way to do these physics simulations, as far as I know, is to position a bone at the rotation point of the dangling clothing.  If that rotation point depends on the body shape, then the dangle-point bone should move as the body shape changes.  That is, the dangle-point bones for a skirt, say, should move outward as the hips and butt get bigger.

To test this last example, I experimented with the Skyrim clothing model "Keo - Merchant", which has a long narrow skirt dangling from the butt.  First I cleaned up the model, made the sliders not distort it, and adjusted all the bone weights so that no rough spots were visible as the pose changed.  I made the rear skirt depend solely on the pelvis bone, so it would hang roughly downward.  Then I added breast, butt, and thigh bones, adjusted their weights so that no rough spots were visible, and created an hdt-smp physics file for the outfit so that everything moved nicely, with large jiggly motions, for an extra-curvy slider preset.  I made the rear skirt depend solely on the butt bones.  Then I added four bones, two for each butt cheek dangle point.  To "NPC L Butt", I attached "DangleLButt0", positioned at the left-buttock dangle point for the high-weight slider settings.  To "DangleLButt0", I attached "DangleLButt1", positioned below it.  I did the same for the right buttock.  I shifted weight from the butt to DangleLButt1 and DangleRButt1 and adjusted the weight so that the skirt moved smoothly with no rough spots, for the high-weight slider settings.  I created physics settings where DangleXButt0 was fixed relative to its parent and DangleXButt1 could only rotate and was affected by gravity.  The result looked reasonable in Skyrim, with no rough spots or gravity-defying spots.  Then I reduced the character weight to 0 in racemenu, restoring the butt size to more or less the default.  This made the skirt no longer dangle properly, with the dangle point clearly far out from the buttocks.

**Request the feature**
I would like Outfit Studio to support having the bone coordinate systems for a model depend on the slider settings, just as vertices do.  Perhaps the osd (Outfit Studio Diff) file already supports this; I haven't investigated.

I'm not sure of a good interface for specifying this.  One easily-implemented interface would be to have a bone-transform editing window that could be used to enter transform values that depend on the current slider being edited.  A fancier interface would display bone CS origins in the model view, with tools to adjust their positions precisely (but I'm not sure that such an interface would be good for editing the rotation part of the transform).

In addition, of course, BodySlide would have to apply the diffs to the bone transforms in addition to everything else when building bodies and outfits.

For custom bones, this would be enough, I think, since all of the in-game parameters for custom bones come from the outfit file.  For standard bones, though, I don't know whether this would be sufficient.  It might be that the physics mod (such as hdt-smp) would need to be modified so that standard-bone parameters also came from the outfit file rather than the skeleton file.  Or maybe hdt-smp (and other physics mods) already works this way.

The race-menu morphs plugin would also need to be updated, I suppose.

If there's a better way to do dangling physics simulations so that this feature would not be needed for good results, please let me know.

If you know of a better example where this not-diffed-bone problem is more obvious than in the dangling skirt example, please let me know.  (Perhaps weapon attachment points?  I know nothing about those.)

**Comment by ousnius** [comment]
This isn't something that is feasible I'm afraid. It won't work correctly with the actual rig of the game either and causes NIFs that are randomly and wildly different.
