### ISSUE TITLE
Update Compilation Wiki Entry

### ISSUE THREAD

**Issue by erri120** [ousnius/BodySlide-and-Outfit-Studio#259]
From the [Khronos OpenGL ES Registry](https://www.khronos.org/registry/OpenGL/index_es.php):
> Khronos Shared Platform Header (<KHR/khrplatform.h>)
> The OpenGL ES 3.0, 2.0, and 1.1 headers all depend on the shared <KHR/khrplatform.h> header from the EGL Registry. 

Building BS/OS requires `glext.h` but that file also requires the `KHR/khrplatform.h` file.

> Get the GL/glext.h header file from https://www.khronos.org/registry/OpenGL/api/GL/glext.h and copy it to your current Windows SDK folder, for example %ProgramFiles(x86)%\Windows Kits\10\Include<version>\um\gl

Should be updated to also include a download link to the file form [here](https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h).

**Comment by ousnius** [comment]
Older versions of the glext header didn't require the additional header file, that's why that info isn't in the instructions.
