### ISSUE TITLE
Without normalization weights can go over 1.0

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#265]
With "Normalize Weights" off and AdjustWeights() not running, you can paint weight factors that go above 1.0. Unfortunately I didn't notice it before releasing 5.0.1.

@sts1skj Could you please take a look at it? If you can't get to it within the next 24 hours I will have to think of a temporary fix, but it might not fit into your code cleanly.

**Comment by sts1skj** [comment]
@ousnius I'm sorry about that.  I'll get on it right away.

**Comment by ousnius** [comment]
No problem, I should have tested better (I tested weight painting, but didn't try to go above 1.0...).

**Comment by sts1skj** [comment]
I've submitted the pull request.

I have to admit that I didn't study the problem of turning normalization off carefully before I submitted the pull request last night.  I think I may have had an emotional reaction that led to me cutting corners.  Do you want me to more thoroughly investigate the consequences of not calling AdjustWeights?

**Comment by ousnius** [comment]
@sts1skj Thanks. I'll be releasing another version, so let me know if you can find any issues in the next hour or so, but I can't leave this one up for long.

**Comment by sts1skj** [comment]
I've looked through the old code from before I touched it, and all it did then was clamp weights to [0,1].  So turning off bNormalizeWeights should result in the same behavior as before.

That's all I can think of to check.
