### ISSUE TITLE
Brushing a mesh while posing saves the posed shape

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#272]
When brushing/editing a mesh while posing transforms are active, the edits are being stored with the posed result. This issue doesn't occur when editing a slider since it happens to reset the pose beforehand (another bug that happens to result in something positive).

@sts1skj We can either make it so you can't brush on shapes/sliders while posing or we need to fix the issue where it bakes the live vertices into the base shape of a mesh.

**Comment by sts1skj** [comment]
I'd recommend turning off posing when switching to the meshes tab.  Probably it's just a matter of calling the right update function in OutfitStudioFrame::OnTabButtonClick, but I'm not sure what.  bPose is already being turned off in that function; the mesh just isn't updated.

**Comment by sts1skj** [comment]
You probably need to do the GetLiveVerts/UpdateMeshVertices combination at the end of OnTabButtonClick.
