### ISSUE TITLE
Batch Build "Invert Selection" not working 

### ISSUE THREAD

**Issue by Neko14789** [ousnius/BodySlide-and-Outfit-Studio#282]
**Description**
When using the Batch Build "Invert Selection" it does not change anything. If first using the Select None option and than using Invert Selection the first 2 Outfits get checked

**How to reproduce**
1. Open Batch Build
2. Select some Outfits
3. Right Click
4. Invert Selection

**Comment by ousnius** [comment]
Fixed, thank you.

**Comment by Neko14789** [comment]
Hi, i just download the newest Version and yeah, i see that you changed something.
It seems like you made the "Invert Selection" Button invert everything all the time.
From my understanding and also prefered would be that this option only inverts the Selected itemes so you can switch off big amount of items very fast.

**Comment by ousnius** [comment]
@Nico14789 Yes, it inverts everything (as intended).
You can use the space key to toggle all selected items. This is standard Windows behavior for all programs.

**Comment by Neko14789** [comment]
Oh, didn't know about that (Spacebar), and now thinking about it i can understand why it is called Invert Selection.

Thx for your reply
