### ISSUE TITLE
Quick Save (Ctrl+S) Fails. Save As Succeeds

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#283]
**Description**
Attempting to save changes to an exiting OSP file fails. If you Save As the save will succeed. After saving as if you attempt to regular save (Eg. Hotkey Ctrl+S) it will succeed.

**How to reproduce**
1. Open an existing project while using MO2
2. Make changes
3. Attempt to Save changes
4. See error.

**Comment by ousnius** [comment]
There are no issues with this without MO2. Please discuss this behavior with MO2 developers on, for example, their Discord channel or their own issue trackers.

**Comment by AdamVezina** [comment]
Okay will do. Thanks!
