### ISSUE TITLE
UV map is lost after separating or deleting vertices and exporting mesh in Outfit Studio v5.0.5

### ISSUE THREAD

**Issue by snake-eater911** [ousnius/BodySlide-and-Outfit-Studio#286]
How to reproduce:

1. Mask vertices to separate/delete
2. Separate/delete them
3. Export NIF
4. Try to load it into NIFSkope or back into Outfit Studio
5. See that there's no uv map data anymore

![image](https://user-images.githubusercontent.com/52472195/80079176-5d347280-8569-11ea-8c05-dc7a67c55b8f.png)

**Comment by ousnius** [comment]
This is already fixed for 5.0.6.
