### ISSUE TITLE
Expand selection options in UV edit mode.

### ISSUE THREAD

**Issue by GrafPanzer** [ousnius/BodySlide-and-Outfit-Studio#294]
In the UV edit window, the user can currently only select UV vertices via box draw select, so cannot select a single vertex or select an entire vertex group when UV maps overlap with identically placed vertices.  There is also no ability to deselect without clearing the entire selection.  

Adding these features would make Outfit Studio superior to NifSkope for casual UV editing, and would permit better UV editing without having to export .nifs from the project.

**Comment by ousnius** [comment]
To-Do:
- Add holding ALT to remove from current selection
- Add "Invert Selection" action
- Add tool to add a single vertex to the selection
- Add "Select More/Less" actions like with the mask brush
- Suggestion by another user: relax/smooth UVs

**Comment by ousnius** [comment]
1.) 15942ff
2.) bc087ff
3.) c01399c
4.) 95ce13b

**Comment by ousnius** [comment]
The UV relax brush of Blender uses Laplacian and HC algorithms for some basic relaxing/smoothing functionality, but it's not a true stretch minimizer. Will think about it again in the future.
