### ISSUE TITLE
Mask off sections before vertex colors

### ISSUE THREAD

**Issue by munkyspunk** [ousnius/BodySlide-and-Outfit-Studio#295]
I have been using OS to do vertex colors a lot lately. Sometimes I have to try a few different shades of a given color before it looks right in game. Sometimes I only need to color certain vertices in an element and it requires careful cursor movement around hi poly density areas. 

I'd like to apply a mask to the element as usual, switch over to the color tab, and be able to paint only the unmasked vertices.

**Comment by ousnius** [comment]
@munkyspunk Right now this isn't possible to implement since the color brush uses the same data under the hood as the mask brush (you can only have one applied).

Possibly you have a mesh where enabling "Edit Connected Only" in the tool- or menubar can help?

**Comment by ousnius** [comment]
This has been possible for quite a while already now.

**Comment by munkyspunk** [comment]
Check the dates on these, this request is from years and years ago, before
it was possible - at least that's what you told me at the time.

**Comment by ousnius** [comment]
I know! I closed the issue because it was still open. The comment wasn't directed at you, it was just for information. :)

**Comment by munkyspunk** [comment]
Fair enough.

Either way, thank for all you do for the community.
