### ISSUE TITLE
(SE) Weight Mismatch Between Body and Hand Meshes

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#301]
**Description**
The bone weights at the seam between the body and hand meshes do not match. This causes small gaps to appear between the two meshes depending on the rotation and translation of the bones. It is most noticeable in first person, but can be seen at any point if the camera is close enough to the wrist.

I've attached an image of the Forearm bone which is the worst offender. You can see the color mismatch representing the different weights. The values of those weights is also clearly indicated in the image. This could probably be most easily fixed by setting the body mesh as a reference and copying the weights to the hands with a max target of 1 and a range of 0.1 or other small number. But you might have a more professional way of fixing the weights you'd prefer to use.

EDIT: Using Outfit Studio 5.0.7 and CBBE SE 1.5.7

![HandWrist Forearm Weight Issues](https://user-images.githubusercontent.com/11934466/87200105-b9797980-c2b0-11ea-9d73-3d6ecb7d4faf.png)

**Comment by ousnius** [comment]
This is fixed for when CBBE SE 1.5.8 comes out.
