### ISSUE TITLE
Groups Manager: Duplicating and Renaming

### ISSUE THREAD

**Issue by erri120** [ousnius/BodySlide-and-Outfit-Studio#304]
It takes way too long manually duplicating and renaming a group. You often need at least 2 groups: one for the master group and one for the current outfit. Having a simple duplicate and rename option would help speed this process up tremendously.

**Comment by ousnius** [comment]
@erri120 Duplication is possible by loading a group .xml file and then using the "Save As" function to save it under a different name. However, renaming of a group in the left list of the group manager dialog isn't possible right now, I will think of adding this.
