### ISSUE TITLE
Mesh morph distortion on male character.

### ISSUE THREAD

**Issue by isshininu** [ousnius/BodySlide-and-Outfit-Studio#308]
After using Outfit Studio for creating slider with _0/_1 body shapes and conforming outfit for bigger shape (_1), I usually make more accurate _1 mesh or fix existing output in 3ds max program. Just export NIF from 3ds max copy & paste over (paste over mesh created in Outfit Studio).

So, the problem is strange, but after using 3ds max nifs for fixing Outfit Studio output clothes on male body became sometimes distorted on a weight range 0.40-0.70 (most visible on this diapazone, but occurs on every weight except 0 and 1).
https://imgur.com/nobe4DD
This is not happens when female character wear those clothes.
https://imgur.com/LYVE7U3
Problem also does not exist in Special Edition after using SSE NIF Optimizer.
Problem is not visible in Outfit Studio (when creating slider with _1 shape datas, it deforms in Outfit Studio correctly). Only game is affected.

It is not possible to backport SSE optimized mesh back to Oldrim, because problem persist. Problem seems to be solvable by making _1 version of outfit solely in Outfit Studio without using any other programs.

**Comment by ousnius** [comment]
It's probably a difference in the weights or skin partition. It's not an Outfit Studio issue so there's nothing I can do.

**Comment by isshininu** [comment]
> It's probably a difference in the weights or skin partition.

Mesh is literally the same.

>It's not an Outfit Studio issue so there's nothing I can do.

Well, I wish I knew
