### ISSUE TITLE
BodySlide hangs when a preview window opens maximized on non-primary display

### ISSUE THREAD

**Issue by DaCoolX** [ousnius/BodySlide-and-Outfit-Studio#310]
**Description**
The position and size is remembered for the preview window. If it is closed in a maximized state on a secondary display (i.e. not the primary one) and you try to open the preview window again, the preview window is created but nothing renders, and Bodyslide freezes with a 100% load on a single CPU core.

**How to reproduce**
1. Open the preview window
2. Drag it to non-primary monitor
3. Maximise it on non-primary monitor
4. Close the preview window while it is maximized
5. Open it again
6. "App not responding"

Tested on FO4 with Bodyslide and CBBE only
OS is Win 10 x64 1909

**Comment by ousnius** [comment]
@DaCoolX I don't have the issue. Are you on an Intel, AMD or NVIDIA chip? Does your machine have multiple graphics chips? Are your drivers up-to-date? Do you run something like G-Sync or the like?

**Comment by DaCoolX** [comment]
AMD Vega 64 with Radeon 20.4.2, most up-to-date as of now.
Onboard Intel graphics is disabled.
Let me try without Freesync.
Edit: Freesync on or off has no effect.

**Comment by DaCoolX** [comment]
Oh wait, the in-driver updater was buggy. Let me update Radeon and come back to you.

**Comment by ousnius** [comment]
And it works if it's re-opened on the primary monitor instead? Can you try disabling "BSA Textures" in the BodySlide settings?

**Comment by DaCoolX** [comment]
20.8.3 Radeon here, sadly no change.
BSA texture toggle doesn't affect the outcome, still hangs.

Yes, if it tries to open maximised on the primary monitor, it works, weirdly enough.
Which is coincidentally the only fast workaround I have to get it unstuck, disable secondary and open the preview window on the primary.

**Comment by ousnius** [comment]
Then I'm not really sure what to do or how to debug it. It might be an AMD driver thing. Instead of disabling your secondary monitor, you can reset the window position/size/state in the BodySlide config XML file.

**Comment by DaCoolX** [comment]
I have Win10 update 2004 on the way, not hopeful but hey let's see what happens.

If it is necessary I will have a stab at it.

**Comment by DaCoolX** [comment]
I took a stab at it and got it to compile and run it though I could use some help. If you could lend a hand I would appreciate it greatly. I'm on your discord if you want to get in touch quickly.

**Comment by ousnius** [comment]
Potentially related to https://trac.wxwidgets.org/ticket/18532
