### ISSUE TITLE
[NIF library] Access out of bounds in NiSkinPartition when saving optimized mesh 

### ISSUE THREAD

**Issue by Guekka** [ousnius/BodySlide-and-Outfit-Studio#314]
**Description**
When saving the [attached mesh](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/5259768/in.zip) after having optimized it, an access out of bounds happens in [NiSkinPartition::Put at line 374](https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/dev/lib/NIF/Skin.cpp#L374)
This is caused by ``numTriangles`` being larger than ``trueTriangles.size()``.
**It only happens when ``OptOptions.mandatoryOnly`` is ``true``**

*Note:* If you don't feel like fixing this, it's okay. I'm the only using ``mandatoryOnly`` anyway

**How to reproduce**
```cpp
int main() {
    NifFile nif;
    nif.Load("in.nif");

    NiVersion target = nif.GetHeader().GetVersion();
    target.SetFile(NiFileVersion::V20_2_0_7);
    target.SetUser(12);
    target.SetStream(100);

    OptOptions optOptions;
    optOptions.targetVersion = target;
    optOptions.headParts = false;
    optOptions.removeParallax = false;
    optOptions.mandatoryOnly = true;

    nif.OptimizeFor(optOptions);
    //Happens in Save
    nif.Save("out.nif");

    return 0;
}
```

**Workaround:**
I use the following workaround, but obviously, it would be better to fix the root cause
```cpp
            if (partitions[p].numTriangles > partitions[p].trueTriangles.size())
                throw std::runtime_error(
                    "True triangles count was smaller than numTriangles in partition: "
                    + std::to_string(p));
```

**Comment by Guekka** [comment]
Actually, this triggers way more often than expected. ``mandatoryOnly`` might be completely broken
I disabled it for now

**Comment by ousnius** [comment]
@Guekka 
The "needsOpt" check in OptimizeFor (which only runs ``continue;`` if ``mandatoryOnly`` is on) might break any NIF that it runs the continue on, since half of the shapes might be optimized and the other half won't be. You need to either optimize all shapes of a NIF or none.

```cpp
if (!needsOpt)
	continue;
```

**Comment by Guekka** [comment]
@ousnius Oh, it's not possible to only optimize some shapes? My bad, this explains it. I'll submit a PR if you want

**Comment by ousnius** [comment]
@Guekka Feel free to, however I could also just remove the mandatoryOnly code and you could do the optimization check locally as part of your code.

**Comment by Guekka** [comment]
Removing it is probably the best option. Thanks for your help
