### ISSUE TITLE
Import multiple files with command line

### ISSUE THREAD

**Issue by awlayton** [ousnius/BodySlide-and-Outfit-Studio#315]
**What is it that you want to do that isn't currently possible?**
Import multiple files to outfit studio from command line.

Right now `OutfitStudio.exe file1.nif file2.nif file3.nif ...` only imports the first file and ignores the rest.

**Request the feature**

Please make it so all the files supplied by command line are imported.

**Comment by ousnius** [comment]
Added that and OBJ/FBX from command line for the next version.
