### ISSUE TITLE
Crash upon starting Batch Build

### ISSUE THREAD

**Issue by CannabisLector** [ousnius/BodySlide-and-Outfit-Studio#317]
Not sure what is causing it, but whenever I try to batch build a body in BodySlide, it causes my entire PC to freeze up to the point where I have to manually restart my pc by the plug since I can't even access the toolbar or Task Manager in anyway shape or form. I've removed CBBE and reinstalled BodySlide but it still persists. If anyone can help me out here, it would be much appreciated.

**Comment by ousnius** [comment]
@CannabisLector This crash only happens when using MO. Please try it without MO.

**Comment by ghost** [comment]
This does not 'only occur with MO' I've got the same problem with vortex. Fo4 fusion girl and body talk batch builds.

My taskbar performance graph still functions, so I can see when it's finished, but it never recovers, and I can't mouse interact with anything on screen. Keyboard works, but nothing will alt tab. Screen does not update.
I can see it's done working, but I can't see if there is a dialogue question or anything when it is.

To get out of it:
Win+r type cmd enter
Type shutdown /l enter (l for logout r for restart)
That will log you off and kill this uncontrollable window handle.

Batch build the same thing again, processor usage remains idle, still locks up the screen. kill bodyslide with a homemade program, still locked up. Kill vortex, still locked up. Kill explorer, and it's over, nothing you can do now but hard reset. Can't bring up run any more.

Edit: a minute or two after I killed explorer, explorer restarted itself, not locked up.

**Comment by ghost** [comment]
Update, I click batch build, everything is checked. Click start, your screen is locked up, I killed explorer and it took 3 minutes to come back.

And I can complete the build from Choose output set.

7 minutes later it's locked up again. All I did was try to Google something.
