### ISSUE TITLE
Exporting .nif yields incorrect weight paint

### ISSUE THREAD

**Issue by Astolf20377** [ousnius/BodySlide-and-Outfit-Studio#319]
**Description**
I weight paint part of my armor to be blue related to pelvis bone. Yet when I export as nif, that part becomes red again.
I tried the same with exporting as fbx, and this does not happen.
Is this a bug?

**How to reproduce**
1. Paint a part of my mesh blue.
2. Export as Nif.
3. Load the nif into OS.
4. View the rig. It becomes red again.

Before Export
![Blue](https://user-images.githubusercontent.com/60375325/97770610-d099eb00-1b6f-11eb-9056-160810864332.PNG)

After Export and load into OS again.
![Red](https://user-images.githubusercontent.com/60375325/97770612-d2fc4500-1b6f-11eb-9ca3-d1339fdf2c1a.PNG)

If you wish I can possibly provide the mesh / OS file.

**Comment by Astolf20377** [comment]
This is getting really strange!
If I paint the whole mesh blue with regards to pelvis bone and export, the whole leg except this region becomes blue, but for some reason this region remains red!

**Comment by Astolf20377** [comment]
No matter which bone weight bone I paint this area with respect to, it will always turn out to be red. 
I have no clue what is causing this. Guess I may need to try another means to weight paint it.

**Comment by Astolf20377** [comment]
Is this related to the weight normalization?

**Comment by ousnius** [comment]
Yes weight normalization. This sounds like normal behavior to me. When you paint the pelvis bone blue, but it's the only thing affecting that area, it will become normalized to 1.0 (red) on export. You may try the live normalization checkbox to the right.

**Comment by Astolf20377** [comment]
So, the way to solve it, is to make a few more bones affect that area?

**Comment by ousnius** [comment]
The area becoming fully assigned to the pelvis bone isn't an error as long as it's the only bone there. You should just try it in-game.

**Comment by Astolf20377** [comment]
Yeah but then that metal plate distorted hugely as my character sneak, jump or run. That pelvis plate is supposed to stay in place. Perhaps that is my own design error...
Anyway it seems assigning different bones to it works. So thanks a lot!
Hopefully I can solve the distortion too.

**Comment by Astolf20377** [comment]
Btw you can safely close the issue.

**Comment by ousnius** [comment]
Yes, you need a spine bone then.
