### ISSUE TITLE
Shape shader properties transfer

### ISSUE THREAD

**Issue by gt9797** [ousnius/BodySlide-and-Outfit-Studio#325]
Outfit Studio Request for an option to transfer Shape Properties from one mesh to another. (Specifically the Shader tab and Shape Textures). [https://i.imgur.com/6Lc94Lb.png](https://i.imgur.com/6Lc94Lb.png)

The reason I am requesting this is due to the amount of times I will import/export a mesh as an .obj between blender and OS. I will often make a small change in blender, whether it be a vertex order change or vertex count change and then reimport to OS to see how the change effects the body conformation on some of the body sliders. 

This feature would save me so much time.

**Comment by ousnius** [comment]
Added.
