### ISSUE TITLE
Feature Request: Fallout 76 mesh support

### ISSUE THREAD

**Issue by GrafPanzer** [ousnius/BodySlide-and-Outfit-Studio#326]
Issue:  Outfit Studio currently doesn't support Fallout 76 .nif formats.  The mod maker and user communities for FO76 are smaller than for Bethesda's single-player games, and Bethesda doesn't explicitly support FO76 modding, but it is still possible to make and use mods for FO76, and there is a demand.  Currently, FO4-formatted meshes work in FO76 with limitations (FO4 cloth physics reportedly doesn't work, for example, and FO76's texture formats are different).  FO4 outfits that also appear in FO76 can be ported, but FO76-exclusive outfits cannot be readily modded.  Because of this, FO76 modders have be unable to create game-wide body and outfit replacers like CBBE, and must stick to body models using vanilla-like UV maps.

Request:  Add Outfit Studio support to open, edit, export, and save FO76-formatted meshes.

**Comment by ousnius** [comment]
Outfit Studio will only have explicit support for games where modding is officially supported by the developer. For a game like FO76 in multiplayer this is currently not the case. I don't grant permission to port assets of CBBE to FO76 either as of now.

This has multiple reasons; legal and philosophical and to prevent the wide majority of people from being able to cheat (editing meshes and stuff) just a tiny bit more.

**Comment by GrafPanzer** [comment]
(Sorry for the slow reply here; I just noticed on Discord that you answered this.) Thanks, that makes sense. Hana had previously said you didn't support FO76, but I thought I'd at least ask. I didn't plan to port CBBE to FO76, but wasn't aware it'd be an issue. Thanks for the clarification.
