### ISSUE TITLE
Bodyslide completely freezes up explorer when processing an absurd amount of outfits

### ISSUE THREAD

**Issue by BurgerLUA** [ousnius/BodySlide-and-Outfit-Studio#327]
**Description**
Clicking "batch build" without any outfit or group filters causes the computer to crash. Note that it doesn't freeze during it building all the outfits, rather it freezes before you can select the conflicting files. CPU usage maxes out during this period and setting the affinity to use only one core and the priority to low does not prevent a crash.

**How to reproduce**
1. Install an absurd amount of large Bodyslide packs.
2. With no filters, select "Batch Build"
3. PC freezes up completely. Explorer freezes. Only salvation is a physical hard reset.

**Comment by ousnius** [comment]
@BurgerLUA This is an issue that's caused by MO.
