### ISSUE TITLE
CTD induced by incorrect sorted blocks

### ISSUE THREAD

**Issue by testiger2** [ousnius/BodySlide-and-Outfit-Studio#328]
Just wanted to report an issue with the new block ordering from
https://github.com/ousnius/BodySlide-and-Outfit-Studio/issues/316

I found out that Collision blocks get ordered/indexed in the reverse order they are supposed to.
Normally you would have something like this: (4)bhkCollisionObject->(3)bhkRigidBody->(2)bhkBoxShape

The new code orders them like this ;  (2)bhkCollisionObject->(3)bhkRigidBody->(4)bhkBoxShape
This behavior reliably leads to CTD's in Oldrim (did not test SSE or FO)

Was able to reproduce it by running a vanilla mesh (gnd mesh with collision) through some test code:

```
#include "NifFile.h"

int main(int argc, char* const argv[])
{
	char* filename = argv[1];
	if (!filename) return 1;

	NifFile nif;
	nif.Load(filename);

	nif.Save(filename);
	std::cout << "Done" << std::endl;
	return 0;
}
```

Testing procedure i used:
- Run mesh through code above
- Open Game 
- Drop item with mesh -> CTD
- Open broken mesh in Nifskope, use sanitize->reorder, save
- Item no longer causes CTD

I have no clue wether other blocktypes are affected as well i just stumpbled upon the Collisions when i made some meshes.

**Comment by ousnius** [comment]
This was fixed before the next release (the bug was not present in any Nexus release yet). Thanks for the report.
