### ISSUE TITLE
FBX Import Weight Issue on limbs

### ISSUE THREAD

**Issue by WarGreySama** [ousnius/BodySlide-and-Outfit-Studio#331]
A prerigged fbx model with right bone names if imported to Outfit Studio and exported as nif,
weights on limbs don't work at all, only the vertical bones from pelvis spine0, spine1 and spine2 
neck (if there is), head bone works properly. Arm bones and leg bones won't work at all. It is quite weird that if I open model with NifSkope I notice that all the bones that deform legs and arms are put in the center between model's feet (where root bones usually are if models have any). I am a Blender 2.8 user and as such your program is my only hope as I work with rather complex models that is pain to weight paint vertex by vertex and copying weight to them from vanilla models are prone to errors too often. (Example is WarGreymon from Digimon Links or Doom Slayer from Doom Eternal - (which also have unique parts and their bodyshapes although humanoid quite different from Skyrim's human body shape) I make custom race/weapon mods for friends, they aren't public mods btw
.

Am I doing something wrong? Hope there is a fix/workaround for this.

**Comment by ousnius** [comment]
The FBX import of Outfit Studio only aligns bones correctly if a matching reference skeleton (and reference shape, like a CBBE body in the case of Skyrim/FO4) is loaded into the program before loading the FBX.

**Comment by WarGreySama** [comment]
I see, but that still doesn't work because I painstakingly rigged the same models manually in OutfitStudio only to fix some weights later in Blender. So I keep my manually rigged models intact and as reference, I also export them as fbx to fix weights in Blender from which I export as fbx again to import back to Outfit Studio but same problem persists.

**Comment by ousnius** [comment]
You need a skeleton.nif for your rig that you can assign to Outfit Studio in the settings.

**Comment by WarGreySama** [comment]
Ah thanks a lot. Sorry for bothering you.
