### ISSUE TITLE
FBX Export Broken

### ISSUE THREAD

**Issue by GreenGhost21** [ousnius/BodySlide-and-Outfit-Studio#336]
**Description**
Exporting shapes to FBX results in a _very_ broken output.

This is how the CBBE NeverNude body for Fallout 4 looks in BodySlide (Front View, non-perspective):
![image](https://user-images.githubusercontent.com/6434946/107718503-e9e02680-6c8a-11eb-8220-e3af2cb404f2.png)

And this is how it looks in the official Autodesk FBX Review tool: 
![image](https://user-images.githubusercontent.com/6434946/107718583-1b58f200-6c8b-11eb-880b-9cb1320dfbe9.png)

I realize this has already been reported in #220. However, in that issue, the person who originally reported the bug wrote it off as a Blender import bug and closed the issue. I'm fairly certain that, given that the official Autodesk viewer also imports it in a broken manner, it's an issue not with the programs' import methods, but with BodySlide's export of meshes to FBX. 

**How to reproduce**
1. Load an outfit/mesh
2. Export mesh or meshes to FBX
3. View model in a program, preferably one that supports rigged meshes.

**Comment by ousnius** [comment]
@GreenGhost21 This is fixed for the next version.
