### ISSUE TITLE
Outfit Studio 5: Transform Tool works differently from previous version

### ISSUE THREAD

**Issue by vadsonbof** [ousnius/BodySlide-and-Outfit-Studio#338]
**Description**
I came across differences in the work of "Transform Tool" in Outfit Studio between versions 4 and 5 (I compared versions 4.5 and 5.2, 5.3).

Previously after I import outfit with different bones position I could translate it as a whole to match the reference. And it worked fine.

When I do the same in the newest version, I've got some ugly picture in nifscope and 3d max. The mesh and its bones seems to move differently now (my diletant speculations). And I haven't found a way to match the model and reference in new version. I have to use version 4 for this operation.

**How to reproduce**
1. Create new project in Outfit Studio with any reference.
2. Load outfit from some special model with different bones coordinates. Like this
[cuirass_0.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/6074436/cuirass_0.zip)
We've got something like that
![screen_1](https://user-images.githubusercontent.com/16064966/109773563-2c10de00-7c21-11eb-9fb8-6940721d9ead.png)
4. Use transform tool to match outfit with reference.
![screen_2](https://user-images.githubusercontent.com/16064966/109774366-1223cb00-7c22-11eb-9ca2-8528ee3ba690.png)
5. Save project with reference copy.
6. Open project .nif file in NifScope.
![screen_3](https://user-images.githubusercontent.com/16064966/109774485-354e7a80-7c22-11eb-9985-5ad3855e8ba7.png)

**Comment by ousnius** [comment]
@vadsonbof Not a bug, you need to use "Edit -> Reset Transforms" and if it's still needed, move it afterwards.

**Comment by vadsonbof** [comment]
@ousnius Maybe I'm missing something, but it doesn't work for me. I used Reset Transforms after step 2, but nothing changed in the viewport or after saving the project.

**Comment by ousnius** [comment]
@vadsonbof After loading the mesh and using Reset Transforms, did you then align it correctly using the transform tool before exporting it?

**Comment by vadsonbof** [comment]
@ousnius Yeah, I repeated all the steps from the first post. I even loaded outfit in the game to see the same picture as in NifScope.

However If I don't align the mesh and the reference (regardless using Reset Transforms), I've got a .nif file that appears to be valid. But in this case, I have to endure "mesh shift" in the Outfit Studio viewport, which obviously doesn't allow to work with sliders normally.

Again, in version 4, I could align the parts and get the same result in both the viewport and the .nif file of the saved project.

**Comment by ousnius** [comment]
@vadsonbof It's not something that can be fixed because the bone transforms of the outfit aren't correct. The workaround is the following.

1. "Edit -> Remove Skinning"
2. Move the shapes to the right place
3. Reload a reference body
4. Copy bone weights
5. Set partition slots
