### ISSUE TITLE
Executable file path causes missing UI bitmap icons

### ISSUE THREAD

**Issue by juhvv** [ousnius/BodySlide-and-Outfit-Studio#341]
**Description**
It appears that if the BodySlide/Outfit Studio executable is located in a directory which has a "#" in its absolute file path, the UI buttons' bitmap icons are not visible. Here's a log file demonstrating this issue:
[Log_OS.txt](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/6216147/Log_OS.txt)

**How to reproduce**
1. Place the BodySlide/Outfit Studio executable to a directory that has a "#" in its name (e.g. "folder1#").
2. Run either one of the programs.
3. Bitmap icons are not visible.

**Comment by ousnius** [comment]
@juhvv This seems to be a bug in the filesystem of wxWidgets where it traverses the path (looking for multiple locations or URLs).
`filesys.cpp: wxString wxFileSystemHandler::GetRightLocation(const wxString& location)`
There's nothing I can do on this side, it needs to be fixed in wxWidgets.

**Comment by ousnius** [comment]
See https://trac.wxwidgets.org/ticket/19142
