### ISSUE TITLE
Batch Partition Slot/Type Alteration

### ISSUE THREAD

**Issue by MalNebiros** [ousnius/BodySlide-and-Outfit-Studio#344]
For compatibility reasons between different mods it can be necessary to update the slots used for various entities such that they match a given format.

A UI to enter a set of slots to swap and associated filtering criteria in order to be able to point it at a set of files and make the adjustments in one go.

**Comment by MalNebiros** [comment]
With a little guidance as to which classes I need to check for the mesh tree view and the associated partition view and list I can probably get this working myself. I'm unsure if this would fit bet as a tool within Outfit Studio or as a tool invoked from bodyslide.

**Comment by ousnius** [comment]
@rowan341 Since this is supposed to operate on multiple files outside of the Outfit Studio project, it would be best fit in a completely separate tool utilizing nifly (the NIF library used here).

Much like the SSE NIF Optimizer - I have such a quickly hacked together tool for personal use for when I need to do something specific to a few files, but it's not something that can be released in its state. Maybe I can come up with something like that in the future.

**Comment by MalNebiros** [comment]
That's roughly what I expected, single responsibility principle and so on. I may have a look into it this weekend. Is there anywhere better to start looking at it than going backwards from the tests?

**Comment by ousnius** [comment]
> That's roughly what I expected, single responsibility principle and so on. I may have a look into it this weekend. Is there anywhere better to start looking at it than going backwards from the tests?

Are you referring to using nifly? It's only recently been split into its own repo and refactored a bit. There's no usage info/API documentation/examples yet, but it's on my todo list.

The problem with editing/merging/splitting skin partitions (for changing or merging slots), is that a lot of data in the NIF format relies on it and needs to be changed/merged to fit the new partition count and triangle assignment to them. You can change partitions with just nifly, but most of the real logic required for reassigning triangles and vertex data and moving stuff around is still located in the Outfit Studio code (CreatePartitionTree and ApplyPartitions in OutfitStudio.cpp).

**Comment by MalNebiros** [comment]
I was indeed referring to nifly.

Ah okay, thanks for the warning on the structure. So it'd be a case of using nifly to do the reassignment then calling the relevant outfit studio methods to do the rest of the required processing?

I may still have a look at it but it is starting to sound a little more complex hoped although possibly still less so than anticipated.
