### ISSUE TITLE
Batch build from cli

### ISSUE THREAD

**Issue by Osmosis-Wrench** [ousnius/BodySlide-and-Outfit-Studio#348]
**What is it that you want to do that isn't currently possible?**
... Currently you can build a body group, but you don't seem to be able to batch build all outfits from cli.

**Request the feature**
... Ideally this would look something like `"Bodyslide x64.exe" /gbuild "CBBE Body" /p "CBBE Curvy" /batchbuild`
And would build all outfits at once. If conflicts arise just show the options menu like is done with the body files already.

**Comment by ousnius** [comment]
@Osmosis-Wrench Use the group "CBBE" for batch building, all CBBE outfits should be part of that group. If they're not, they should be added to it.

**Comment by ousnius** [comment]
@Osmosis-Wrench Let me know if this is enough for you or if you still need something new.

**Comment by Osmosis-Wrench** [comment]
That works, now that I understand how they are built. Only thing that is kinda weird is that the auto mode doesn't seem to obey the Mo2 output rules when called via Mo2. Not sure if that is something you can fix however, might be an mo2 issue.

If you can do something about that, it would be amazing. But if not feel free to close the issue 😄 

Thanks for your help!

**Comment by ousnius** [comment]
From BodySlide's side, there's no difference between batch building from the GUI and from the command-line. Maybe MO's hooks aren't fully initialized yet? Not sure, but you might have to go to the MO devs for that.
