### ISSUE TITLE
FBX import destroying uv's

### ISSUE THREAD

**Issue by BaelZ** [ousnius/BodySlide-and-Outfit-Studio#349]
**Description**
When I try to import an FBX file from maya 2019, Zbrush  or any softwares I use, the uv's are destroyed. I also tried to import FBX asci/binary for 2019,2018 and older dates : still have the issue. Also importing in obj doesn't work because of the polygonal limit.

**How to reproduce**
Simply importing the model as new project or loading it as outfit.

[FO4Newbody.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/6416279/FO4Newbody.zip)

**Comment by ousnius** [comment]
@BaelZ The NIF format doesn't support vertices with more than one texture coordinate (UV). You need to split the mesh on its UV seams to be able to import it correctly. And yes, it's very close to or over the vertex/triangle limit for the game.

**Comment by BaelZ** [comment]
@ousnius  So I need to cut for exemple, at the hands, head , belly etc, is that right ? Isn't it going to create very visible seams in game ?

**Comment by ousnius** [comment]
@BaelZ Yes, those are examples.

No, Skyrim uses model space normal maps for everything that has skin (head, hands, feet, body, ...). Due to this, they won't have any shading seams as long as the vertices and weights are matching up.
