### ISSUE TITLE
Transform tool with non-zero sliders and remember last used tool

### ISSUE THREAD

**Issue by GrafPanzer** [ousnius/BodySlide-and-Outfit-Studio#363]
Trying to edit a mesh with most tools while sliders are set to a non-zero value calls a dialog prompting the user to set sliders to zero.  However, it is possible to set slider(s) to a non-zero value then edit the mesh with the transform tool.  This does not call a dialog, but results in the slider value becoming permanent.  If you Ctrl+Z to undo, the slider resets to zero but the mesh doesn't change (it takes on the set value as the base shape).  Likewise if you set the slider back to zero.  It is possible to undo this by hitting Ctrl+Z to undo the transform tool action, then set the slider to the negative of the set value, then use the transform tool again, and again use Ctrl+Z to undo the action.

Here are two other OS behaviors that are not exactly bugs, but are nuisances for me:
1.  X-mirror is on by default for all tools.  Often when I am masking, moving, or inflating, and I am zoomed in to look closely at what I'm doing, I'll later find that every move was being x-mirrored and I didn't want it to be.   I suggest making x-mirror off by default.
2. Inflate is the default tool.  When I switch from the Meshes tab to another tab, and then switch back, the tool resets to Inflate.  I often will be using the Mask tool, switch to another tab, and then accidentally inflate the mesh when I switch back.  I suggest making Mask the default tool (since it doesn't make any actual changes to the mesh) and revert to the last selected tool when switching back to the Meshes tab.

**Comment by ousnius** [comment]
@GrafPanzer
Being able to use the transform tool while any slider is at a non-zero value (and not in edit mode) is a bug. I'll have to fix that one.

1. X-mirror has to stay on by default, as that's what's almost always needed (initially) when working with outfits. However, the behavior here changed for the worse recently and maybe it will be fine for you again after #340 is fixed.
2. I prefer the inflate brush being the initial default tool. However, remembering which tool was used before entering the bones/other tabs is a good idea, and it will probably solve your issue.

Summary:
- Prevent using transform tool with sliders at non-zero values
- Fix #340
- Remember last used tool from the meshes tab when going back to it from another tab

**Comment by GrafPanzer** [comment]
Thanks!

**Comment by GrafPanzer** [comment]
Here's a bug related to (2) that I noticed last night.  The View shortcut keys (Shift+1,2,3,4,5) seem to be connected to the Mask, Inflate, Deflate, etc. tools.  When I use those shortcuts to set the view, they also sometimes change the selected tool.  It's not clear whether they're tabbing through the tools, or selecting specific tools.  The behavior isn't consistent.  In any case, the View shortcuts shouldn't change which tool is selected.

**Comment by ousnius** [comment]
@GrafPanzer All of this should be fixed now.

**Comment by GrafPanzer** [comment]
Thanks!  That's awesome!
