### ISSUE TITLE
Zapping Doesn't Delete Shared Linked Properties

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#370]
Currently when a shape is zapped the entire branch of that shape and all it's properties is deleted.
If that shape is using a shared TextureSet (ie. there is a single Texture Set property in the nif that is shared among multiple shapes), that shared property will be deleted and all shapes that had a dependency on the texture set will lose their assigned textures.
...

Often shared texture sets are used as a minor optimization to meshes to reduce size, and also make it so that texture paths only need to be changed in one place in order to update all affected shapes in a mesh. Can you please make it so that shared properties are not deleted when a shape is zapped?
...

**Comment by AdamVezina** [comment]
This issue won't show up in Outfit Studio because the mesh is loaded with all shapes intact. The issue only occurs in Bodyslide/in-game after the transforms are applied to the mesh.

**Comment by ousnius** [comment]
@AdamVezina Nobody cared about this or reported this in over 6 years until a few days ago (and it's always been like this). Sharing shaders or texture sets among multiple shapes is invalid (there's not a single Bethesda file that does it and in FO4 it can even cause crashes).

However, it's already been changed in the 5.4.1 release so the issue shouldn't exist there. Can you confirm it's fixed or still exists in 5.4.1?

**Comment by AdamVezina** [comment]
Confirmed "fixed" in 5.4.1. 
Sorry ousnius, seems I'm always a version behind by a few days.

I've encountered this years and years ago in LE, but didn't have enough of an understanding of how nifs worked then in order to realize what was going on. Thank you for changing the behaviour, this will save me a lot of time.
