### ISSUE TITLE
Bodyslide Builds Default Mesh Only Unless Preview Open

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#371]
**Description**
I know this would have started with v5.4.0 when the optimization was made so slider data is only loaded when the preview window is open. It's still present in v5.4.1.

The issue is that unless the preview window is open when you build outfits they will only build as the default source mesh. No zaps, no slider morphs. I can't speak for the entire user base, but I don't think it's uncommon that a person just opens Bodyslide, selects an outfit/preset and clicks Build without previewing. If they have a preset they always use they wouldn't need to see what it's going to look like. 

Oddly enough Batch Build seems to generate the meshes as expected. So maybe hooking slider data to also load with the regular Build button was just missed by accident?

**How to reproduce**
1. Open Bodyslide.
2. Select a preset that isn't "-Zeroed Sliders-"
3. Close Bodyslide so the preset choice will load as the default
4. Re-open Bodyslide
5. Press the Build button
6. Open the mesh(es) that were built in a model viewer.
7. You'll see that none of the settings in your preset were applied.

**Comment by AdamVezina** [comment]
Please don't whack me for opening another issue so soon V_V

**Comment by ousnius** [comment]
Thanks, fixed for 5.4.2.
