### ISSUE TITLE
(FO4) Applying changes on segment is not working properly

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#378]
**Description**
Segment assignment data goes wrong when you add more segment(s) and apply it.
When the last segment is empty, it gets filled with the last data of the segment o
n the upper of the list when you press apply.
this is annoying when you trying to combining shapes using copy geometry because the moment you add segment(s) and press apply, the data gets messed up.

**How to reproduce**
1. Load any mesh which has segment(s)
![11](https://user-images.githubusercontent.com/90162452/132147849-c30c0a5b-adce-4783-ac6d-1ac45f25f6b3.png)
2. Add new segment(s) to the list : make sure newly added segment is empty
![22](https://user-images.githubusercontent.com/90162452/132147868-4f717b6e-0687-4104-b9ac-677d771a125d.png)
3. press apply
![33](https://user-images.githubusercontent.com/90162452/132147880-e6fc928f-1a0e-4ddd-b913-06cea9abad25.png)
4. view the result : the segment data which belongs to the upper segment on the list would be transferred to the last segment of the list.

**Comment by sts1skj** [comment]
Hopefully I have fixed this bug in https://github.com/ousnius/nifly/pull/26
