### ISSUE TITLE
I can't change the property settings in the shader tab for Fallout 3/NV.

### ISSUE THREAD

**Issue by Retral-RX** [ousnius/BodySlide-and-Outfit-Studio#381]
I have been experiencing this weird issue since when I updated outfit studio from 5.2.0 to 5.4.0+. Fallout 4 and Skyrim works fine but this problem occurs when I try to edit meshes in Fallout 3 and NV. When I edit the settings in the shader tab (*Mesh in the right menu*> properties>shader tab) It doesn't register my settings. After clicking OK, I reopen the tab to check it. all settings reset to their original value. Even the texture path resetting. Removing and adding functions in the same tab doesn't seem to fix it either. I've checked the results in Nifskope if something has changed. Nope, it doesn't do it. Most of the time I'm having this problem. Hope this information helps.

**Comment by ousnius** [comment]
@Retral-RX Can you attach a NIF file this is happening for you with? I can't reproduce it just yet.

**Comment by Retral-RX** [comment]
@ousnius Of course, just tested this one before the upload. This one is from New Vegas. Although, I doubt it is a mesh-specific problem. I've been experiencing this issue for a while now with a variety of meshes.  I can edit those same meshes without a problem in ver. 5.2.0.

I don't know if you find this information useful but; I'm using the steam version of the games(F3, F4, FNV, Skyrim, Oblivion) on win10. They're located inside program files.

Also, I came across a weird problem while editing Oblivion meshes in OS. I'm gonna post it on a separate topic.

[DMCO Tactical Talon.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/7447554/DMCO.Tactical.Talon.zip)

**Comment by ousnius** [comment]
@Retral-RX I can edit the shader type, texture paths and glossiness properties of the NIF you attached just fine in the released version of 5.4.2. What exactly are the steps you're taking (how do you load the NIF, what shape do you edit and what property, how do you save the NIF)?

**Comment by Retral-RX** [comment]
@ousnius Every game has its own OS with the target game selected for that game. I use the x64 version of the executables.  Since the OS uses the last selected file location for the export process across all Outfit studios regardless of the game, I simply use the drag & drop method to load the mesh. I use it for mostly armor/clothing meshes. If there is not a special case, I export mesh files as nif. I mostly change specular color in the property if the program ever lets me.^^
I recorded the process to give you a better view. Here is the link:
[https://youtu.be/3KYxvKFgF9k](url)
As you can see in the video, I'm trying to edit the very same file I sent you. This time (god bless Todd's soul) it just works... partially lol. Sometimes it doesn't let me change anything, sometimes it works. Whatever it is it is not constant but sure as a thing it is there.^^

**Comment by ousnius** [comment]
@Retral-RX FO3/NV meshes actually don't have a property for "specular strength", that's why that one isn't saving. The other properties like shader type, specular power (glossiness) and specular color are saving fine.

So this isn't a bug, but the field "Specular Strength" should be greyed out for shaders/games that don't support it. Thanks for the report, though.
