### ISSUE TITLE
Working Oblivion meshes become invisible in-game after being exported from Outfit Studio.

### ISSUE THREAD

**Issue by Retral-RX** [ousnius/BodySlide-and-Outfit-Studio#382]
This is an unusual one and specific to Oblivion. As I stated in the title when I load a mesh that is working fine in my game into Outfit Studio, the mesh becomes invisible in-game after the export process. Mesh appears normal in both Nifskope and OS but it is invisible in-game.

To be more specific, I loaded a mesh from a mod I'm already using in-game. I slightly edited clippings and bone weights of some parts. After exporting as nif, it becomes invisible. To narrow it down, I first thought it is something with archive invalidation or simple mesh error but before the process, the same mesh was working fine. Tried it with a couple of other meshes and the result was the same.

I also made a test with Nifskope. I duplicated the original Armor mesh, named the new ones "Armor  A" and "Armor B"( Those 2 are the same files). I loaded Armor A into OS and exported it as nif and overwritten the same file. Then I loaded new Armor A and Armor B in Nifskope separately. I copied specific parts from Armor A and pasted them over B. Then I tested Armor B that has some of the meshes from Armor A in-game. As I expected, the parts from Armor A were invisible. Hope this helps.

**Comment by ousnius** [comment]
@Retral-RX Oblivion NIF editing is pretty much untested, I merely made sure the NIF files look like they're supposed to. I've never launched the game in my life (so far). Can you attach the before and after NIF files so that I can see what might be the issue?

**Comment by Retral-RX** [comment]
@ousnius  Fun thing is that even though I played Fallout and Skyrim numerous times, this is my first Oblivion run.^^ Because of this, the problem I'm experiencing made me think that Oblivion nifs somewhat work differently. It took me a while to figure out what is going on but here we are. :) 

Here are the original files
[HuntersArmour-16078.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/7448952/HuntersArmour-16078.zip)

Link to original mod if you need
[https://www.nexusmods.com/oblivion/mods/16078?tab=files&file_id=22101](url)

These are the files I edited
[HuntersArmouredited.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/7448954/HuntersArmouredited.zip)

In case you need details, the original mod uses Robert's female body. I changed the body with HGEC body, edited the meshes for clipping, and copied new body weights onto armor parts.

**Comment by ousnius** [comment]
@Retral-RX Can you see if any of these two meshes for LHBootsBlack are working (I'm assuming the edited one's you uploaded aren't working)? Or is it only the torso piece that isn't working?

[LHBootsBlack.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/7449386/LHBootsBlack.zip)

**Comment by Retral-RX** [comment]
@ousnius Both files are working fine. Cuirass and Greaves have the most edited ones in OS. Have you also tested them?

**Comment by ousnius** [comment]
@Retral-RX This was very likely related to the order of the blocks (nodes vs. shapes) in the NIF file. I've finally gotten around to installing Oblivion myself and have played around with a few vanilla meshes.

There's since been changes that should hopefully fix the issues you had in the next release, so I'm closing this issue for now.

**Comment by BakaNakama** [comment]
@Retral-RX the skin instance was changed from niskininstance to bsdismemberskininsatce after you exported it. to fix it copy over the original skin instance, and then go into outfit studio and copy over the bone weights from your old edited piece to the new one. hope this helps

**Comment by VKVII** [comment]
Edit (again) because I have experienced this issue with another outfit and it's not about body parts only as I thought.

What I do is to open the exported file in Nifskope, right click on the BSDismemberSkinInstance ---> Block---> Convert ---> NiSkinInstance.
I'm leaving this here in case may be useful for someone else.
Btw I'm so happy you have included Oblivion in BS/OS, it's truly awesome. Thank you!
