### ISSUE TITLE
Batch conflict resolution should be supported in the base UI

### ISSUE THREAD

**Issue by Iloei** [ousnius/BodySlide-and-Outfit-Studio#386]
When I am working in bodyslide, I want to see what nif(s) I would be generating. And, when I have conflicting definitions for a nif, I want to preview the possibilities so that I can pick the one I like best. And, when I make this choice, it should be preserved for batch builds.

This is similar to Issue https://github.com/ousnius/BodySlide-and-Outfit-Studio/issues/350 (partial overlap, but this version is more limited in scope).

**Comment by Iloei** [comment]
Pull request https://github.com/ousnius/BodySlide-and-Outfit-Studio/pull/387 would be a plausible implementation of this concept.

**Comment by ousnius** [comment]
PR #387 merged
