### ISSUE TITLE
Slider data loss during merging geometries

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#390]
**Description**
While using **geometries merging** function, some of slider data disappears.
This seems to happen when **the source shape has sliders which the target shape does not.**

**How to reproduce**
1. load any slider set which is not a full body
![01-1 Arm Add](https://user-images.githubusercontent.com/90162452/145709742-fa688908-5006-4fdd-bce2-eba856894472.png)
 - I used a combat armor's arm part in CBBE Vanilla. Only changed the name and folder of the slider set to test it.
 - Obviously, there is **no leg or butt slider** in this slider set.

2. Add any slider set which contains sliders which previous slider set doesn't have
![02 Leg Added](https://user-images.githubusercontent.com/90162452/145709841-5b7f25ff-d704-4431-af13-ba0703dfca76.png)
 - I added a combat armor's leg part in CBBE Vanilla.
 - Now some **leg/butt sliders are added** in the list below : they are **only applied to the leg part**
 
3. Merge Geometry
![03 Merging](https://user-images.githubusercontent.com/90162452/145709913-b397d573-2a51-4acd-8edc-cee50544708e.png)
 - I copied the shader informations through Nifskope + add segments and copied ssf file data to get them merged
 - **I merged the Leg Part(Source) to the Arm Part(Target)**

4. After Merging
![04 After Merge -1](https://user-images.githubusercontent.com/90162452/145709974-ef08f485-211c-4651-b037-4f82668c04b5.png)
 - Now we have only one mesh in the list. But these leg/butt sliders won't work even in the outfit studio.(And they will be gone if you re-load the slider set)

5. Save the result and run Bodyslide
     ![04-1 Arger Merge On Bodyslide](https://user-images.githubusercontent.com/90162452/145710085-3b1f920e-a81f-49ca-a7f2-e380a7397d71.png)
 - Now you can see **leg and butt sliders are missing.**

**Comment by ousnius** [comment]
@MrAnnonymous00 Thanks for the report, I fixed the issue for the next release.
