### ISSUE TITLE
Automatic custom normals preservation for skin for Fallout New Vegas

### ISSUE THREAD

**Issue by ahzidaljun** [ousnius/BodySlide-and-Outfit-Studio#392]
**What is it that you want to do that isn't currently possible?**
in fallout: new vegas, the [new and most commonly used female body](https://www.nexusmods.com/newvegas/mods/66903?) relies on custom normals on every mesh in order to be seamless (or as close as possible to it) ingame. you can preserve this by manually locking normals under the Shape dropdown, but it has to be done every single time you open a new nif file before you interact with the meshes in any way, since even setting as reference will recalc the normals and make them seam-ful again

the whole thing is a little unreliable as at some point it's easy to forget to do it and you have to regenerate the custom normals via an external tool, which can be time consuming.

**Request the feature**
make it so while F:NV is selected, any mesh with SHADER_SKIN as its Shader Type has locked normals by default

i'm also not 100% sure if smooth seam normals also could influence this, but if it can disrupt custom normals then having that also disabled by default on the same Shader Type criteria would be sensible.

thanks!!

**Comment by ousnius** [comment]
@ahzidaljun There's already a feature for locking specific normals (vertex indices), which is respected by both BodySlide and Outfit Studio. All you need to do is add a "NiIntegersExtraData" block to the body shape in its NIF file as seen in the image.

The array needs to contain the exact vertex indices you want to lock (the neck). You can find the vertex indices by inspecting your shape data in NifSkope or hovering over vertices with a brush in Outfit Studio.

I hope this works well for you. You can keep the NiIntegersExtraData in the file, it shouldn't affect the game.

![image](https://user-images.githubusercontent.com/7034795/147154977-b9b5a5f9-dcd8-4ec5-b85c-b1cc80202dd8.png)
