### ISSUE TITLE
Don't understand Install instructions at All

### ISSUE THREAD

**Issue by pgorbas** [ousnius/BodySlide-and-Outfit-Studio#408]
Don't understand Install instructions at All

>  Mod Organizer
> Download and install the archive to MO like you would do with any other mod and enable it.
> Add a shortcut to the "BodySlide x64.exe" file from the "Data" tab and set it to run from your game's real data folder, NOT the MO mods folder: "<game folder>/Data/CalienteTools/BodySlide" for Skyrim and "<game folder>/Data/Tools/BodySlide" for FO4/others.
> Install any BodySlide addons such as body mods and outfits to MO as well.

First of all "Mod Organizer", as far as I know, doesn't even exist anymore, the current program is Mod Organizer Two or MO2.
Secondly, all this talk of data folder as opposed to "real data folder" is confusing!
A picture is worth a thousand words would apply here.

What I ended up with is:
Target:  "D:\Games\Modding\mods\BodySlide and Outfit Studio\CalienteTools\BodySlide\BodySlide x64.exe"
Start In: "D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data"
![image](https://user-images.githubusercontent.com/11726837/150632450-6184a917-34fb-48f4-8d34-2bd53259a255.png)

> Install any BodySlide addons such as body mods and outfits to MO as well.
What BodySlide addons ?? There are none listed in your file section??

> Target Game
> When running the executable for the first time, the following dialog window will show.
Nope, the Setup dialog never appeared for me and I see no way to bring up a dialog that looks like the one pictured from within the app.
I never see this dialog:
![image](https://user-images.githubusercontent.com/11726837/150633319-86b2c32b-9a94-4f6a-9131-1afeea8c9e00.png)

> Settings
> The settings dialog of the program can be accessed from the main BodySlide window.
These are my best guess, do they look good?  From your image I guessed to ONLY select the Texture files??
![image](https://user-images.githubusercontent.com/11726837/150632706-6683062e-417c-45e6-9bbc-8e7037933f76.png)

> File
> This is the reference skeleton file that Outfit Studio uses to create a list of bones and read bone transforms from.

I don't know where a skeleton file would be, if I have one.  The example file path "res\skeleton_female_sse.nif" makes no sense.  Where is the "res" folder?  If I browse, it opens a file finder pointing at nowhere...  Are you ASSUMING the existence of a dependent file download which you skipped mentioning in you setup?

> Root Node
> The root node name can differ from game to game. It needs to be correctly set up in order for Outfit Studio to know where to start reading the list of bones from.

Another section that makes no sense to me, instead of a "Browse", it offers a dropdown of ambiguous locations I have no idea where they are?
![image](https://user-images.githubusercontent.com/11726837/150633026-f5e89978-922b-4f9d-86f0-63b43e44a4af.png)

### **Note how there is no button in the setting dialog, that brings up anything resembling the Setup Dialog, which I never got.**

I'm a retired software developer with 40 years experience, but to me there appears to be a disconnect between what I see actually happen, and your instructions.

With my setup as observed in the screen shots above, all the dropdown boxes are empty - maybe because the Setup dialog never appeared, and there is no way to bring it up from the Settings page??
![image](https://user-images.githubusercontent.com/11726837/150633263-fc64ccc4-0c29-4796-8080-28fba8ac6254.png)

I would really like to use your tool as it is my understanding this is the way to add a bigger selection of bodies in Skyrim SE so not everyone looks like clones of the same person.

I will keep reading and as a last resort look at a video - I hate youtube videos, they general show 5 minutes of video for something that can be explained better in a few clear lines of text.  

Thanks for creating this tool, I'm sure it is great if I can figure out how to use it!

**Comment by ousnius** [comment]
@pgorbas You missed a crucial point in the instructions which is to make a shortcut to BodySlide from inside of MO2, not a Windows-based shortcut.

Using MO2 it should be aware to you that any external programs you use must be run from inside of MO2, otherwise its virtual file system cannot hook into those external programs (such as BodySlide). The install instructions for MO2 for BodySlide are the same as for any other external tool, so this is not even an issue with BodySlide to begin with.

> First of all "Mod Organizer", as far as I know, doesn't even exist anymore, the current program is Mod Organizer Two or MO2.

The install instructions are the same for MO and MO2, which is why the "2" was left out because it applies to both.

> Install any BodySlide addons such as body mods and outfits to MO as well.
What BodySlide addons ?? There are none listed in your file section??

It's explained in the very line you quoted.
BodySlide addons = body mods and outfits with support for BodySlide.
There's thousands of them on the Nexus, so it doesn't make much sense to link them.
Compatible body mods are in fact linked on the mod page of BodySlide on the Nexus.

You don't need to deal with any of the other settings such as the reference skeleton or root node. Those only apply to Outfit Studio and in 99,9% of cases don't need to be changed. The settings are explained for completeness-sake on the wiki.

Please report installation issues on the mod page instead of the GitHub page, or join my Discord server to receive direct help in a live chat scenario (link is on the mod page and inside the program).

**Comment by pgorbas** [comment]
Closed. With absolutely no explanation about why it is Closed.   Proper documentation is as important as any other step in the software development cycle, and as painstakingly show, the current setup instructions are far from clear.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: ousnius ***@***.***> Date: 1/22/22  3:01 AM  (GMT-07:00) To: ousnius/BodySlide-and-Outfit-Studio ***@***.***> Cc: pgorbas ***@***.***>, Mention ***@***.***> Subject: Re: [ousnius/BodySlide-and-Outfit-Studio] Don't understand Install instructions at All (Issue #408) 
Closed #408.

**Comment by pgorbas** [comment]
Thank you very much to your quick reply.  I shall move my shortcut I put on my desktop to within my steam game directory for Skyrim.  Since I can't have a shortcut to a shortcut on my desktop, I will add the shortcut into my MO2 drop down of executables. I will try this tomorrow.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: ousnius ***@***.***> Date: 1/22/22  3:01 AM  (GMT-07:00) To: ousnius/BodySlide-and-Outfit-Studio ***@***.***> Cc: pgorbas ***@***.***>, Mention ***@***.***> Subject: Re: [ousnius/BodySlide-and-Outfit-Studio] Don't understand Install instructions at All (Issue #408) 
@pgorbas You missed a crucial point in the instructions which is to make a shortcut to BodySlide from inside of MO2, not a Windows-based shortcut.
Using MO2 it should be aware to you that any external programs you use must be run from inside of MO2, otherwise its virtual file system cannot hook into those external programs (such as BodySlide). The install instructions for MO2 for BodySlide are the same as for any other external tool, so this is not even an issue with BodySlide to begin with.

First of all "Mod Organizer", as far as I know, doesn't even exist anymore, the current program is Mod Organizer Two or MO2.

The install instructions are the same for MO and MO2, which is why the "2" was left out because it applies to both.

Install any BodySlide addons such as body mods and outfits to MO as well.
What BodySlide addons ?? There are none listed in your file section??

It's explained in the very line you quoted.
BodySlide addons = body mods and outfits with support for BodySlide.
There's thousands of them on the Nexus, so it doesn't make much sense to link them.
Compatible body mods are in fact linked on the mod page of BodySlide on the Nexus.
You don't need to deal with any of the other settings such as the reference skeleton or root node. Those only apply to Outfit Studio and in 99,9% of cases don't need to be changed. The settings are explained for completeness-sake on the wiki.
Please report installation issues on the mod page instead of the GitHub page, or join my Discord server to receive direct help in a live chat scenario (link is on the mod page and inside the program).
