### ISSUE TITLE
MO2 - Using Root Builder Plugin causes OS to be unable to save files. 

### ISSUE THREAD

**Issue by SynthOB** [ousnius/BodySlide-and-Outfit-Studio#411]
**Description**
MO2 Users using the Root Builder Plugin (https://www.nexusmods.com/fallout4/mods/43814/) cannot save files in OS

**How to reproduce**
1. Use RootBuilder 
2. Launch OS through MO2 and attempt to save a project

**Comment by ousnius** [comment]
@SynthOB Please report this issue to the developers of Root Builder or MO2 first. I can't do anything about the behavior of mod managers or their plugins.
