### ISSUE TITLE
Slider data not saving properly

### ISSUE THREAD

**Issue by enpinion** [ousnius/BodySlide-and-Outfit-Studio#414]
**Description**
Slider data is corrupted after saving projects.
Commit version: 7db256a8c32297166f32c8447ef21adcd4864a5a

**How to reproduce**
1. Open an existing project or start a new
2. Edit existing sliders or create a new one
3. Confirm slider edit and test.
4. Save the project.
5. Reload the project.
6. The previously edited slider is broken after load

**Comment by ousnius** [comment]
@enpinion Thanks, I just fixed this with fb27bfc.
