### ISSUE TITLE
Move brush improvements

### ISSUE THREAD

**Issue by themilkdrinker0** [ousnius/BodySlide-and-Outfit-Studio#420]
OS move brush feels weird, I don't know how the 3D softwares do it, but I took some screenshots as an exemple:

Zbrush | Softimage | OS

![Untitled-1](https://user-images.githubusercontent.com/80032229/152407935-cf58b7e8-6d15-4641-be3d-28d9c9011199.jpg)

Also, that's the maximum radius brush size in OS, it would be nice to have it extended.

**Comment by sts1skj** [comment]
@themilkdrinker0 What if you fiddle with the "Focus" brush setting slider?

**Comment by themilkdrinker0** [comment]
1.0 Focus

![image](https://user-images.githubusercontent.com/80032229/152410192-0cb4b014-1f99-4c7c-af70-1b0b1f9c0edf.png)

0.1 Focus

![image](https://user-images.githubusercontent.com/80032229/152410361-5ab52b0d-6b9b-4928-8e05-1f8b6fbe6778.png)

Same brush size.

**Comment by sts1skj** [comment]
@themilkdrinker0 But what about more intermediate values for brush focus? .2, .3, .5, .7, .8?

(I agree the "Size" brush setting needs a higher maximum than 1.0.)

**Comment by themilkdrinker0** [comment]
0.2 seems to give the best result, but could be more responsive, that's dragging all the way to the corner of the screen, it would be nice for it to deform closer to the mouse movement.

![image](https://user-images.githubusercontent.com/80032229/152411855-4428cb65-6959-492d-a068-3d878ab6629b.png)

**Comment by sts1skj** [comment]
Here's the formula for how focus affects the strength of the move at a vertex whose distance from the pointer is "d":

sd = d / radius

strength = (1 - sd^2) * (1 - (sd / focus)^4)

where "radius" is the brush size and "focus" is the focus brush setting, 0<focus<=1.

I have no idea where this formula came from; it's from before I started working on Outfit Studio.

It looks like Zbrush and Softimage use completely different formulas and perhaps even completely different algorithms.

**Comment by themilkdrinker0** [comment]
Zbrush also has a second circle inside the brush display circle to represent the focus, this could be helpful too.

**Comment by sts1skj** [comment]
Here's a graph of the brush strength as a function of d / radius for focus of .1, .4, and .8 (using the formula above, which is from the current Outfit Studio 5.5.2 source code):

![image](https://user-images.githubusercontent.com/59774938/152423195-d542031a-0ee4-4e30-abf0-a3eead1e5de3.png)

To me, there are some problems evident in these curves:
1. The nonzero portion does not extend to 1.
2. They have approximately the same shape, just different scales.
3. They have a hard turn when they hit the x axis instead of curving smoothly.  (Mathematically, the slope is discontinuous.)

**Comment by sts1skj** [comment]
Ack!  The formula I gave above is for focus<.2 .  A different formula is used for .2<focus<1 .  So the graphs above are labeled wrong: those are for focus=.08, .02, and .16, not .4, .1, and .8 .

The formula used currently for .2<focus<1 is:
x = 5 * focus * (1 - sd) - 1
strength = (1 - x^2) * (1 - x^4) if x < 0
strength = 1 if x >= 0

Here are the graphs:
![image](https://user-images.githubusercontent.com/59774938/152598695-519d9beb-2844-4e1f-8456-322ce68786e4.png)

**Comment by sts1skj** [comment]
Here's an updated graph combining both ranges for focus:

![image](https://user-images.githubusercontent.com/59774938/152601168-f8259abb-3146-4c8f-9cdf-862ccb50713d.png)

**Comment by sts1skj** [comment]
@themilkdrinker0 Could you post your nif file with the sphere that you used in your screenshots?  I want to test some possibilities.

Looking at your screenshots, I can see why .2 would give the best result: it has the nicest-looking curve in the graph.

**Comment by themilkdrinker0** [comment]
[Sphere.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/8007235/Sphere.zip)

**Comment by sts1skj** [comment]
Here's a possibility that I'll name "the cubic option":

p = 6^(2 * focus-1)
x = sd^p
strength = 2 * x^3 - 3 * x^2 + 1

(I chose the number "6" in the formula to give reasonable extremes: the higher that number, the more pointy it is at 0 and the more flat it is at 1, with .5 staying the same.  The other numbers in the formula are necessary for this function to work.)

Here's a graph:
![image](https://user-images.githubusercontent.com/59774938/152626846-5d4b614d-6244-4d63-90da-fdfe5c3fa821.png)

Here's its effect on the sphere at focus=.5 (and maximum brush size):
![image](https://user-images.githubusercontent.com/59774938/152626898-7fbc36a2-a00b-4d64-a37c-93740d9b82a7.png)

Focus=0:
![image](https://user-images.githubusercontent.com/59774938/152626914-04696fdd-0094-4dd4-8617-84a3a467294f.png)

Focus=1:
![image](https://user-images.githubusercontent.com/59774938/152626933-c7c3c66c-385c-4076-9a15-cbfe5b27e3cf.png)

Focus=.25:
![image](https://user-images.githubusercontent.com/59774938/152626952-6deb4126-c554-4beb-925d-b7419ffdf365.png)

Focus=.75:
![image](https://user-images.githubusercontent.com/59774938/152626969-8d54f095-f31a-4509-b9e2-637e881349b5.png)

@themilkdrinker0 What do you think?  Is it significantly better?  Is there room for improvement?

**Comment by themilkdrinker0** [comment]
Looks good to me, just make the 0.5 the default value when opening OS.

**Comment by sts1skj** [comment]
@ousnius What do you think?  May I replace the formula in TweakBrush::getFalloff with the new formula, get rid of the factor-of-5 scaling, and set the default to .5 for all brushes?

themilkdrinker0 also requested that the maximum brush size be increased.  It looks like, internally, brush size is scaled by 3.  May I increase the scaling to 10?

**Comment by ousnius** [comment]
@sts1skj Yes, please do so I can play around with the new formula myself. Feel free to increase the scaling to 10, but make sure to adjust the default size (0.150 right now) accordingly to be the same size it is currently.

**Comment by sts1skj** [comment]
@themilkdrinker0 Ousnius and I have played with the new brush scale some, and we don't like 10, so we're going to keep the old brush scale of 3.  But we're also increasing the maximum size of the value that can be input into the text field next to the slider from 1 to 10, so you'll be able to get a larger brush size by typing in the number you want.  We're also increasing the precision of the text field from 3 to 4, so you can type in smaller brush sizes.
