### ISSUE TITLE
Targeted Vertex Snap between TriShapes

### ISSUE THREAD

**Issue by MadCat221** [ousnius/BodySlide-and-Outfit-Studio#428]
Can a means to target-snap one vertex to another on a separate trishape (and of course on the same trishape) be implemented? It would be immensely useful for sealing up seams between shapes that have congruent border edges, such as the gold trim and main blue coverall on the FO4 Vault Suit.

**Comment by ousnius** [comment]
@MadCat221 This was implemented in #419 that I linked you.
