### ISSUE TITLE
(FO4) Segment bug still occurs.

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#433]
I don't know how to reopen a closed issue, so I open a new one.
[This is the closed issue page I posted before.
](https://github.com/ousnius/BodySlide-and-Outfit-Studio/issues/378#issue-988656146)
It still happens with the lastest version of Outfit Studio.

![00](https://user-images.githubusercontent.com/90162452/154407079-f9ba72fe-d477-441f-9ced-8059e71401f7.png)
Loaded Combat Armor in CBBE Vanilla
![01](https://user-images.githubusercontent.com/90162452/154407083-36dfdf8e-4c76-453e-ad41-db33cb60f01b.png)
As you see, all triangles are assigned to segement 3(torso)
![02](https://user-images.githubusercontent.com/90162452/154407085-8c5f0142-159f-448a-9fd8-6f025eaa30fe.png)
Added 2 empty segments(4, 5), still all triangles are assigned to segment 3
![03](https://user-images.githubusercontent.com/90162452/154407087-4bd1dbe9-e22f-4ad7-b8c1-f0922eb79bfa.png)
Press Apply and now all triangles are assigned to the last segment, 5.

This screenshots were taken today with latest version in Nexus Mods

**Comment by sts1skj** [comment]
Hopefully I have fixed this bug in https://github.com/ousnius/nifly/pull/26 .  The bug was originally my fault.
