### ISSUE TITLE
Mirror Brush Display

### ISSUE THREAD

**Issue by themilkdrinker0** [ousnius/BodySlide-and-Outfit-Studio#435]
As shown in the gif, you can see it through the mesh too.

![Bodyslide-2022 02 18---19 40](https://user-images.githubusercontent.com/80032229/154771259-611c325d-7f1d-4e61-8a3e-e8e4ad3fb5ef.gif)

**Comment by sts1skj** [comment]
When X-Mirror is on, the Move Vertex tool (which you probably haven't seen yet) already does this.  For the Move Vertex tool, the highlighted mirror vertex is exactly the vertex that will be mirror-moved if you click.  The mirror vertex is computed like this: the camera position is mirrored; the direction from the camera towards the surface is mirrored; these give a ray in space; the location on the surface that this ray hits is found; the nearest vertex on the surface to this mirror-ray-hit location is found; this is the mirror vertex.

But that's not how the brushes work.  The center of the brush action (which is highlighted red) is the point on the surface directly under the mouse and _not_ the nearest vertex (which is highlighted cyan).  For the _mirror_ of the brush action, the center is the _mirror_ of the non-mirror center (the point you get if you replace the center's x coordinate with its negative).  If the shape is not at all symmetrical, this mirror center is not necessarily on the surface at all.  Regardless if the mirror center is on the surface, inside, or outside, all points within the brush radius of the mirror center are affected (if X-Mirror is on).

So I wonder if it might be more useful to display the mirror of the brush center and brush radius circle than the mirror vertex.

**Comment by themilkdrinker0** [comment]
Well, that was just an idea, mirroring the brush circle would be just as useful.
