### ISSUE TITLE
Custom bones don't appear right with "Show Bones" or "Show Nodes"

### ISSUE THREAD

**Issue by sts1skj** [ousnius/BodySlide-and-Outfit-Studio#440]
Custom bones don't appear at all when you turn on "Show Bones".  They do appear when you turn on "Show Nodes", but their location doesn't update when you change them with "Edit Bone".

**Comment by sts1skj** [comment]
Pull request #441 fixes the first problem: custom bones don't appear.

The second problem is apparently because NiNodes are not updated until the NIF is saved.  Until then, the copy of NiNode data in AnimSkeleton can be out of sync with the copy in NifFile.  I don't know why OS works this way, so I don't know whether it makes sense to fix this problem.

**Comment by ousnius** [comment]
> Pull request #441 fixes the first problem: custom bones don't appear.
> 
> The second problem is apparently because NiNodes are not updated until the NIF is saved. Until then, the copy of NiNode data in AnimSkeleton can be out of sync with the copy in NifFile. I don't know why OS works this way, so I don't know whether it makes sense to fix this problem.

Yes, I knew about the second problem and decided it's too dangerous fixing it/changing that behavior.
