### ISSUE TITLE
Numeric fields (or at least basic multipliers/dividers) for the UV rescale tool.

### ISSUE THREAD

**Issue by FramFramson** [ousnius/BodySlide-and-Outfit-Studio#442]
In reusing small or partial meshes I have at times wanted to consolidate these into smaller texture files, or incorporating already-small textures images into larger ones, but the issue is that the UV editing tools in OS lack any means of inputting precise values. 

For example I took a belt from a complete outfit to reuse elsewhere. The texture file for the original mesh is a typical 2048 x 2048, so most of that area becomes wasted space when using only one small component. I wanted to reduce the texture file to 1024 x 1024 or even 512 x 512 to increase optimization, but it's very difficult to do so in OS because the scale tool in the UV mesh editor lacks any way to enter fixed values to scale areas of the UV map selected for editing. If a texture file is being reduced in dimensions by half the UV map of the corresponding mesh must be doubled in size to retain the correct relative texture dimensions in the final mesh.

This limits the user to imprecisely eyeballing the task, or interrupting workflow to open Blender for this one task, before returning to OS (which personally I prefer to use for anything but the heaviest mesh editing). 

As the brush tool recently received fields to input numeric values, perhaps the same could be added to the UV scaling tool? Perhaps even the movement tool as well? Or if numeric fields are too large a feature, perhaps at least a simple button to double or halve the selection?

**Comment by ousnius** [comment]
@FramFramson I added translate, rotate and scale dialogs to the UV editor, allowing you to enter specific values in a text field and using a slider. Keyboard shortcuts: T, R and S.
