### ISSUE TITLE
Automatically triangulate imported meshes

### ISSUE THREAD

**Issue by GrafPanzer** [ousnius/BodySlide-and-Outfit-Studio#443]
Outfit Studio does not currently handle mesh faces with more than three sides.  Upon importing an .fbx or .obj with multi-sided faces, OS typically omits the 4+ sided faces (I think it sometimes triangulates them, not sure).  A better way to handle this would be to automatically triangulate all faces upon import, so users don't inadvertently end up with holes in their meshes.  [Inspired by a user issue in the outfitstudio-help channel on Discord today.]

**Comment by sts1skj** [comment]
I've taken a look through ObjFile::LoadForNif (which is Outfit Studio's function for parsing OBJ files), and it looks to me like it currently can handle faces with 3 or 4 vertices, but not more.

@GrafPanzer Is it possible that OBJ import only misbehaves for faces with 5 or more vertices, and works okay for 4?

**Comment by ousnius** [comment]
FBX import triangulates the mesh, however the UV map will be screwed up as it won't account for actually splitting up the mesh where the UV island seams are located.

OBJ import can handle quads (iirc it should turn them into two triangles, but need to check). I don't know if the OBJ format by itself even supports polygons with more than 4 points.

**Comment by sts1skj** [comment]
<s>Could someone please verify that PR #444 fixes this issue?  More specifically, can you now import OBJ files with more than 4 vertices per face, and can you now import FBX files with more than 3 vertices per face?</s>

**Comment by sts1skj** [comment]
Verified importing a hand-written OBJ with a hexagon:
```
o hexagon
v 0 0 0
v -1 0 1
v -1 0 2
v 0 0 3
v 1 0 2
v 1 0 1
f 1 2 3 4 5 6
```

**Comment by GrafPanzer** [comment]
Thanks for taking a look at this, sts1skj.  Sorry, but once again I'm not competent to verify fixes before they're merged and published.
