### ISSUE TITLE
i cant see anything in the bodyslide

### ISSUE THREAD

**Issue by thanos13356** [ousnius/BodySlide-and-Outfit-Studio#445]
i downloaded the bodyslide from nexus mods and installed it on vortex but when i open it i nothing works it doesnt have any preset not any slides to create the body the build and preset button doesnt do anything and i have tried numerous things like reapering my game but nothing works also i have it for fallout 4
![unknown](https://user-images.githubusercontent.com/101312792/157598381-e7afdf4c-8379-48a9-96f5-76f633c1f11e.png)

**Comment by ousnius** [comment]
@thanos13356 Please look for support on the mod page or in the Discord server.
