### ISSUE TITLE
Copy from Shape does not copy all properties

### ISSUE THREAD

**Issue by GrafPanzer** [ousnius/BodySlide-and-Outfit-Studio#449]
In Outfit Studio, the command Shape > Properties > Copy from shape... does not copy all properties.  For Fallout 4 shapes, for example, Root Material, Subsurface Rolloff, and Grayscale to Palette Scale are not copied.  These properties can be copied in NifSkope, but if OS copied all properties it would eliminate the extra step of copying properties in NifSkope.

**Comment by ousnius** [comment]
@GrafPanzer The feature was originally never intended to fully copy the shader with all its values and children blocks, but only fill the shape properties dialog with the values for the fields it has.

I've enhanced the feature to fully copy everything now.

**Comment by GrafPanzer** [comment]
Thanks for enhancing it.  That will significantly simplify the workflow.  It was really close to a full copy before, so I thought I'd ask.
