### ISSUE TITLE
Weight/vertex painting for large objects.

### ISSUE THREAD

**Issue by OdinMods** [ousnius/BodySlide-and-Outfit-Studio#452]
Hi. I requested this a while back on the Discord, but I wanted to make a formal request here.

I wanted to use Outfit Studio to weight paint and vertex paint my tree objects. Having a "fill" tool and increasing the brush size for large objects would make this pipeline more useable as for now it's very tedious.

Example object where the fill tool would be extremely useful.
![unknown](https://user-images.githubusercontent.com/61665039/163846766-aec5a880-5c65-4f38-87e4-77c7e82d04ee.png)

**Comment by sts1skj** [comment]
@OdinMods In commit 7230018e (PR #422), we increased the maximum brush size from 1 to 10 (but you have to type values larger than 1 into the text field).  Hopefully that'll be big enough to cover an entire tree.  Commit 7230018e has not yet been released; it should be in the next major release of Outfit Studio.

As an alternative to a "fill" tool for weight painting, you can turn on the "Edit Connected Only" tool option (which is both in the "Edit" menu and in the vertical tool bar).  Hopefully this will do what you want.
