### ISSUE TITLE
Mask selection in UV editor in main viewport (select by UV)

### ISSUE THREAD

**Issue by ahzidaljun** [ousnius/BodySlide-and-Outfit-Studio#457]
**What is it that you want to do that isn't currently possible?**
A selection by UV limits, ala connected vertices only, would be nice to help with editing distinct parts of an outfit that are connected in mesh but do not share an UV island and thus could reasonably be separated, like pants, sleeves, etc

This is available in dedicated 3D apps like Blender and Max
![Screenshot_14](https://user-images.githubusercontent.com/72061961/166461977-47d360db-d45b-44ea-af0e-c1bd753038d0.png)

**Request the feature**
The feature could be accessed as a new brush toggle option in the menu bars or in the UV edit panel, where you could right click -> translate current UV selection to viewport mask

**Comment by ousnius** [comment]
@ahzidaljun 

> parts of an outfit that are connected in mesh but do not share an UV island

This combination isn't possible in the NIF format. Each vertex can only have one texture coordinate, so everything that's not connected to the same UV island is automatically unconnected mesh-wise as well.

What you can already do is select (mask) all vertices that are connected mesh-wise (faces are connected in some way) by using the menu items "Mask More/Less" or their keyboard shortcuts.

**Comment by ousnius** [comment]
@ahzidaljun This can now be done.

![image](https://github.com/user-attachments/assets/fc05d94f-0ad1-4660-a9d8-2e8a986f2ee1)
