### ISSUE TITLE
[FO4] About left bare forearm problem when not wearing pipboy

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#458]
In FO4, some outfits have 2 left arm meshes because of pipboy.
For example,
![Suit00](https://user-images.githubusercontent.com/90162452/168335955-e5dba79e-1286-4242-9404-5674fb2d329e.png)
This is the mesh of clean suit.
 - Both of sleeves covers wrists if pipboy is not worn together.
 - Left sleeve is rolled up and bare forearm is revealed when pipboy is worn.

The problem is, that bare forearm is hidden automatically in vanilla meshes, but not in custom meshes like CBBE.
![ScreenShot0](https://user-images.githubusercontent.com/90162452/168336134-7a8bdc5d-ba77-4ad3-afde-adc59213a90c.png)
So the bare arm is sometimes clipping through clothing like this. (this screenshot is taken with Bodyslided mesh of CBBE Reduced Vanilla)
I looked into it and found a solution by using nifskope.
1. (Maybe optional) Load the bodyslided mesh in Outfit Studio and clean up segment
![002](https://user-images.githubusercontent.com/90162452/168336185-81400359-1cc1-41e9-8e6d-7e40252eb081.png)
    - I just did this to make it easier to edit the mesh in nifskope. It may not be necessary, but I'm not sure.
    - I used cbbe reduced because original cbbe does not really have segment in the mesh. Just to make the job easier.
    - Cleaning segments do nothing about that forearm. You can confirm it by running the game after this stage.
3. Open the file in nifskope
![003](https://user-images.githubusercontent.com/90162452/168336586-79629640-274f-4ac8-ab91-a6e9ad3568ce.png)
4. **IMPORTANT : Edit the number in Per Segment Data to 160**
![004](https://user-images.githubusercontent.com/90162452/168336610-fc2694e6-04e8-40e6-b7aa-fe407a9341b6.png)
5. run the game and the bare arm part is gone.
![ScreenShot1](https://user-images.githubusercontent.com/90162452/168336632-618df34c-825d-4654-b6d6-1d57428150db.png)

I really have no idea how it works. I just copied it from vanilla meshes. I'd appreciate if someone look into this and add support for this in Outfit Studio.

**Comment by ousnius** [comment]
@MrAnnonymous00 The numbers ("User Index") are the slot of the segment ("Slot" in the Outfit Studio dropdown). The pipboy slot is 60 and the pipboy cap slot is 160.

Outfit Studio didn't have the slot 160 as a choice yet, I just added it. Meaning you will be able to choose it instead of having to enter the number in NifSkope in the next version.
