### ISSUE TITLE
[FO4] About 'Merge Geometry' function and Segment Data

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#461]
When trying to merge shapes in Outfit Studio, several things are checked before executing it. Like shader data, alpha properties and segment data.
And segment data checking seems like it doesn't work as it intended. For example,

![01](https://user-images.githubusercontent.com/90162452/172189895-9cb075ac-2224-4600-8864-abe5b7fe3518.png)
1. This is Army Fatigues slider set from CBBE Vanilla. And I'm going to merge PipboyArm0_0 to Body_0.

![02](https://user-images.githubusercontent.com/90162452/172190259-fc749d82-139c-492f-aca4-db1a91902b2f.png)
2. Both shapes already have the same shader data, so I'll just edit segment data.

![03](https://user-images.githubusercontent.com/90162452/172190420-21448466-e559-4124-9106-c0f74ef7d3dd.png)
3. I added blank segments to the shape 'PipboyArm0_0' to make it look like 'Body_0'. Same count of segments and subsegments. Also they already share the same SSF file.

![04](https://user-images.githubusercontent.com/90162452/172191034-202b3fa1-18fd-4f2e-a542-dbd0f9535321.png)
4. But when I try to merge them, pop-up windows says segment data does not match. But I think I've done all I can do to match them. Even I checked the nif file with nifskope, but nothing came up.

Is there anything else I missed? Or is this a bug? I'm not really sure what it is. Please take a look at it.

**Comment by ousnius** [comment]
@MrAnnonymous00 Segment slots aren't identical.
![image](https://user-images.githubusercontent.com/7034795/172198048-aff5ad92-f2f9-488a-af37-8d6054c25f61.png)

**Comment by MrAnnonymous00** [comment]
I've made a mistake in that screenshot. But trust me, I've tested for this for almost a dozen times. And I've just tested again.
![03-1](https://user-images.githubusercontent.com/90162452/172308277-ee24ce53-54b4-440f-a495-a54eb5cad12e.png)
And it's not working in this time again.
![04-1](https://user-images.githubusercontent.com/90162452/172308465-68ef3f7f-71a4-43cc-9f9c-aa3f49c353f4.png)



Edit :
I found the answer by myself. The reason is 'Cut Offsets'.
These values are related to body dismemberment and only visible through Nifskope, not Outfit Studio. You need to copy them to merge the meshes properly. It would be better if Outfit Studio can handle it, too.

**Comment by ousnius** [comment]
@MrAnnonymous00 I've removed the check for cut offsets having to be identical to be able to merge geometry for now while Outfit Studio doesn't allow editing cut offsets.
