### ISSUE TITLE
(FO4) Trying to preview crashes BodySlide

### ISSUE THREAD

**Issue by drgns** [ousnius/BodySlide-and-Outfit-Studio#463]
Whenever I try to preview the settings I put into BodySlide, it always freezes the program and won't show what it was I was trying to preview. I thought it was an issue with other mods, but it does the same thing for models that came base with the program. The model can still be built and implemented into the game, but I don't want to have to enter and exit my game to test slider settings.

**Comment by ousnius** [comment]
If you or someone else is still experiencing issues with this, please do a new report on here, the Nexus or Discord. Need more information on the setup, mod manager, installation, maybe log files.
