### ISSUE TITLE
Show outfits with zap options only (BodySlide)

### ISSUE THREAD

**Issue by alphabetsoupdog1234** [ousnius/BodySlide-and-Outfit-Studio#464]
IMO this is a low priority nice-to-have.

Currently there's no way (to my knowledge[!]) that you can find which outfits have ZAP options aside from the mod author writing this information somewhere, or looking at each piece / data file one at a time.

In my opinion, it would be great if there were an option to automatically create/update an outfit group that contains all your items with ZAP options.

Maybe a button in the group manager, where it'll go through all the files and check for ZAP options, before adding that item to the group?

Possibly as an option when doing a batch build where whenever it builds an outfit with a ZAP option, it adds it to the group?
>> obviously this would result in some degree of slowdown, since there's extra checks and steps...

Some better method that someone else can come up with? :)

**Comment by user177013** [comment]
Second this.
There need to be some way to filter items that have special sliders/zap, this will make changing presets immensely easier.
I've somewhat managed to rebuild my collection with ZAPs almost intact by looking at individual items and making a new preset but since the sliders name isn't standardised, e.g. some creator use LEG_PUSH but another use Pressed, it's such a pain.

**Comment by ousnius** [comment]
> Second this. There need to be some way to filter items that have special sliders/zap, this will make changing presets immensely easier. I've somewhat managed to rebuild my collection with ZAPs almost intact by looking at individual items and making a new preset but since the sliders name isn't standardised, e.g. some creator use LEG_PUSH but another use Pressed, it's such a pain.

Version 5.6.0 or higher now saves the last used zap options for every outfit, including for batch builds. So there only needs to be a way to find all outfits that have (visible) zap options.

Saving values for custom sliders like "Pressed" would be harder to do, as they aren't zaps but could theoretically be saved to a preset file.

**Comment by ousnius** [comment]
@alphabetsoupdog1234 @user177013 I've added a filter "Has Zap Options" to BodySlide that will make it so the outfit list only shows entries that have a (visible) zap checkbox.

![image](https://github.com/user-attachments/assets/b28da2a2-6ef9-4601-b841-e5458e80c6f6)

**Comment by alphabetsoupdog1234** [comment]
Sorry for the late response (I barely use github), but that's fantastic!

Hopefully it didn't take you too much effort, but even if it did: know that it is greatly appreciated by at least one random internet person 😄
