### ISSUE TITLE
Original slider data not purged on import of new reference

### ISSUE THREAD

**Issue by rdhughes** [ousnius/BodySlide-and-Outfit-Studio#468]
When converting from CBBE bodies or earlier versions of  BHUNP to BHUNP v3, importing the new reference and confirming results in a mesh with incorrect slider data attached to the vertices. This means that moving a slider causes the mesh to deform in a distorted manner. This happens regardless of whether merge slider data is checked or not. The problem seems to appear any time the UV/vertex count of the old reference differs from the new reference body and when the mesh uses slot 32.

Clearing and deleting the reference and saving the outfit, then reloading the outfit and readding and conforming to the reference is required to avoid this condition.

One easy way to see this is to load the Umbra BHUNP version, then load the "Umbra -Vest" in outfit studio, remove the existing reference, load the BHUNP ver 3 Advanced body reference and conform. The result is a broken outfit. Then load ""Umbra -Vest(Bra)", load the BHUNP ver 3 Advanced body reference and conform. This time, the result is as expected.

**Comment by ousnius** [comment]
This is now fixed.
See #466 and commit dc41e5b12765dff5a693caa86c28e6baa7cb7b4d.
