### ISSUE TITLE
Open currently active outfit's shape data folder in BodySlide

### ISSUE THREAD

**Issue by Spaz490** [ousnius/BodySlide-and-Outfit-Studio#469]
Bodyslide: open shape data folder button

I was thinking that it would speed up peoples workflow if they were able to open the selected outfits shade data, for quick access for Nifskope etc.

**Comment by ousnius** [comment]
![image](https://github.com/user-attachments/assets/2cbc1a4b-68dd-454e-bbff-c2c2f1a81000)
