### ISSUE TITLE
More editable feature configs

### ISSUE THREAD

**Issue by lensman11** [ousnius/BodySlide-and-Outfit-Studio#473]
I am getting Sooooooo tired of changing settings to my prefered ways of working every time I change to a feature ie increase/decrease/smoothing etc.
If there isn't one, can the next version release include savable options in the config file to store user preferences??

Regards Colin
PS:
Also I always turn OFF the default perspective view before doing anything in Outfit Studio.
Andthe same in Body Slide Preview but it also is NOT removable.
Yes I am aware that BS and OS are NOT mods so MCM is not available but even a more detailed config file would be nice.

**Comment by lensman11** [comment]
Also would it be possible to add a crash recovery option - I have had frustrating crashes after doing bulk editing in OS only to have an exception error crash the project. Even a configurable auto save would be a godsend on occasions like this.
Regards Colin

**Comment by lensman11** [comment]
Sorry did not mean to close..................

**Comment by lensman11** [comment]
....

**Comment by lensman11** [comment]
Is this still out-standing ?? Having a user config file with regular settings for the most used features is still the focus of this request.
In particular "TURNING OFF PERSPECTIVE VIEW" it is annoying and frustrating including the preview screen in Bodyslide!
Regards Colin

PS: Your advice regarding Refining Mesh was just one of the things I wanted clarified and it works great.

**Comment by ousnius** [comment]
@lensman11 The perspective view can now be changed in the settings for both BodySlide and Outfit Studio (and for Outfit Studio it remembers the last used option automatically) in the next version.

**Comment by lensman11** [comment]
Thanks so much - tried the new version and it's just what I needed..
I hope others notice the change and give appropriate thanks.
This can be closed if not already.

PS: Will the user configurable brush/tools option also be looked into in a similar manner??

Regards Colin
