### ISSUE TITLE
Vertises Changes under brush

### ISSUE THREAD

**Issue by lensman11** [ousnius/BodySlide-and-Outfit-Studio#474]
Would it be possible to increase/decrease vertice density in an area, say under the brush?
I often note when editing some low poly meshes that it would be great to be able to increase the poly count in a specific area ie breast or feet or hands.

Could you add this feature in a similar way you do bone weighting changes but apply to the mesh vertices?

Regards Colin.

PS: You must be swamped with requests as I see some posts going back a year un-actioned....

**Comment by lensman11** [comment]
My bad should have checked previous posted requests - noted similar request below from a year ago.
Shows that the option would still be a usefull feature even if its only me....

**Comment by ousnius** [comment]
@lensman11 You can use the mask brush to "select" an area. Then invert the mask and use the "Refine" action, which will increase the poly count.

**Comment by lensman11** [comment]
Have found it - and yes works as expected.Many thanks.
