### ISSUE TITLE
Remember selected zap's

### ISSUE THREAD

**Issue by Zaflis** [ousnius/BodySlide-and-Outfit-Studio#477]
**What is it that you want to do that isn't currently possible?**
In Bodyslide main window if you choose some outfit, change zap toggles, choose different outfit and then back the outfit you just edited, your changes to zap's are lost. Some outfits have over a dozen zaps and it is very delicate work going through each one using preview window. Especially if it is a whole Skyrim clothing and armor replacer mod, it means going through hundreds of toggles if you just want to change 1 slider in your body preset.

**Request the feature**
- It would be great if the toggles were saved when changes are made. Where are they saved? Could be just some ini file acting as a database for all your outfits.
- Batch building should support those zap changes.
- Maybe some people don't like this? Make it an option in the settings to "Remember zap toggles" and "Reset all zap's to defaults", which would maybe just delete the ini file.

Afternotes... I can't say i'm any Outfit Studio expert but i tried changing dafault zap's for 1 outfit. Lets say it's "needlessly complicated". For example i went to edit mode for "Leggings" slider group and clicked on gear, then toggled the "Default" zap. Then turn off its edit mode and save project. Back in Bodyslide i select the outfit, and sure enough leggings is zapped, but the model's legs are invisible too?? I reopened the project and reversed my steps in toggling the zap back off and saved, legs and leggings are back. That's not what happens when you normally toggle leggings in the main Bodyslide.

**Comment by ousnius** [comment]
@Zaflis Remembering zap options has just been implemented (see #490).

As for the default zap value you changed - some outfits use "zap toggles" which means that one zap also toggles ANOTHER zap along with it. Changing the default value won't change the default value of the other zap linked to it, so you have to change both zap's default values. There was likely a zap that removed the legs.
