### ISSUE TITLE
Smooth tool equivalent for bone weight painting?

### ISSUE THREAD

**Issue by PS-Dane** [ousnius/BodySlide-and-Outfit-Studio#480]
An equivalent of the smooth tool for bone weight painting would be very useful to me, since using NiOverride on bones with custom weighting always ends up with a bunch of sharp edges that REALLY stand out in directional lighting.

**Comment by ousnius** [comment]
@PS-Dane You can hold shift while using the weight brush to smooth. Additionally you can turn on normalization in the Bones tab.

**Comment by PS-Dane** [comment]
Sorry, I didnt know that. Thanks for the pointers.
