### ISSUE TITLE
Merge Geometry messes up mesh

### ISSUE THREAD

**Issue by Pop000100** [ousnius/BodySlide-and-Outfit-Studio#481]
**Description**
 Merge Geometry causes one trishape to move ruining the mesh I had encountered this before but i couldn't remember the mesh but this is less serious then this mesh
[mesh.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/11098054/mesh.zip)

**How to reproduce**
Look at the back of the mesh
Merge the two trishapes together
Look at the back of the mesh
And notice the strap is now clipping the shirt

**Comment by ousnius** [comment]
@Pop000100 This is probably related to the two meshes/shapes having different transformations stored on them. If you select the two BSTriShape blocks in NifSkope, you will notice different values in the "Translation" field.

You can fix the issue by applying the "Edit -> Reset Transforms" function in Outfit Studio **before** you merge the geometry.
