### ISSUE TITLE
Override max triangles when creating references using merge geometry in outfit studio

### ISSUE THREAD

**Issue by rdhughes** [ousnius/BodySlide-and-Outfit-Studio#482]
I'm working on creating a reference that will only be used for conforming armors. I'm trying to merge two different parts to finalize the body so that it can be used as a reference, but even after deleting the all parts of the mesh that will be covered by the second part, I still get the message that the resulting shape would contain too many triangles. For a shape that is strictly a reference and not used in the game, this shouldn't matter. Therefore, I would like the ability, with an appropriate warning, to bypass the message and perform the merge any way. Even a command line argument would work.

**Comment by ousnius** [comment]
The limitation is with the NIF file format, not the game. So it's not possible to save a file with more triangles.

**Comment by rdhughes** [comment]
OK. But that leaves me with a question; why then is it possible to take a mesh that OS says has reached the triangle limit, mask off parts of the mesh, run the refine option against the unmasked parts, and save that mesh and load it in the game?

**Comment by ousnius** [comment]
@rdhughes With the parts you masked, it is probably not exceeding the limit anymore when using Refine Mesh. It only does when trying to refine the entire mesh (without a mask).
