### ISSUE TITLE
Please add exceptions for vanilla and select .tri files.

### ISSUE THREAD

**Issue by SQr17** [ousnius/BodySlide-and-Outfit-Studio#484]
**Description**
Would it be possible to add exceptions for vanilla .tri files in Bodyslide when building meshes and morphs? Currently, if you use Bodyslide to build face and face part meshes, it proceeds to either remove loose .tri files of the same name, and with Build Morphs checked, it replaces them with the incorrect type of .tri files, leading to CTD.

Fallout 4 has 79 vanilla .tri files. Ideally, Bodyslide would never touch the vanilla .tri files, plus it would be great if we could add our own exceptions as well (for current and future custom face parts).

**Comment by ousnius** [comment]
@SQr17 Head part .tri files are not replaced by body morph .tri files any longer when building a project that output a NIF with the name of a head part. They're also not deleted when building without body morphs.
