### ISSUE TITLE
Adding per shape controlled normals smoothing angle

### ISSUE THREAD

**Issue by JohnnyBungalow** [ousnius/BodySlide-and-Outfit-Studio#487]
"right now there's the "Smooth Normals" and the "Smooth Seam Normals" toggles, one turns smoothing completely off or on and the other makes it so UV seams (so "real" UV seams that are actually duplicate vertices) are smoothed as if there was no seam/gap
the smoothing angle is 60°, any edge that's harder than that won't be smoothed
so it would require a per-shape based configuration of the maximum smoothing angle"

**Comment by ousnius** [comment]
@JohnnyBungalow I added this for the next version. It's saved per shape in the .osp project file.

Decreasing the angle from the default of 60° to, for example, 10°, will result in more hard seam edges, while increasing the angle will result in more smooth seam edges.

Bear in mind that this entire mechanism only affects the normals of edges on (UV) seams that touch other edges on the mesh, not ALL normal angles of a mesh.
