### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by DapaCz** [ousnius/BodySlide-and-Outfit-Studio#488]
I have been trying to convert women's clothes to men's for many hours. In the game, the clothes work on the woman, but I can only see the head and hands on the man. Please advise what I can do. I'm already desperate. My dream is to be able to convert women's clothing into men's and vice versa.

https://live.staticflickr.com/65535/52925938686_2659393d9e_h.jpg
https://live.staticflickr.com/65535/52926349185_6a9f7c354f_k.jpg

**Comment by Cthorthu** [comment]
Hi
(This is not a bug)

When copying bone weights from reference, default values are a great start point. But, if some vertices are too far from body (for example, leg holsters) they may not be weighted.

In this case, you are lucky of not having a CTD when equip outfit...

A simple way to do it is:
Copy bone weights with default values (radius 5, vertex 4)
Try to save project. If you have a popup about unweighted vertices, select NO. Now you can see that the weighted vertices are masked.
Copy bone weights again, but sum +5 to radius.
Try to save project... every time you get a popup about unweighted vertices, select NO and copy bone weights again adding +5 to radius.

This is a simple solution, works perfectly 99% cases.

Another solution would be go to bones tab and manually paint the weights.
