### ISSUE TITLE
Some issues I've found experimenting with Oblivion outfit editing

### ISSUE THREAD

**Issue by Padomaic** [ousnius/BodySlide-and-Outfit-Studio#489]
Hello! I wasn't sure how to write this up, first time using github, but I wanted to mention a few things I found out when editing oblivion nifs in OS

*I can't seem to combine nifs in OS - The game rejects them if I don't combine them in nifskope first and THEN open and edit them in OS.
*Similarly, deleting vertices in OS at any point seems to yield similar results. I have to minimise clipping by squishing the body underneath, which is... Not ideal.

By "reject" I mean the models will just be invisible in game - I can't seem to figure out what exactly _causes_ this, as the only indication I've had was an incredibly vague message in a MessageLogger log that just says "[WARNING] The biped part _[item filepath]_ should be skinned for _[player name]_"

I know oblivion support is very experimental - but I hope this helps? :o

**Comment by lensman11** [comment]
How much editing are you trying to do in Outfit Studio? OS is not very friendly regarding mesh manipulations and will only merge meshes with identical vertici counts. Osnius has been very helpfull in advising me and others on OS limitations.
I have found Metasequoia great for editing meshes - only limitation is having to output .OBJ files into Meta, editing, saving back as .OBJ and importing into OS. You need to reset the texture entries in OS but I have ehad great success doing this.

Regards Colin

**Comment by Padomaic** [comment]
I'm only doing the same basic stuff one would do for Skyrim outfit conversions. Not even actually merging, just importing the two parts together, fitting clothes to the body shape and deleting vertices (since there's no sliders/zaps bc oblivion)

**Comment by ousnius** [comment]
@Padomaic Is there a possibility you can send me a simple example of a NIF file/edit you made in OS that doesn't work in Oblivion, and also possibly the same edit (like merging shapes) in NifSkope that works in the game?

That way I have two NIFs to compare with each other. Thank you!

**Comment by ousnius** [comment]
I think this is fixed with #382 and #505.
