### ISSUE TITLE
[Bodyslide] Save Zap Slider for single outfit

### ISSUE THREAD

**Issue by dagdralef** [ousnius/BodySlide-and-Outfit-Studio#490]
Hi Osnius,
there is times that is needed to batch build ALL or almost all the outfit, like with a 3BA update or something with Obody. I simply don't do it because of zap is not saving for every single outfit but only like a normal slider in the body preset. 
Obviusly not rebuilding the outfit when its needed bring glitch and i finally choose to rebuild the single outfits only when i see "problem" in game but in this way is always a mess...
I tryed to modify the default value of zap slider in OS for every single piece of outfit, but is not too fast when you have many outfit and clearly when the outfit's mod author update the mod, my changes are lost.

I think i'm not the only one with this "idea" and not the first who ask this features:

We need the possibility to save the zap slider setup for single outfit piece. Maybe in a single ini/txt file or one for every outfit, maybe through a checkbox in settings to enable or disable the automatic saves of zap sliders, or a button in the main window... idk we can think about it...

btw i don't pretend anything, I only ask if this is possible, if its something that you think will be usefull and if this feature can be taken into consideration for adding in a future update. I don't need/want to put pressure or to know when, I want only to know if i can dream/wait for this in the future ;D

Thanks for all

**Comment by ousnius** [comment]
@dagdralef Selected zap options are now stored in the existing BuildSelection.xml file (for each project/outfit).
As soon as a zap is manually toggled, the choice is added to the file and applied when loading the outfit or batch building.

Thanks for the request.

**Comment by dagdralef** [comment]
marvelous! many thanks!
