### ISSUE TITLE
Posing tool causes distortion on the mesh

### ISSUE THREAD

**Issue by Cthorthu** [ousnius/BodySlide-and-Outfit-Studio#491]
Hi!

Issue in OutfitStudio (Skyrim Special Edition), version 5.6.0

The "posing" tool in Bones tab causes distortion on the mesh. Every time you press "Apply to mesh", the whole shape is slightly modified. In practice, this causes bad seams on neck, ankles and wrists.

To easily replicate this issue, press "Apply to mesh" many times (for example, 20 times) and then zoom in and press W to see wireframe.

The seams issue is a problem from the first time you press "Apply to mesh". You can see it if you import a hands mesh after used that.

Sample images:
https://i.ibb.co/Nyf8Mhb/bug-Outfit-Studio-1.png
https://i.ibb.co/wBQpkHN/bug-Outfit-Studio-2.png

Thanks for your time

**Comment by ousnius** [comment]
@Cthorthu I fixed this for the next version by checking for every vertex if the new position is nearly the same as the old position (to reduce calculation noise). That way, these vertices won't move.

Thanks for the report.
