### ISSUE TITLE
Request again option to save user settings for various brush tools etc

### ISSUE THREAD

**Issue by lensman11** [ousnius/BodySlide-and-Outfit-Studio#494]
Is it possible to improve the settings/preferences option to include user settings for the brush and vertice manipulation options so that I don't have to re-enter them each time I launch a new copy of Outfit Studio?

I often change between panels and several settings values are shared across each panel. examples are the mesh expand/contract/move and smoothing..

These are options I use regularly. Some require small values and others have larger ones. But size/strenght/focus and spacing appear to be common in each. 

Also the ability to be able to select grouped vertices in a split mesh. An individual mesh in a group of meshes that have been merged but have no linked verices in the .NIF file.

Regards Colin

**Comment by ousnius** [comment]
@lensman11 Brush settings (size, strength, focus, spacing) are now saved to the OutfitStudio.xml config file. I've also added a "Reset" button to the brush popup.

You can already select connected vertices by using the "Select More" / "Select Less" menu items or shortcuts, which will mask vertices that are connected to the other already masked vertices within the same mesh only.
