### ISSUE TITLE
Bug about remembering zap slider option

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#495]
Since version 5.6.1, bodyslide remembers zap sliders's option. The problem is, if a zap slider is set to toggle other zap slider(s), remembering option may failed to function properly.

For example
![ZapSetting01](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/a0673ffe-b949-47f2-84a1-dfaceae1a7e3)
![ZapSetting02](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/b9eb657b-14d3-442e-8aab-a8aa3446c7e3)
I added 3 zap sliders in this set : boots, arms, waist.
Boots will be the only zap slider shown in bodyslide and other silders will be hidden, only to be toggled by boots zap slider
(waist slider has the same setting with arms slider)

![ProperZapped02](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/a51e466f-f62d-4f62-a0e7-9d470a1180d8)
![ProperZapped01](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/7648ee3f-faa6-42bf-b96b-41b2cedfbba1)
on first run, they works properly : only boots are zapped.
If you toggle the checkbox, boots reappear, arms and waist are zapped.

Now...
1. Toggle zap slider checkbox at least once to remember current option
2. Set the boots slider zapped(fill the checkbox) and close Bodyslide app.
3. Start Bodyslide app again.

![ImproperZapped01](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/08642417-498a-477a-ba35-e3a18ffa2f90)
This is the first thing you see : all zapped.

![ImproperZapped02](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/3e23dca1-22a1-4dea-acef-b7e20b7366e8)
Clear the check box : now all unzapped.

If you clear checkbox, close and rerun the app, it works properly again. Of course it will fail to work properly again if you fill the checkbox before closing it.

**Comment by ousnius** [comment]
@MrAnnonymous00 This only happens when a zap that toggles other zaps is zapped by default (checkbox "Default Zapped" in OS is checked). It doesn't happen for other zaps or other toggles.

I'll see what I can do.
