### ISSUE TITLE
Undiff Slider data does not clear affected vertices status

### ISSUE THREAD

**Issue by MrAnnonymous00** [ousnius/BodySlide-and-Outfit-Studio#496]
undiff brush reduces slider's effect. If you keep using it, you can even clear the slider data as if there's no slider. But affected vertices information still stays.

![000](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/88996c5e-f5a4-4e30-b58d-c5e83eff6327)
This is Armored Coat slider set in CBBE Vanilla. Just changed project name for test.

![001](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/a9c68fbc-fa55-4553-80bc-03f38018bbe1)
Before using undiff brush. Slider inflates the mesh and affected vertices are masked properly.

Then I use undiff brush to clear the slider data. (Brush Strength to 1.00)

![002](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/04f2c8d7-ed5a-4a52-89d5-4ec366f60d75)
You can see the mesh is not inflating anymore when the slider is on. Let's mask the affected vertices.

![003](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/90162452/678e38a3-dc79-4d12-9af6-8d9267afee68)
The outfit mesh is not transforming anymore, but vertices are still masked. In fact, more vertices are masked since undiff brush touched them.

This can cause some confusion when you're trying to clear silder data from unwanted areas. For example, I'm making a slider for legs, but accidentally manupulated upper body area. Then I will use undiff brush to clear the date from upper body. When I finish the job and mask affected vertices, some vertices in upper body will still marked even there's no transforming now.

**Comment by ousnius** [comment]
Implemented, thanks for noticing this.
