### ISSUE TITLE
outfit studio not responding

### ISSUE THREAD

**Issue by TasheemTheDream** [ousnius/BodySlide-and-Outfit-Studio#500]
**Description**
whenever I try to open outfit studio whether it be through bodyslide or going directly to the application I get this error screen
![image_2023-10-03_172656980](https://github.com/ousnius/BodySlide-and-Outfit-Studio/assets/114784701/eddfc41d-d9a6-4856-94f6-8c85e054860c)
after I click ok on it. outfit studio loads up and immediately stops responding

**Comment by ProjectLuca-Dev** [comment]
It seems to me that the dev team behind Nolvus improperly configured Bodyslide. It might be worth opening an issue with them.

**Comment by ousnius** [comment]
The config file is incomplete. I can't really help with such third party projects.
