### ISSUE TITLE
Nvidia last driver

### ISSUE THREAD

**Issue by AndreyVSh** [ousnius/BodySlide-and-Outfit-Studio#504]
**Description**
546.xx driver Nvidia Game Ready (new) not working. Preview does not open and not launch OutfitStudio
Tested in Skyrim & Fallout 4
Rolling back to version 537 solves the problem

**Comment by ousnius** [comment]
Works on all driver versions with OpenGL support, unless something went wrong during the installation and the OpenGL libraries are missing,

Closing as it works for me and others.
