### ISSUE TITLE
Remove environment mapping shader flag when changing shader type

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#508]
When changing the shader type away from emvironment mapping, the corresponding shader flag should be removed.

**Comment by JohnnyBungalow** [comment]
And added if u select this shader type. It was quite confusing a couple of times already when I would select env mapping shader and not having a single clue why no cubemaps appear

**Comment by ousnius** [comment]
Changing the shader type to or away from environment mapping in Skyrim and FO4 now also adds or removes the corresponding shader flag.
@JohnnyBungalow fyi
