### ISSUE TITLE
Zap toggles not applying correctly when batch building

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#509]
Bug report from Nexus Mods:

> I've been investigating a problem and think I have a possible bug regarding Zaps, BuildSelection.xml, and Batch Building causing missing body parts etc..
> 
> The situation: On some mods a Zap toggles a secondary zap, to swap out one piece for another (like shorts / pants, for example), however BuildSelection.xml ONLY saves the zap you manually clicked on, not the secondary zaps.
> 
> When it works: When you load up one of these items in bodyslide the correct zaps are loaded from the BuildSelection.xml and their corresponding secondary zaps will flip appropriately. Then hitting BUILD works correctly as all zap are correct to the users liking. 
> 
> When it breaks: When you batch build many outfits with these kind of zaps, it appears zaps are not loaded correctly from BuildSelection.XML in the background, resulting in outfits/bodies with missing legs/arms etc. It's as if multiple conflicting zaps are applied disregarding the users selections and the zap logic applied by the mod author.
> 
> notes: I've been testing using "zeroed sliders" preset which comes with CBBE and nothing is saved into the preset.

Need to check if that's the case and if so what the issue is.

**Comment by PumpkinMaster69** [comment]
bro im having this issue real bad.
zaps that i nor the author have enabled are enabling when i do batch build.

**Comment by PumpkinMaster69** [comment]
After alot of testing i think i found the problem.

Batch build does not load hidden zap sliders even if those zaps sliders are triggered by a not hidden zap slider.
If you show all hidden zaps then batch build will load that outfit correctly.

Hope this helps :)

**Comment by ousnius** [comment]
I fixed the issue for the next version and tested a bunch of stuff:
Building, batch building, changing zaps, reopening BodySlide, batch building with a different or the same outfit selected, with or without saved zap choices for invisible zaps. Seems to work now.

@PumpkinMaster69 Thanks for the additional info.
