### ISSUE TITLE
Multiple selection of groups in bodyslide

### ISSUE THREAD

**Issue by SirDaemon** [ousnius/BodySlide-and-Outfit-Studio#512]
**What is it that you want to do that isn't currently possible?**
...

I want to be able to quickly select multiple groups/outfits etc in Bodyslide. Currently You can select all, select none or select one by one. This did not used to be much of an issue when I was just using female outfits but now that I use HIMBO  I am finding it very time consuming to select the appropriate groups or outfits.

**Request the feature**
Hold down shift key for quick multi selection. This would speed up group/outfit selection and would also conform to standard multi-selections that you get in other applications

**Comment by ousnius** [comment]
@SirDaemon This is now possible in the next version. Use Shift/CTRL to select multiple groups in the list box. Then hit the spacebar to check or uncheck the currently highlighted groups.
