### ISSUE TITLE
Gradient in a masked area can't receive sliders' data properly

### ISSUE THREAD

**Issue by JohnnyBungalow** [ousnius/BodySlide-and-Outfit-Studio#513]
When u mask an area and then smooth bits u need using Shift+LMB, the gradient area doesn't combine existing slider on this masked mesh with the new ones, this area just loses slider data.

**Comment by ousnius** [comment]
@JohnnyBungalow Conforming with a mask with gradients (or lower mask values like 0.5) now keeps the old slider data and mixes it with the slider data from the new conform based on the mask factor.

This means it's now also possible to conform parts of a shape "just a bit" by applying an e.g. 20% or 50% mask to it.
