### ISSUE TITLE
Help, image wont rotate in bodyslide or Outfit studio   preview pane

### ISSUE THREAD

**Issue by AttilaGM** [ousnius/BodySlide-and-Outfit-Studio#518]
**Description**
A clear and concise description of what the bug and the expected behavior is.

**How to reproduce** when I choose a body, and try rotating it in either bodyslide and or Outfit studio using my right mouise button, I can't seem to get it to work :( 
1. Click on '....'
2. Go to '...'
3. See error

**Comment by ousnius** [comment]
@AttilaGM I haven't heard of an issue with right-click rotation so far. What exactly is happening when you right-click and move the mouse? It just doesn't rotate?

Does the middle mouse button (scrolling wheel) work for panning the camera? Does right-click + move work in other software for you?

**Comment by AttilaGM** [comment]
Everything except for rotating around and or up and down  works 🤔

**Comment by ousnius** [comment]
@AttilaGM So panning doesn't work either? Do you have another mouse you can connect to your PC to try it out with? Do you have any weird settings in Windows, like swapping left and right buttons?

There's no way for me to debug this, I'm afraid. As I said, first time I've heard of someone having this issue.

**Comment by AttilaGM** [comment]
Panning in and ou is also fine , it’s just the right mousr button than
doesn’ rotate 97% of the time. I’ve not changed any settings because I
don’t know to 😏My mouse works fine though 👌😉

**Comment by ousnius** [comment]
@AttilaGM Open up any folder in the explorer on your PC. In a blank space, hold down the right mouse button and drag the blue selection box that (should) appear over some files in the folder.

Does the blue selection box appear as you hold down the right button?

**Comment by AttilaGM** [comment]
But, the left button highlights the text in blue

**Comment by ousnius** [comment]
@AttilaGM The right button should do that as well, so it's probably your mouse.

Change the primary button on the mouse from the left to the right button in the Windows mouse settings and try to click and drag to create a selection box on your desktop. If the box disappears without you letting go of the button you'll know the button is the problem.

**Comment by AttilaGM** [comment]
Wait, the right does a drop down and the left does a highlight. Are you
saying that both should be able to highlight the text?

**Comment by ousnius** [comment]
@AttilaGM When you hold down the left OR the right mouse button and move the mouse while holding it down, it should highlight the text in your files, yes.

If it doesn't do that for the right button, then your mouse or related driver isn't holding down the right-click correctly.

**Comment by AttilaGM** [comment]
Or just the right?

**Comment by ousnius** [comment]
@AttilaGM Both mouse buttons should do the selection box. I'm closing the issue as it has nothing to do with the program.

**Comment by AttilaGM** [comment]
Okay so now I can rotate the image using my left button and move the image
up/downf and horizontally, is that how it’s supposed to be ?🤔

**Comment by ousnius** [comment]
@AttilaGM Yes, this is how it is supposed to be for the RIGHT mouse button. Since you swapped the buttons using the Windows setting, it's now rotating for you with the LEFT mouse button.

This is confirmation that the right mouse button on your mouse is (partially) broken.
You should switch the setting back to the way it was now.

**Comment by AttilaGM** [comment]
Ok, thanks for the clarification.
