### ISSUE TITLE
Multi-select slider checkboxes using shift modifier

### ISSUE THREAD

**Issue by DoctorFraggington** [ousnius/BodySlide-and-Outfit-Studio#519]
**What is it that you want to do that isn't currently possible?**
...
I want to conform multiple sliders at once and omit multiple other sliders at once. Currently to do that I have to click on the checkbox of each box I want, one after the other, monotonously. 

**Request the feature**
...
Add perhaps a shift click to select every slider checkbox between the current checked box and a previous one.

**Comment by ousnius** [comment]
@DoctorFraggington Added for the next version using Shift key.
