### ISSUE TITLE
BodySlide does not respect NiIntegersExtraData

### ISSUE THREAD

**Issue by AciesGecko** [ousnius/BodySlide-and-Outfit-Studio#520]
**Description**
I use OS and BS for Fallout New Vegas. Asides from this issue, the program works flawlessly. 
I am using the NiIntegersExtraData property on Nifskope, to prevent neck seams on my body mesh, but I still want the rest of the normals to get recalculated. 
When manipulating the mesh on Outfit Studio, the specified vertices on the NiIntegersExtraData gets respected, and while the rest of the body normals get recalculated to take into account the shape, the neck vertices stay locked. When exporting a mesh with OS, this still gets respected. 
However this is not the case for meshes built in BodySlide, where the NiIntegersExtraData is not respected, and the output mesh brings back the neck seam, even though on the newly built mesh, the NiIntegersExtraData is still inside the .nif

Example.
The body mesh without seam, with NiIntegersExtraData property set:
![1](https://github.com/user-attachments/assets/954c15a8-993d-4f12-8651-a34e8d2db365)

As a test, I make a slider that deforms the mesh, where the normals get deformed as well, but not the ones I locked in Nifskope:
![2](https://github.com/user-attachments/assets/a0b0488b-59ed-43d4-8085-e7fea488103c)

I save the project, I build it on BodySlide then load it back to OS (or test it in-game):
![image](https://github.com/user-attachments/assets/81e99d9d-f5e1-47fe-93b8-23911ad06f29)

**Comment by ousnius** [comment]
@AciesGecko The normals locking in BodySlide only worked for BSTriShape and not for NiTriShapeData (Skyrim LE, FO3, FONV, etc.). This is now fixed.
