### ISSUE TITLE
Having an option to choose if Zaps should delete 3D shapes

### ISSUE THREAD

**Issue by ChanceXBerrus** [ousnius/BodySlide-and-Outfit-Studio#521]
A feature within the **Save Project As** dialog box or the **Zap Slider Properties** dialog box could be introduced, allowing users to opt not to completely delete the 3D shape during the zapping process and to maybe hide it instead. This would provide greater flexibility for creating intricate armors that involve numerous zaps and texture sets.

**Comment by ousnius** [comment]
@ChanceXBerrus This is now implemented.

![image](https://github.com/user-attachments/assets/e17b557c-978d-49b0-85c8-d3312832592b)
