### ISSUE TITLE
Unique Skeleton - Option to choose reference skeleton of project

### ISSUE THREAD

**Issue by foxuhound** [ousnius/BodySlide-and-Outfit-Studio#522]
Hello, currently bodyslide works primarily on humanoid PC/NPC.
but with regards to creatures or races with unique skeletons, it would need a workaround for it to function correctly due to the limitation of Reference Skeleton.

Below is an example of using OutfitStudio/BodySlide on a creature Draugr with the default humanoid reference skeleton:
![draugr bodyslide](https://github.com/user-attachments/assets/715f43cf-8e24-46a1-a862-c7932f2ab2f6)

![settings default](https://github.com/user-attachments/assets/bf2ccdf0-7cc0-4210-b0ff-44d5b7726509)

![build defskel](https://github.com/user-attachments/assets/368e38c8-64a4-4cb3-982c-40d711164b90)

the resulting mesh after build is distorted due to the reference skeleton.

This can be solved by using a different reference skeleton as seen on the pictures below:
copied the draugr skeleton into res\ folder and renamed to draugr_skeletonf.nif
![settings](https://github.com/user-attachments/assets/f91d7c21-ed29-4074-bf49-dee491ffe03f)

![build draugrskel](https://github.com/user-attachments/assets/851ef817-1214-4040-8096-2b6865b0bbf0)

the resulting mesh after build is working as expected.

**Requested Feature:**
would it be possible to add an option for a project to specify skeleton to be used for each individual project
either an option to 'not force' the reference skeleton into build and leaving the existing bones that came with the mesh
or an option to have additional save settings that would specify the skeleton it will be built with like in the picture below:
![saveas](https://github.com/user-attachments/assets/f79b3b32-cb2a-4f4b-b83b-a4f79599b6e6)

an example of a .osp output adding a tag ReferenceSkeleton

```
<?xml version="1.0" encoding="UTF-8"?>
<SliderSetInfo version="1">
    <SliderSet name="New Outfit">
        <DataFolder>New Outfit</DataFolder>
        <SourceFile>draugrmale.nif</SourceFile>
        <OutputPath>meshes\actors\draugr\character assets</OutputPath>
        <OutputFile GenWeights="false">draugrmale</OutputFile>

		<!-- <ReferenceSkeleton>res\draugr_skeletonf.nif</ReferenceSkeleton> -->

        <Shape target="ArmorWaist01">ArmorWaist01</Shape>
        <Shape target="Body_Male_Naked">Body_Male_Naked</Shape>
        <Slider name="New Slider" invert="false" default="0">
            <Data name="Body_Male_NakedNew Slider" target="Body_Male_Naked" local="true">draugrmale.osd\Body_Male_NakedNew Slider</Data>
        </Slider>
    </SliderSet>
</SliderSetInfo>
```

with this feature, bodyslide can also be used on:
creatures like werewolf, draugr, bear, etc..
mounts
custom races like supermutant (fallout) or other custom races with a unique skeleton

also i think this can be applied to separate male and female build?

*i usually mod for fallout new vegas.

**Comment by ousnius** [comment]
@foxuhound BodySlide does not touch the NIF file other than modifying vertex positions and normals/tangents. It doesn't even load the reference skeleton.

So all you need to do is do your edits in Outfit Studio using the correct skeleton. For end users of your BodySlide project, the selection won't matter.
