### ISSUE TITLE
Suggestion - Offset Meshes In .Nif File

### ISSUE THREAD

**Issue by FiftyTifty** [ousnius/BodySlide-and-Outfit-Studio#62]
An idea, that would be quite a boon for the conversion of outfits; an "Offset" slider entry.

As the program currently stands, vertices further away from the body are influenced less by the sliders (IIRC), which yields clipping, especially with more extreme silders & values. This can be witnessed, for example, by using the BBW slider I generated, and conforming the fur armour to the slider.

If you generate the outfit mesh and the baseshape separately, whilst increasing the slider values by a small margin for the outfit mesh, and merge them together, there will be less/no clipping. But that's a pain in the arse, to compare each increment to the outfit's sliders with the body mesh, merging them, etc.

For reference, the sliders I generated can be found here. http://www.nexusmods.com/skyrim/mods/59876/?

To elaborate on the offset slider idea:

If I were to have a .nif with three meshes inside it (the baseshape, a dress and an arm-band), there would be selection check-boxes pertaining to the three individual meshes.

When one is ticked, a new percentage-entry field will appear for each ticked box. You can then increase/decrease the percentage as necessary, until the clipping is reduced/gone

If the baseshape was clipping the dress, I would increase the offset percentage of the dress (100% representing the preset's total slider values) until the body was no longer clipping. For example, an offset of 125% would give that result.

This would save much hassle with editing meshes in 3DS Max, buggering around in Nifskope and the like, to achieve the same result.

Would make converting outfits much easier, especially for the end user.

**Comment by ousnius** [comment]
The offsetting of slider data etc. is a good idea in general, though the implementation probably needs a bit of work (it needs a clean UI, and needs to be revertable, ...).

I will keep it in mind for when I next do stuff with the code.

**Comment by FiftyTifty** [comment]
Awesome, thanks man.

If the UI is a pain in the neck to faff around with, perhaps delegate the offsetting of meshes to, say, a command line program? Supposing that is feasible (I.E, would save effort and require less work to create), it could easily be kept simple.

The user would run the program, with a prompt to select the outfit preset. The command line would list the meshes, with the user inputting the offset for the first mesh, then pressing enter. Repeat those steps until all the meshes have their offsets inputted, and then the outfit would be exported.

Of course, having the offsetting integrated would be best, as far as maximum usability goes, but again, if it would save effort, I'd advise making it a separate program.

Either way, you have my thanks for continuing with developing Bodyslide. Keep up the good work.

**Comment by ousnius** [comment]
Added a minus and plus button beneath the edit button when clicked to
scale the slider data (not the shape) up and down.
