### ISSUE TITLE
Import obj into Outfit Studio used all RAM

### ISSUE THREAD

**Issue by Jet4571** [ousnius/BodySlide-and-Outfit-Studio#84]
When importing a .obj file into Outfit Studio V3.0 it kept loading until all 16GB of my ram was used and crashed with a fatal Exception. Textures were not included and the Z-Y axis wasn't flipped when exporting.

http://www.mediafire.com/download/ulcou9bixv87uv3/CuteYen.zip

**Comment by Jet4571** [comment]
Problem is semi solved. exporting a .obj from 3DS Max 2016 requires the obj exporter to use the blender preset setting rather than default. Z-Y axis swap ofcourse should be off.

The file uploaded is way off in scale, importing the CBBE_HD_Base.fbx with default settings shrunk it, needed units to be set to centimeters in the importer to scale with previous games .nif files.

The Bethesda employee who made the new .nif format and Todd Howard who approved it needs a swift hard kick in the nuts everyday for a week for this BS.

**Comment by ousnius** [comment]
Outfit Studio is getting confused by the smooth shading groups in your OBJ file:
s 1, s 2, s 4, s 8, s 16, s 32, s 64, s 128, s off

It's thinking those are supposed to be objects ('g', 'o' and 's') and randomly replacing internal data with them.

However, something else is causing the crash. A vertex index within a face (4896) is 1 above the maximum index, but I don't exactly know why this works with other OBJ files.

**Comment by ousnius** [comment]
Fixed in c4ab8f5.
