### ISSUE TITLE
Crash when entering slider edit mode

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#90]
How to reproduce:
- Create a conversion project (f.e. 7B to CBBE) and load an outfit with multiple meshes
- Conform all
- While the sliders are conforming, you can edit the conversion slider
- Crash

Expected Behaviour:
Either show an info dialog, that you need to wait for the sliders to conform, or queue the task (editing the slider) after the conform all task.

**Comment by CNKTHoward** [comment]
Above steps don't always seem to work. What I could reproduce by 100% is the following:
1. Create Project
2. Convert XY to CBBE
3. Choose a file (then delete the included body if any)
4. Conform all (ctrl+shift+c)
5. Edit slider
6. Set Base Shape
7. Load Reference (UUNP)
8. Conform all
9. Copy Bone Weights
10. Edit Mesh with Inflate Brush
11. Edit (Pencil icon) any Slider, then edit the mesh
12. ~~Deactivate the slider (Pencil icon)~~ I tried it without deactivating the slider when debugging, and it crashed more often...
13. Save As

Repeat 1. - 5. with a new project and it should crash

**Comment by ousnius** [comment]
Tried editing the sliders/shapes while conforming - doesn't work, the program is waiting until the conforming is over already. I couldn't get it to crash either with any combo of references, conforming or editing sliders. :/

**Comment by CNKTHoward** [comment]
Hm, interesting. At least the crash for me occurs when I want to edit the conversion slider. I should try to set up the project and debug it...

**Comment by CNKTHoward** [comment]
If I should create a new issue for this, please let me know:
I just tried to set up the project. I guess the stuff "Compilation requirements" doesn't require the stuff under "Compiling with Visual Studio 2013".
Anyway, I cloned this repo, downloaded the wxWidgets 3.0.2 installer and isntalled to <project>/wxWidgets, FBX SDK to <project>/libraries/fbx. I even double checked the projects include path, and the folders themselves to see if everything was there. Still, Visual Studio can't find the <wx/xyz.h> headers. C++ is installed (v12), using Visual Studio 2013 Ultimate x86.

Errors look as follows:
```cpp
bodyslide-and-outfit-studio\stdafx.h(8): fatal error C1083: Cannot open include file: 'wx/wx.h': No such file or directory
```

**Comment by CNKTHoward** [comment]
I debugged Outfit Studio (damn OS is slow when debugging) and tried to reproduce the error. I tried the above 4 times, it crashed every time. This is what happened:
Call stack:
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/dev/OutfitStudio.cpp#L665
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/dev/TweakBrush.h#L524
https://github.com/ousnius/BodySlide-and-Outfit-Studio/blob/dev/TweakBrush.h#L504

```
First-chance exception at 0x00C20D5B in BodySlide Debug.exe: 0xC0000005: Access violation reading location 0x91AD3D08.
Unhandled exception at 0x00C20D5B in BodySlide Debug.exe: 0xC000041D: Ausnahmefehler während eines Benutzerrückrufs.
```

Another error I got at the same line was:

```
File: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector
Line: 1201

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
Detected memory leaks!
Dumping objects ->
{25271257} normal block at 0x19475830, 32 bytes long.
 Data: <UNP Perky High t> 55 4E 50 20 50 65 72 6B 79 20 48 69 67 68 20 74 
...
Object dump complete.
```

There were quite a few elements in the vector as you can see by the index (although not every index had an element... for example {90} was dumped, and the next was {92}, skipping 91)

I can investigate further, but you would have to push me into the right direction - I have no idea where to look ;)

But according to the error message it seems as if the vector's size gets wrongly allocated when editing a slider under some condition(s) and thus it fails.

**Comment by ousnius** [comment]
Thanks for looking into it, can you try again with this commit?

**Comment by CNKTHoward** [comment]
Seems fixed (built release x64). Might need some more testing though - so I will re-open the issue if another related crash occurs. Thanks for the quick fix!

**Comment by CNKTHoward** [comment]
Btw, you committed those lines:
```
glView->SetStrokeManager(nullptr);
glView->GetStrokeManager()->Clear();
```

Shouldn't they be in reversed order? Not exactly sure what happens internally, but if you set the stroke manager to a nullptr, then calling Clear on it won't do anything (assumed that the Getter returns the object set in the Setter).
