### ISSUE TITLE
Hotkeys for viewport

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#91]
This is a feature request - I'm not sure if it's implented already but couldn't find anything.

Basically it would be nice if you could change the viewport (front, back, left, right, mode) with hotkeys (f.e. numpad).

**Comment by ousnius** [comment]
Implemented, but using Shift+1 to 5 instead. Couldn't get the numpad to work properly.

**Comment by CNKTHoward** [comment]
Shift+1-5 is even better, thanks!
