### ISSUE TITLE
Possible OSD bloat

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#93]
I converted an armor to UUNP and checked all the sliders (edit mode) to see if there was some clipping (only a few needed adjustments, mainly the UNP Variant sliders). The OSD-File now has 43 MB, and it's generated TRI-File has ~29 MB. 
My assumption is, that there is data generated for the sliders I edited, even though I didn't change anything.

I can send you the files (originals and my conversion) if you need them.

**Comment by ousnius** [comment]
Not necessarily - can you check how many vertices all shapes of the outfit's NIF have combined? (without the body shape)

The TRI file is smaller because it uses 2 bytes per value, while OSD files have to use 4 bytes (except for the index).

**Comment by CNKTHoward** [comment]
I hope that this is the right information, but the outfit (without the body, as you asked) has 38,012 Vertices.

**Comment by ousnius** [comment]
Yeah, then the size is most likely actually that much.

UUNP has a looot of sliders (and most of them are full-body sliders), so there's a ton of data being created for a ton of vertices.

**Comment by CNKTHoward** [comment]
If the slider data isn't changed though, can't the data be calculated once it's meshes are created? The same thing happens when saving the project anyway. I'd rather have to wait 1-2 seconds longer for the mesh to create than have a 40-50 MB file instead of a ~5-10 MB file :/

**Comment by ousnius** [comment]
What do you mean? There is no unnecessary data in your OSD. All of the data in there is required for the sliders that have data to work. If a slider is empty, then there's no data for it in the OSD.

The file can't get any smaller, unless you remove sliders or give the meshes a lower resolution.

**Comment by CNKTHoward** [comment]
Well I didn't have the time to get into the code, so I'm just assuming here how things work and play together. What I'm saying is, if you create a new project and get your sliders through a reference, what data do the sliders have? So they data for the sliders that are generated for the project when loading a reference are kinda the default for this project (as long as you don't change any other sliders that is). 
Again, just assuming here: If this defaulty data can be calculated from the current project, the same could happen when you create meshes for an outfit, assuming that the slider data hasn't been changed manually... Does that make sense?

**Comment by ousnius** [comment]
You're saying you did "New Project", then "Save Project As" right away and the OSD file was already that big? As in, you didn't "Conform All" yet?

**Comment by CNKTHoward** [comment]
No, I did conform all... Hm I might've gotten that wrong. Is the slider data for other sliders changed too, when I only change the base shape (without editing any slider) AND/OR are they changed when I edit any other slider?

**Comment by ousnius** [comment]
As soon as you hit "Conform All", the slider data is generated for all shapes and all sliders (from the reference to the other shapes). This is the point where you have the maximum amount of data in the project.

Editing any sliders at this point (or not doing so) neither adds nor removes much bytes of data anymore.

**Comment by CNKTHoward** [comment]
Alright, but do sliders influence each other? If so, I didn't have the impression that they did. Editing a slider only adds data to the slider, right? I'm just asking, because if they don't, "Conform All" would always generate the same data for the same outfit, no matter when you hit it. (as far as I know, Slider data also is reset to it's "vanilla" state). Since this state is always the same, the data generation for the sliders could be delayed to a much later point - namely when the user generates an outfit. The OSD file would only have to include slider data, that aren't "vanilla" anymore, or in other words: As soon as a slider is edited by a user, it's data is to be included in the OSD-file. This idea is all based on the assumption that sliders don't influence each other when editing or conforming though.

**Comment by ousnius** [comment]
No, you're looking at it the wrong way. BodySlide does not create any slider data, it's not something that magically exists, even in its vanilla state. Using "Conform All" is what creates the initial slider data.

Outfit Studio has to save the full OSD file, because otherwise, there would be no slider. The vanilla state of the slider is just as important to have as any edits that are done to it.

The result that Conform All creates will be different when either 1.) you brush edits into the reference shape, or 2.) you edit a slider for the reference.

Sliders don't influence each other, but that doesn't really have anything to do with this.
If there was no OSD, you wouldn't have sliders in BodySlide. It can't be delayed.

**Comment by CNKTHoward** [comment]
Ah ok. So I thought the slider data was generated based on some reference data (like CBBE or UUNP reference meshes) and the actual outfit.

**Comment by ousnius** [comment]
Conforming is running an approximation algorithm that looks at the nearest vertices of the outfit to the vertices of the reference that are affected by each slider.

So when either the reference or outfit take up a different shape, conforming will result in a different slider (minimally).

Reference has a breast slider -> conforming takes a look at the outfit to see which vertices of it are near the breasts of the reference, then generates a morph that "conforms" to the one of the reference.

Bone weight copying is using the same algorithm, by the way.

**Comment by CNKTHoward** [comment]
Ah ok, got you. Conforming is done only once (at the start when creating a conversion) though, right? 

And different sliders of a reference have other ... I'll call it "referenced vertices" on which the algorithm has to perform on (like "back", "waist", etc.)?

**Comment by ousnius** [comment]
Yeah. You conform all sliders to the outfit once. That's your initial data (and as big as the .OSD will get).

This is done so you don't have to manually brush each single slider for all shapes from scratch, which would take about 1 week per outfit.

Then you edit the slider data that came from the conforming manually using brushes, to reduce clipping and increase quality.

**Comment by CNKTHoward** [comment]
Ok, so I conform all the sliders, and then edit the base mesh for above stated reasons. As you said though, conforming is only "running an algorithm", that happens once. So if you edit the mesh, the slider data doesn't change? Or did I get that wrong...

**Comment by ousnius** [comment]
If you edit the base shape of the mesh, the slider data doesn't change (but what was conformed earlier is still there and needs to be there). The results will change, but not the data.

If you edit the shape of a slider, the slider data obviously does change.

**Comment by CNKTHoward** [comment]
Oh ok, that explains it all. I thought the conformation data could be created at any given time. Thanks for the clearification!
