### ISSUE TITLE
Confirm Dialog when conforming after mesh editing

### ISSUE THREAD

**Issue by CNKTHoward** [ousnius/BodySlide-and-Outfit-Studio#95]
Since you only have to conform the sliders once for any outfit, a confirmation dialog that comes up if you want to conform although you already did some work would be really nice. 
It occassionally happened to myself, that out of force of habbit I pressed ctrl+shift+c, and all the data is gone.

**Comment by ousnius** [comment]
That would mean I have to add a conformation dialog to a lot of other places in the programs, such as copying bone weights or setting the base shape. I don't really want to do that for all of them as they add more clicks and generally "Do you really want to?" scares off new users, in my opinion.

The way to prevent that is to save the project multiple times during your work and honestly, pressing CTRL+Shift+C is a rather acrobatic thing to do. :P

Not doing this one for now, sorry. :/
