### ISSUE TITLE
Conditional Zap Sliders

### ISSUE THREAD

**Issue by RustyXXL** [ousnius/BodySlide-and-Outfit-Studio#97]
As per the PM on the Nexus here the Issue/feature suggestion for Conditional Zap Sliders, where the state of 1 (hidden) Zap Slider depends on the state of another, that the user is able to choose.

I have 2 use cases in mind, that would make things for the enduser easier and avoid problems/user error:
1. I recently learned that the matte black version of the colossus Bodysuite comes with it's own meshes. I would like to implement it so that when the User selects the matte black version in BS, the default chrome version gets automatically zapped away. Of course I could simply add a second Outfit overwriting the same file, or leave it to the user to correctly zap one or the other, but this would make it more elegant.
2. I plan on including 1 or more nevernude options to some outfits that otherwise might show nudity. Adding a conditional Zap slider that hides parts of the reference shape depending on wether the Nevernude option is selected or not, would go miles for preventing potential clipping issues.

There are other possible solutions, but this would make things more elegant for the enduser.

**Comment by ousnius** [comment]
To stop the user from bringing the toggle out of alignment, hide the zaps that would be toggled so they can't be used manually.

**Comment by ousnius** [comment]
If you want two zaps toggling the same other zap properly, you will need to create the target zap twice and assign one to each.
