### ISSUE TITLE
Holding Ctrl and clickin while "Navigate and select meshes" brush is active causes OS to crash

### ISSUE THREAD

**Issue by ofus** [ousnius/BodySlide-and-Outfit-Studio#98]
When starting OS and loading a project, the default brush is" navigate and select meshes". If you hold Ctrl and click the mesh while that brush is active, it freezes/crashes OS and BS.

**Comment by ousnius** [comment]
Couldn't replicate with multiple meshes and procedures, so I'll close the issue for now until someone finds a way to replicate it 100%.
